import logoUrl from "../assets/chineseverse-logo-matte.png";

// The real ChineseVerse logo. The source lives in frontend/photo/ and is
// never edited; this is its matte, generated by scripts/build_brand_assets.mjs
// (background lifted out, every artwork pixel unchanged). Re-run that script
// if the source logo is ever replaced.
//
// Two variants, both cut from this one asset:
//   "lockup" — the full horizontal lockup (pagoda-and-book emblem +
//     "ChineseVerse" wordmark), the default wherever there is room for it.
//   "mark"   — the emblem alone, cropped out of the same 1753x591 PNG for
//     the collapsed sidebar. Keeping it a crop means the sidebar mark can
//     never drift out of sync with the full logo.
//
// The matte is shown with no background at all, straight on the page in
// both themes; the favicons are the same transparent emblem.
//
// Sizing lives entirely in CSS (.brand-logo* in index.css) so the image
// is always driven by a single dimension with the other left to `auto` —
// the browser preserves the intrinsic 1753:591 ratio, so the logo can't be
// stretched or squashed at any breakpoint.
export default function BrandLogo({ variant = "lockup", className = "", ...rest }) {
  return (
    <span className={`brand-logo brand-logo--${variant}${className ? ` ${className}` : ""}`}>
      <img
        className="brand-logo__img"
        src={logoUrl}
        alt="ChineseVerse"
        draggable="false"
        decoding="async"
        {...rest}
      />
    </span>
  );
}
