from fastapi import APIRouter, Depends
from pydantic import BaseModel, Field
from sqlalchemy.orm import Session

from app import models
from app.database import get_db
from app.deps import get_current_user, get_locale
from app.services import ai_client, lesson_path
from app.services.dna import compute_dna
from app.services.gamification import ensure_user_skills, user_rank
from app.services.localization import load_translations, tr
from app.services.practice import review_counts

router = APIRouter(prefix="/api/assistant", tags=["assistant"])


class ChatMessage(BaseModel):
    role: str = Field(pattern="^(user|assistant)$")
    content: str = Field(min_length=1, max_length=2000)


class AssistantRequest(BaseModel):
    messages: list[ChatMessage] = Field(min_length=1, max_length=20)


class AssistantResponse(BaseModel):
    reply: str
    # "ai" = generated by the live model, "offline" = the fallback used when
    # no model is configured or the call failed.
    source: str = "ai"


@router.post("/chat", response_model=AssistantResponse)
def chat(
    payload: AssistantRequest,
    user: models.User = Depends(get_current_user),
    db: Session = Depends(get_db),
    locale: str = Depends(get_locale),
):
    ensure_user_skills(db, user)
    level, mastery = user_rank(db, user)
    skills = sorted((s for s in user.user_skills if s.skill), key=lambda s: s.mastery)
    skill_tr = load_translations(db, "skill", [str(s.skill.id) for s in skills], locale)
    # Same localized skill names the dashboard/DNA pages show, so a reply
    # in the selected language doesn't splice in English skill names.
    skill_name = {s.id: tr(skill_tr, s.skill.id, "name", s.skill.name) for s in skills}
    practised = any(s.mastery > 0 for s in skills)
    dna = compute_dna(user)

    context = {
        "username": user.username,
        "hsk_level": level,
        "mastery": mastery,
        "streak": user.streak.current_streak if user.streak else 0,
        # With every skill still at 0 there is no "weakest" -- naming two
        # arbitrary ones would hand the model a fact that isn't true.
        "weak_skills": [skill_name[s.id] for s in skills[:2]] if practised else [],
        "skill_mastery": [f"{skill_name[s.id]} {round(s.mastery)}%" for s in skills] if practised else [],
        "dna_overall": dna["overall"],
        "words_mastered": dna["words_mastered"],
        "companion": user.animal.name if user.animal else None,
    }
    # Read-only: these are the same counts the dashboard and Review page show,
    # handed to the model as context so "what should I practise?" is grounded
    # in the learner's real queue. Nothing here writes progress.
    due = review_counts(db, user)
    context["due_reviews"] = due["total"] + due["mistakes"]
    context["open_mistakes"] = due["mistakes"]
    recent = (
        db.query(models.LearningMistake)
        .filter(models.LearningMistake.user_id == user.id, models.LearningMistake.mastered.is_(False))
        .order_by(models.LearningMistake.last_seen_at.desc())
        .limit(3)
        .all()
    )
    context["recent_mistakes"] = [
        f"{m.mistake_type} {m.reference}"
        + (f" (answered {m.answer_given}, correct {m.correct_answer})" if m.answer_given and m.correct_answer else "")
        for m in recent
    ]
    context["completed_lessons"] = (
        db.query(models.Progress)
        .filter(models.Progress.user_id == user.id, models.Progress.status == "completed")
        .count()
    )
    # Where the learner really is in the curriculum: the lesson path's
    # current lesson (server-side, services/lesson_path.py), in their language.
    state = lesson_path.path_state(db, user)
    if state.current is not None:
        cur = state.current.lesson
        lesson_tr = load_translations(db, "lesson", [str(cur.id)], locale)
        context["current_lesson"] = tr(lesson_tr, cur.id, "title", cur.title)
        context["current_lesson_level"] = state.current.level
    # At the exam gate there is no current lesson: the next real step is the
    # level's final exam, so the assistant must not suggest lessons past it.
    if state.exam_level is not None:
        context["pending_exam_level"] = state.exam_level
    if state.exams_passed:
        context["exams_passed"] = sorted(state.exams_passed)
    reply, source = ai_client.assistant_reply(
        [m.model_dump() for m in payload.messages], context, locale
    )
    return AssistantResponse(reply=reply, source=source)
