"""Hand-written dialogue scripts for Real Chinese (services/real_life.py).

Content, not progress: every scene is one real-life situation scripted at
three tiers, so a beginner and an advanced learner never get the same
conversation -- the tiers differ in vocabulary, grammar, sentence length,
number of exchanges and how many replies they choose from:

  beginner      HSK 1-2 words, short sentences, 3 exchanges, 3 replies
  intermediate  HSK 3-4 words and patterns, 4 exchanges, 3 replies
  advanced      HSK 5+ words, complex sentences, 5 exchanges, 4 replies

One exchange is the other person's line plus the learner's fitting reply
(each with pinyin and an EN/RU/TG translation -- Chinese and pinyin are
never translated, and zh UI users read the English gloss, like the rest of
the practice engine) and the wrong replies offered next to it. Beginner
wrong replies carry pinyin because that tier shows pinyin on every option.

`focus` is the exchange's key curriculum word. Practice resolves it to the
real VocabularyWord row, so answering the exchange schedules that word for
review like any other practice answer (tests/real_life_test.py checks that
every focus word exists in the curriculum).
"""

from __future__ import annotations


def X(npc, reply, wrong, focus):
    """One exchange: npc/reply = (zh, pinyin, en, ru, tg)."""
    return {
        "npc": {"zh": npc[0], "py": npc[1], "tr": {"en": npc[2], "ru": npc[3], "tg": npc[4]}},
        "reply": {"zh": reply[0], "py": reply[1], "tr": {"en": reply[2], "ru": reply[3], "tg": reply[4]}},
        "wrong": [w if isinstance(w, tuple) else (w, "") for w in wrong],
        "focus": focus,
    }


def T(en, ru, tg, zh):
    return {"en": en, "ru": ru, "tg": tg, "zh": zh}


SCENES = [
    {
        "slug": "restaurant",
        "icon": "🍜",
        "title": T("Restaurant", "Ресторан", "Тарабхона", "餐厅"),
        "description": T(
            "Get a table, order food and pay the bill.",
            "Займите столик, закажите еду и оплатите счёт.",
            "Ҷой гиред, хӯрок фармоиш диҳед ва ҳисобро пардохт кунед.",
            "找座位、点菜、结账。",
        ),
        "npc": {"zh": "服务员", "role": T("Waiter", "Официант", "Пешхизмат", "服务员")},
        "tiers": {
            "beginner": [
                X(("你好！你们几位？", "nǐ hǎo! nǐmen jǐ wèi?", "Hello! How many people?", "Здравствуйте! Сколько вас?", "Салом! Шумо чанд нафаред?"),
                  ("两位，谢谢。", "liǎng wèi, xièxie.", "Two, thank you.", "Двое, спасибо.", "Ду нафар, ташаккур."),
                  [("我是学生。", "wǒ shì xuésheng."), ("今天星期一。", "jīntiān xīngqīyī.")], "谢谢"),
                X(("你想吃什么？", "nǐ xiǎng chī shénme?", "What would you like to eat?", "Что вы хотите съесть?", "Шумо чӣ хӯрдан мехоҳед?"),
                  ("我想吃米饭和鸡蛋。", "wǒ xiǎng chī mǐfàn hé jīdàn.", "I'd like rice and eggs.", "Я хочу рис и яйца.", "Ман биринҷ ва тухм хӯрдан мехоҳам."),
                  [("我去医院。", "wǒ qù yīyuàn."), ("我有一个哥哥。", "wǒ yǒu yí ge gēge.")], "米饭"),
                X(("你要喝什么？", "nǐ yào hē shénme?", "What would you like to drink?", "Что будете пить?", "Чӣ менӯшед?"),
                  ("我要一杯茶。", "wǒ yào yì bēi chá.", "A cup of tea, please.", "Мне чашку чая.", "Ба ман як пиёла чой."),
                  [("我喜欢看书。", "wǒ xǐhuan kàn shū."), ("他在家。", "tā zài jiā.")], "茶"),
            ],
            "intermediate": [
                X(("欢迎光临！请问有预订吗？", "huānyíng guānglín! qǐngwèn yǒu yùdìng ma?", "Welcome! Do you have a reservation?", "Добро пожаловать! У вас есть бронь?", "Хуш омадед! Шумо ҷой брон кардаед?"),
                  ("没有预订，还有空位吗？", "méiyǒu yùdìng, hái yǒu kòng wèi ma?", "No reservation — are there any free tables?", "Брони нет. Есть свободные места?", "Брон надорем, ҷойи холӣ ҳаст?"),
                  ["我已经吃饱了，谢谢。", "明天会下雨吗？"], "预订"),
                X(("这是菜单。今天的鱼很新鲜。", "zhè shì càidān. jīntiān de yú hěn xīnxiān.", "Here's the menu. Today's fish is very fresh.", "Вот меню. Сегодня очень свежая рыба.", "Ин меню. Моҳии имрӯза хеле тоза аст."),
                  ("那我点一条鱼，不要太辣。", "nà wǒ diǎn yì tiáo yú, bú yào tài là.", "Then I'll order a fish, not too spicy.", "Тогда я закажу рыбу, только не слишком острую.", "Пас ман як моҳӣ фармоиш медиҳам, на он қадар тунд."),
                  ["我的手机没电了。", "这本书是我朋友的。"], "新鲜"),
                X(("鱼需要等二十分钟，可以吗？", "yú xūyào děng èrshí fēnzhōng, kěyǐ ma?", "The fish takes twenty minutes — is that OK?", "Рыбу придётся ждать двадцать минут, хорошо?", "Моҳӣ бист дақиқа интизорӣ мехоҳад, мешавад?"),
                  ("没问题，我们不着急。", "méi wèntí, wǒmen bù zháojí.", "No problem, we're not in a hurry.", "Без проблем, мы не торопимся.", "Мушкиле нест, мо шитоб надорем."),
                  ["我坐地铁去公司。", "她比我高一点儿。"], "着急"),
                X(("菜都上齐了，还需要别的吗？", "cài dōu shàng qí le, hái xūyào bié de ma?", "All the dishes are here — anything else?", "Все блюда поданы. Ещё что-нибудь?", "Ҳамаи хӯрокҳо оварда шуданд, боз чизе лозим аст?"),
                  ("不用了，请帮我们结账。", "búyòng le, qǐng bāng wǒmen jiézhàng.", "No thanks — the bill, please.", "Нет, спасибо. Рассчитайте нас, пожалуйста.", "Не, лозим нест, лутфан ҳисобро биёред."),
                  ["我每天早上跑步。", "这个周末我要搬家。"], "需要"),
            ],
            "advanced": [
                X(("不好意思，靠窗的位子已经满了，您介意坐在里面吗？", "bù hǎoyìsi, kào chuāng de wèizi yǐjīng mǎn le, nín jièyì zuò zài lǐmiàn ma?", "Sorry, the window seats are full — would you mind sitting further inside?", "Извините, места у окна заняты. Вы не против сесть в глубине зала?", "Бубахшед, ҷойҳои назди тиреза пур шудаанд. Шумо дар дарун нишастанро зид нестед?"),
                  ("不介意，只要安静一点儿就行。", "bú jièyì, zhǐyào ānjìng yìdiǎnr jiù xíng.", "I don't mind, as long as it's a bit quiet.", "Не против, лишь бы было потише.", "Зид нестам, фақат каме ором бошад, бас аст."),
                  ["这件衣服打八折。", "我昨天把护照弄丢了。", "他的汉语水平越来越高。"], "介意"),
                X(("我们的招牌菜是宫保鸡丁，不过有点儿辣。", "wǒmen de zhāopai cài shì gōngbǎo jīdīng, búguò yǒudiǎnr là.", "Our signature dish is Kung Pao chicken, though it's a little spicy.", "Наше фирменное блюдо — курица гунбао, правда, она немного острая.", "Таоми махсуси мо мурғи гунбао аст, вале каме тунд аст."),
                  ("我不太能吃辣，能不能少放点辣椒？", "wǒ bú tài néng chī là, néng bu néng shǎo fàng diǎn làjiāo?", "I can't handle spicy food well — could you use less chili?", "Я плохо переношу острое. Можно положить поменьше перца?", "Ман тундро хуб хӯрда наметавонам, метавонед қаламфури камтар андозед?"),
                  ["这个问题值得我们认真讨论。", "请把行李放在安检机上。", "我打算下个月去面试。"], "辣"),
                X(("当然可以。另外，今天店里有活动，消费满两百打九折。", "dāngrán kěyǐ. lìngwài, jīntiān diàn li yǒu huódòng, xiāofèi mǎn liǎng bǎi dǎ jiǔ zhé.", "Of course. Also, there's a promotion today: 10% off when you spend over 200.", "Конечно. Кроме того, сегодня акция: при заказе от 200 скидка 10%.", "Албатта. Ғайр аз ин, имрӯз аксия ҳаст: аз 200 зиёд харҷ кунед, 10% тахфиф."),
                  ("那太划算了，我们再加一个汤吧。", "nà tài huásuàn le, wǒmen zài jiā yí ge tāng ba.", "That's a great deal — let's add a soup then.", "Это очень выгодно — тогда добавим ещё суп.", "Ин хеле фоиданок аст, пас боз як шӯрбо илова мекунем."),
                  ["他终于通过了考试。", "我们的航班推迟了。", "医生建议我多休息。"], "活动"),
                X(("这道菜还合您的口味吗？", "zhè dào cài hái hé nín de kǒuwèi ma?", "Is the dish to your taste?", "Блюдо вам по вкусу?", "Ин таом ба таъми шумо мувофиқ аст?"),
                  ("味道很地道，就是稍微有点儿咸。", "wèidao hěn dìdao, jiùshì shāowēi yǒudiǎnr xián.", "It tastes authentic, just a little salty.", "Вкус настоящий, только чуть солоновато.", "Таъмаш аслӣ аст, танҳо каме шӯр аст."),
                  ["我已经在网上预约了挂号。", "房间里的空调坏了。", "请问去机场的大巴几点发车？"], "味道"),
                X(("一共三百二十块，您用现金还是手机支付？", "yígòng sānbǎi èrshí kuài, nín yòng xiànjīn háishi shǒujī zhīfù?", "320 yuan in total — cash or mobile payment?", "Всего 320 юаней — наличными или через телефон?", "Ҳамагӣ сесаду бист юан, нақд ё бо телефон пардохт мекунед?"),
                  ("我扫码付吧，麻烦你把发票也开一下。", "wǒ sǎo mǎ fù ba, máfan nǐ bǎ fāpiào yě kāi yíxià.", "I'll scan the code to pay — and could you issue a receipt too?", "Оплачу по QR-коду. И выпишите, пожалуйста, чек.", "Ман бо скани код пардохт мекунам, лутфан фактураро ҳам нависед."),
                  ["我小时候在农村长大。", "这次会议改到周五了。", "你的建议非常有道理。"], "现金"),
            ],
        },
    },
    {
        "slug": "train-station",
        "icon": "🚉",
        "title": T("Train station", "Вокзал", "Истгоҳи роҳи оҳан", "火车站"),
        "description": T(
            "Buy a ticket, handle a delay and find your platform.",
            "Купите билет, разберитесь с задержкой и найдите платформу.",
            "Чипта харед, бо таъхир кор кунед ва платформаро ёбед.",
            "买票、处理晚点、找站台。",
        ),
        "npc": {"zh": "售票员", "role": T("Ticket clerk", "Кассир", "Кассир", "售票员")},
        "tiers": {
            "beginner": [
                X(("你好，你去哪儿？", "nǐ hǎo, nǐ qù nǎr?", "Hello, where are you going?", "Здравствуйте, куда вы едете?", "Салом, шумо ба куҷо меравед?"),
                  ("我去北京。", "wǒ qù Běijīng.", "I'm going to Beijing.", "Я еду в Пекин.", "Ман ба Пекин меравам."),
                  [("我喜欢吃苹果。", "wǒ xǐhuan chī píngguǒ."), ("这是我妈妈。", "zhè shì wǒ māma.")], "去"),
                X(("你要几张票？", "nǐ yào jǐ zhāng piào?", "How many tickets do you want?", "Сколько билетов вам нужно?", "Ба шумо чанд чипта лозим аст?"),
                  ("我要一张票。", "wǒ yào yì zhāng piào.", "One ticket, please.", "Мне один билет.", "Ба ман як чипта."),
                  [("我八点起床。", "wǒ bā diǎn qǐchuáng."), ("天气很冷。", "tiānqì hěn lěng.")], "票"),
                X(("火车下午三点开。", "huǒchē xiàwǔ sān diǎn kāi.", "The train leaves at 3 p.m.", "Поезд отправляется в три часа дня.", "Қатора соати сеи рӯз ҳаракат мекунад."),
                  ("好的，谢谢你！", "hǎo de, xièxie nǐ!", "OK, thank you!", "Хорошо, спасибо!", "Хуб, ташаккур!"),
                  [("我没有妹妹。", "wǒ méiyǒu mèimei."), ("他是医生。", "tā shì yīshēng.")], "火车"),
            ],
            "intermediate": [
                X(("您好，请出示一下您的身份证。", "nín hǎo, qǐng chūshì yíxià nín de shēnfènzhèng.", "Hello, please show your ID card.", "Здравствуйте, покажите, пожалуйста, удостоверение личности.", "Салом, лутфан шаҳодатномаи шахсиятатонро нишон диҳед."),
                  ("我是外国人，可以用护照吗？", "wǒ shì wàiguó rén, kěyǐ yòng hùzhào ma?", "I'm a foreigner — can I use my passport?", "Я иностранец. Можно по паспорту?", "Ман хориҷӣ ҳастам, бо шиноснома мешавад?"),
                  ["我已经吃过晚饭了。", "这个颜色不太适合我。"], "护照"),
                X(("可以。您要买去上海的哪一趟车？", "kěyǐ. nín yào mǎi qù Shànghǎi de nǎ yí tàng chē?", "Sure. Which train to Shanghai do you want?", "Можно. На какой поезд до Шанхая вам билет?", "Мешавад. Ба кадом қатораи Шанхай чипта мехаред?"),
                  ("最早的那趟高铁，还有座位吗？", "zuì zǎo de nà tàng gāotiě, hái yǒu zuòwèi ma?", "The earliest high-speed train — are there seats left?", "На самый ранний скоростной. Места ещё есть?", "Қатораи тезгарди аз ҳама барвақт, ҷой боқӣ мондааст?"),
                  ["我打算周末去爬山。", "你的中文说得真好。"], "座位"),
                X(("二等座只剩下靠过道的了。", "èr děng zuò zhǐ shèng xià kào guòdào de le.", "Only aisle seats are left in second class.", "Во втором классе остались только места у прохода.", "Дар дараҷаи дуюм танҳо ҷойҳои назди гузаргоҳ монданд."),
                  ("没关系，就要过道的吧。", "méi guānxi, jiù yào guòdào de ba.", "That's fine, I'll take an aisle seat.", "Ничего, давайте у прохода.", "Ҳеҷ гап не, ҳамон ҷойи назди гузаргоҳро диҳед."),
                  ["我的钥匙找不到了。", "他们正在开会呢。"], "没关系"),
                X(("一共五百五十三元。在第七站台上车。", "yígòng wǔbǎi wǔshísān yuán. zài dì qī zhàntái shàng chē.", "553 yuan in total. Board at platform 7.", "Всего 553 юаня. Посадка на седьмой платформе.", "Ҳамагӣ панҷсаду панҷоҳу се юан. Саворшавӣ аз платформаи ҳафтум."),
                  ("请问要提前多长时间进站？", "qǐngwèn yào tíqián duō cháng shíjiān jìn zhàn?", "How early should I go through to the platform?", "Скажите, за сколько времени нужно пройти на посадку?", "Бигӯед, чанд вақт пеш ба истгоҳ дароям?"),
                  ["我觉得这部电影很有意思。", "我妹妹在大学学习法律。"], "提前"),
            ],
            "advanced": [
                X(("由于天气原因，G102次列车晚点了大约四十分钟。", "yóuyú tiānqì yuányīn, G yāo líng èr cì lièchē wǎndiǎn le dàyuē sìshí fēnzhōng.", "Due to the weather, train G102 is delayed by about forty minutes.", "Из-за погоды поезд G102 задерживается примерно на сорок минут.", "Аз сабаби обу ҳаво қатораи G102 тақрибан чил дақиқа дер мекунад."),
                  ("那我恐怕赶不上在南京的换乘了，怎么办？", "nà wǒ kǒngpà gǎn bu shàng zài Nánjīng de huànchéng le, zěnme bàn?", "Then I'm afraid I'll miss my connection in Nanjing — what should I do?", "Тогда я, боюсь, не успею на пересадку в Нанкине. Что делать?", "Пас метарсам, ки ба ивази қатора дар Нанкин намерасам, чӣ кор кунам?"),
                  ["这家公司的福利待遇相当不错。", "请把垃圾分类以后再扔。", "他从小就对音乐很感兴趣。"], "恐怕"),
                X(("您可以去改签窗口，免费改到下一班。", "nín kěyǐ qù gǎiqiān chuāngkǒu, miǎnfèi gǎi dào xià yì bān.", "You can go to the rebooking window and change to the next train for free.", "Подойдите к окну переоформления — билет на следующий поезд поменяют бесплатно.", "Шумо метавонед ба равзанаи ивази чипта равед ва ройгон ба қатораи навбатӣ иваз кунед."),
                  ("改签的话，原来的座位等级能保留吗？", "gǎiqiān de huà, yuánlái de zuòwèi děngjí néng bǎoliú ma?", "If I rebook, can I keep the same seat class?", "Если переоформить, класс места сохранится?", "Агар иваз кунам, дараҷаи ҷойи пештара нигоҳ дошта мешавад?"),
                  ["我们公司下个月要开发新产品。", "这个小区的环境非常安静。", "医生说我的感冒已经好了。"], "保留"),
                X(("一般可以，但是如果一等座卖完了，就只能退差价。", "yìbān kěyǐ, dànshì rúguǒ yī děng zuò mài wán le, jiù zhǐ néng tuì chājià.", "Usually yes, but if first class is sold out, we can only refund the difference.", "Обычно да, но если первый класс распродан, можем только вернуть разницу.", "Одатан мешавад, аммо агар ҷойҳои дараҷаи як фурӯхта шуда бошанд, танҳо фарқи нархро бармегардонем."),
                  ("明白了，退差价也可以接受。", "míngbai le, tuì chājià yě kěyǐ jiēshòu.", "Understood — a refund of the difference is acceptable too.", "Понятно, возврат разницы меня тоже устроит.", "Фаҳмидам, баргардонидани фарқи нарх ҳам қабул аст."),
                  ["这本小说的结局让人意想不到。", "我们得提前把会议室布置好。", "他把钱包忘在出租车上了。"], "接受"),
                X(("另外提醒您，候车室在二楼，检票会提前十五分钟停止。", "lìngwài tíxǐng nín, hòuchēshì zài èr lóu, jiǎnpiào huì tíqián shíwǔ fēnzhōng tíngzhǐ.", "A reminder: the waiting room is on the second floor, and ticket checks close fifteen minutes before departure.", "Напоминаю: зал ожидания на втором этаже, проверка билетов заканчивается за пятнадцать минут до отправления.", "Хотиррасон мекунам: толори интизорӣ дар ошёнаи дуюм аст ва санҷиши чипта понздаҳ дақиқа пеш қатъ мешавад."),
                  ("谢谢提醒，我现在就上去等着。", "xièxie tíxǐng, wǒ xiànzài jiù shàngqu děng zhe.", "Thanks for the reminder, I'll go up and wait now.", "Спасибо, что напомнили, сейчас же поднимусь и подожду.", "Ташаккур барои хотиррасонӣ, ман ҳозир боло рафта интизор мешавам."),
                  ["我对这次比赛的结果很失望。", "这种药每天吃三次。", "她的性格跟她姐姐完全不同。"], "提醒"),
                X(("祝您旅途愉快！如果还有问题，可以拨打服务热线。", "zhù nín lǚtú yúkuài! rúguǒ hái yǒu wèntí, kěyǐ bōdǎ fúwù rèxiàn.", "Have a pleasant trip! If you have more questions, call the service hotline.", "Приятной поездки! Если будут вопросы, звоните на горячую линию.", "Сафари хуш! Агар боз савол бошад, ба хати хизматрасонӣ занг занед."),
                  ("好的，您的服务真周到，辛苦了！", "hǎo de, nín de fúwù zhēn zhōudào, xīnkǔ le!", "OK — your service is really thoughtful, thank you for your hard work!", "Хорошо, вы очень внимательны, спасибо за ваш труд!", "Хуб, хизматрасонии шумо хеле боэҳтиёт аст, ташаккур барои заҳмататон!"),
                  ["我的论文还差一个结论。", "这里禁止停车。", "我们的预算已经超了。"], "愉快"),
            ],
        },
    },
    {
        "slug": "airport",
        "icon": "✈️",
        "title": T("Airport", "Аэропорт", "Фурудгоҳ", "机场"),
        "description": T(
            "Check in, handle your luggage and deal with flight changes.",
            "Пройдите регистрацию, сдайте багаж и справьтесь с изменениями рейса.",
            "Бақайдгирӣ гузаред, бағоҷ супоред ва бо тағйироти рейс кор кунед.",
            "办理值机、托运行李、应对航班变化。",
        ),
        "npc": {"zh": "值机员", "role": T("Check-in agent", "Сотрудник регистрации", "Корманди бақайдгирӣ", "值机员")},
        "tiers": {
            "beginner": [
                X(("你好！请给我你的护照。", "nǐ hǎo! qǐng gěi wǒ nǐ de hùzhào.", "Hello! Please give me your passport.", "Здравствуйте! Дайте, пожалуйста, ваш паспорт.", "Салом! Лутфан шиносномаатонро ба ман диҳед."),
                  ("好的，给你。", "hǎo de, gěi nǐ.", "OK, here you are.", "Хорошо, вот.", "Хуб, марҳамат."),
                  [("我不喝咖啡。", "wǒ bù hē kāfēi."), ("我家有三个人。", "wǒ jiā yǒu sān ge rén.")], "给"),
                X(("你去哪个城市？", "nǐ qù nǎge chéngshì?", "Which city are you going to?", "В какой город вы летите?", "Шумо ба кадом шаҳр меравед?"),
                  ("我去上海。", "wǒ qù Shànghǎi.", "I'm going to Shanghai.", "Я лечу в Шанхай.", "Ман ба Шанхай меравам."),
                  [("我在学校工作。", "wǒ zài xuéxiào gōngzuò."), ("这个很好吃。", "zhège hěn hǎochī.")], "城市"),
                X(("飞机十点起飞，你在八号门上飞机。", "fēijī shí diǎn qǐfēi, nǐ zài bā hào mén shàng fēijī.", "The plane takes off at ten; board at gate 8.", "Самолёт вылетает в десять, посадка у выхода 8.", "Ҳавопаймо соати даҳ парвоз мекунад, шумо аз дари 8 савор мешавед."),
                  ("八号门在哪儿？", "bā hào mén zài nǎr?", "Where is gate 8?", "Где выход номер 8?", "Дари рақами 8 дар куҷост?"),
                  [("我今年二十岁。", "wǒ jīnnián èrshí suì."), ("我们明天见。", "wǒmen míngtiān jiàn.")], "飞机"),
            ],
            "intermediate": [
                X(("您有需要托运的行李吗？", "nín yǒu xūyào tuōyùn de xíngli ma?", "Do you have any luggage to check in?", "У вас есть багаж для сдачи?", "Шумо бағоҷе доред, ки супоридан лозим аст?"),
                  ("有一个箱子，另外这个包我带上飞机。", "yǒu yí ge xiāngzi, lìngwài zhège bāo wǒ dài shàng fēijī.", "One suitcase; I'll take this bag on board.", "Один чемодан, а эту сумку возьму с собой в салон.", "Як ҷомадон, инчунин ин сумкаро бо худ ба ҳавопаймо мебарам."),
                  ["这条裤子有点儿长。", "我们班有二十个学生。"], "行李"),
                X(("您的箱子超重了两公斤。", "nín de xiāngzi chāozhòng le liǎng gōngjīn.", "Your suitcase is two kilos overweight.", "Ваш чемодан превышает норму на два килограмма.", "Ҷомадони шумо ду кило аз меъёр вазнинтар аст."),
                  ("那我拿出一些东西放进包里吧。", "nà wǒ ná chū yìxiē dōngxi fàng jìn bāo li ba.", "Then let me take some things out and put them in my bag.", "Тогда я выну кое-что и положу в сумку.", "Пас ман баъзе чизҳоро бароварда ба сумка мегузорам."),
                  ["我觉得今天比昨天暖和。", "他每天骑自行车上班。"], "公斤"),
                X(("好了。您想要靠窗还是靠过道的座位？", "hǎo le. nín xiǎng yào kào chuāng háishi kào guòdào de zuòwèi?", "Done. Would you like a window or an aisle seat?", "Готово. Вам место у окна или у прохода?", "Тайёр. Ҷойи назди тиреза мехоҳед ё назди гузаргоҳ?"),
                  ("靠窗的吧，我想看看风景。", "kào chuāng de ba, wǒ xiǎng kànkan fēngjǐng.", "Window, please — I'd like to see the view.", "У окна — хочу посмотреть на виды.", "Назди тиреза, мехоҳам манзараро тамошо кунам."),
                  ["我的电脑突然坏了。", "请你把门关上。"], "风景"),
                X(("这是您的登机牌，请在九点半以前到登机口。", "zhè shì nín de dēngjīpái, qǐng zài jiǔ diǎn bàn yǐqián dào dēngjīkǒu.", "Here's your boarding pass; please be at the gate before 9:30.", "Вот ваш посадочный талон. Будьте у выхода на посадку до 9:30.", "Ин талони саворшавии шумо, лутфан то соати нӯҳу ним ба дари саворшавӣ биёед."),
                  ("好的，安检往哪边走？", "hǎo de, ānjiǎn wǎng nǎ biān zǒu?", "OK — which way to security?", "Хорошо, а куда идти на досмотр?", "Хуб, ба назорати амниятӣ аз кадом тараф равам?"),
                  ["这家饭馆的菜特别便宜。", "我小时候很喜欢画画儿。"], "以前"),
            ],
            "advanced": [
                X(("很抱歉，由于航空管制，您的航班取消了。", "hěn bàoqiàn, yóuyú hángkōng guǎnzhì, nín de hángbān qǔxiāo le.", "We're very sorry — due to air traffic control, your flight has been cancelled.", "Приносим извинения: из-за ограничений авиадиспетчеров ваш рейс отменён.", "Хеле бубахшед, аз сабаби маҳдудиятҳои парвоз рейси шумо бекор шуд."),
                  ("那航空公司会安排我改乘下一班吗？", "nà hángkōng gōngsī huì ānpái wǒ gǎichéng xià yì bān ma?", "Will the airline put me on the next flight?", "Авиакомпания пересадит меня на следующий рейс?", "Ширкати ҳавопаймоӣ маро ба рейси навбатӣ мегузаронад?"),
                  ["这篇文章的观点很有说服力。", "我们小区明天停水。", "他把这个月的工资都存起来了。"], "取消"),
                X(("最早的一班是明天早上七点，我们会为您提供酒店住宿。", "zuì zǎo de yì bān shì míngtiān zǎoshang qī diǎn, wǒmen huì wèi nín tígōng jiǔdiàn zhùsù.", "The earliest is tomorrow at 7 a.m.; we'll provide you with a hotel.", "Ближайший рейс завтра в 7 утра, мы предоставим вам гостиницу.", "Аввалин рейс пагоҳ соати ҳафти субҳ аст, мо ба шумо меҳмонхона медиҳем."),
                  ("住宿包括晚餐和接送吗？", "zhùsù bāokuò wǎncān hé jiēsòng ma?", "Does the stay include dinner and transfers?", "Проживание включает ужин и трансфер?", "Ҷойгиршавӣ хӯроки шом ва интиқолро дар бар мегирад?"),
                  ["我建议你多参加体育锻炼。", "这台洗衣机的声音太大了。", "他们俩是在大学认识的。"], "提供"),
                X(("包括，班车每半小时一趟，在三号出口等候。", "bāokuò, bānchē měi bàn xiǎoshí yí tàng, zài sān hào chūkǒu děnghòu.", "Yes — a shuttle runs every half hour; wait at exit 3.", "Включает: шаттл ходит каждые полчаса, ждите у выхода 3.", "Дар бар мегирад: автобуси махсус ҳар ним соат меравад, дар баромадгоҳи 3 интизор шавед."),
                  ("我托运的行李需要先取出来吗？", "wǒ tuōyùn de xíngli xūyào xiān qǔ chūlai ma?", "Do I need to collect my checked luggage first?", "Мне нужно сначала забрать сданный багаж?", "Бағоҷи супоридаамро аввал гирифтан лозим аст?"),
                  ["这次失败给了我很大的教训。", "这个城市的交通越来越方便了。", "我们得节约用电。"], "需要"),
                X(("不用，行李会直接转到明天的航班上。", "búyòng, xíngli huì zhíjiē zhuǎn dào míngtiān de hángbān shang.", "No, your luggage will be transferred directly to tomorrow's flight.", "Нет, багаж перенесут прямо на завтрашний рейс.", "Не, бағоҷ мустақиман ба рейси пагоҳ интиқол дода мешавад."),
                  ("那我的随身物品够用了，太感谢了。", "nà wǒ de suíshēn wùpǐn gòu yòng le, tài gǎnxiè le.", "Then what I have with me is enough — thank you so much.", "Тогда мне хватит вещей, что при мне. Большое спасибо.", "Пас чизҳои ҳамроҳам кифоя мекунанд, хеле ташаккур."),
                  ["他的发音比以前标准多了。", "这个小镇以出产茶叶闻名。", "我们正在讨论明年的计划。"], "直接"),
                X(("不客气。给您带来不便，我们深表歉意。", "bú kèqi. gěi nín dàilái búbiàn, wǒmen shēn biǎo qiànyì.", "You're welcome. We sincerely apologize for the inconvenience.", "Не за что. Приносим глубокие извинения за неудобства.", "Намеарзад. Барои нороҳатӣ аз шумо самимона узр мепурсем."),
                  ("理解，天气的事谁也控制不了。", "lǐjiě, tiānqì de shì shéi yě kòngzhì bu liǎo.", "I understand — nobody can control the weather.", "Понимаю, погоду никто не контролирует.", "Мефаҳмам, обу ҳаворо ҳеҷ кас идора карда наметавонад."),
                  ["这件事你得跟经理商量。", "他的作品获得了一等奖。", "我习惯晚上散步。"], "理解"),
            ],
        },
    },
    {
        "slug": "hotel",
        "icon": "🏨",
        "title": T("Hotel", "Гостиница", "Меҳмонхона", "酒店"),
        "description": T(
            "Check in, ask about services and solve a problem with your room.",
            "Заселитесь, спросите об услугах и решите проблему с номером.",
            "Ҷойгир шавед, дар бораи хизматҳо пурсед ва мушкили ҳуҷраро ҳал кунед.",
            "办理入住、询问服务、解决房间问题。",
        ),
        "npc": {"zh": "前台", "role": T("Receptionist", "Администратор", "Корманди қабулгоҳ", "前台")},
        "tiers": {
            "beginner": [
                X(("你好！你叫什么名字？", "nǐ hǎo! nǐ jiào shénme míngzi?", "Hello! What's your name?", "Здравствуйте! Как вас зовут?", "Салом! Номатон чист?"),
                  ("我叫王明。", "wǒ jiào Wáng Míng.", "My name is Wang Ming.", "Меня зовут Ван Мин.", "Номи ман Ван Мин аст."),
                  [("我去商店。", "wǒ qù shāngdiàn."), ("现在十点。", "xiànzài shí diǎn.")], "名字"),
                X(("你住几天？", "nǐ zhù jǐ tiān?", "How many days are you staying?", "Сколько дней вы пробудете?", "Шумо чанд рӯз мемонед?"),
                  ("我住三天。", "wǒ zhù sān tiān.", "I'm staying three days.", "Я пробуду три дня.", "Ман се рӯз мемонам."),
                  [("我爱吃水果。", "wǒ ài chī shuǐguǒ."), ("他是我朋友。", "tā shì wǒ péngyou.")], "住"),
                X(("你的房间是三零八。", "nǐ de fángjiān shì sān líng bā.", "Your room is 308.", "Ваш номер — 308.", "Ҳуҷраи шумо 308 аст."),
                  ("谢谢！房间在几楼？", "xièxie! fángjiān zài jǐ lóu?", "Thanks! Which floor is the room on?", "Спасибо! На каком этаже номер?", "Ташаккур! Ҳуҷра дар ошёнаи чандум аст?"),
                  [("我会说汉语。", "wǒ huì shuō Hànyǔ."), ("我想买书。", "wǒ xiǎng mǎi shū.")], "房间"),
            ],
            "intermediate": [
                X(("晚上好，欢迎入住！请问您预订了吗？", "wǎnshang hǎo, huānyíng rùzhù! qǐngwèn nín yùdìng le ma?", "Good evening, welcome! Do you have a booking?", "Добрый вечер, добро пожаловать! Вы бронировали?", "Шоми хуш, хуш омадед! Шумо брон кардаед?"),
                  ("预订了，是用李华的名字订的。", "yùdìng le, shì yòng Lǐ Huá de míngzi dìng de.", "Yes, it's booked under the name Li Hua.", "Да, бронь на имя Ли Хуа.", "Брон кардаам, ба номи Ли Хуа."),
                  ["这个星期我特别忙。", "我的手机在桌子上。"], "预订"),
                X(("找到了，一间大床房，住两个晚上，对吗？", "zhǎo dào le, yì jiān dàchuáng fáng, zhù liǎng ge wǎnshang, duì ma?", "Found it: one double room for two nights, right?", "Нашла: один номер с двуспальной кроватью на две ночи, верно?", "Ёфтам: як ҳуҷра бо кати калон барои ду шаб, дуруст?"),
                  ("对，早饭包括在里面吗？", "duì, zǎofàn bāokuò zài lǐmiàn ma?", "Yes. Is breakfast included?", "Да. Завтрак включён?", "Бале. Наҳорӣ дохил аст?"),
                  ["我昨天去公园跑步了。", "他们在准备考试。"], "包括"),
                X(("包括，早餐在一楼餐厅，从七点到十点。", "bāokuò, zǎocān zài yī lóu cāntīng, cóng qī diǎn dào shí diǎn.", "Yes; breakfast is in the first-floor restaurant from 7 to 10.", "Да, завтрак в ресторане на первом этаже с 7 до 10.", "Бале, наҳорӣ дар тарабхонаи ошёнаи якум аз соати 7 то 10."),
                  ("太好了。房间里能上网吗？", "tài hǎo le. fángjiān li néng shàng wǎng ma?", "Great. Is there internet in the room?", "Отлично. В номере есть интернет?", "Хеле хуб. Дар ҳуҷра интернет ҳаст?"),
                  ["我想学习做中国菜。", "这双鞋有点儿小。"], "上网"),
                X(("可以，无线网的密码写在房卡上。", "kěyǐ, wúxiàn wǎng de mìmǎ xiě zài fángkǎ shang.", "Yes, the Wi-Fi password is written on the key card.", "Да, пароль от Wi-Fi написан на карте-ключе.", "Бале, пароли Wi-Fi дар корти калид навишта шудааст."),
                  ("明白了。明天早上能叫醒我吗？", "míngbai le. míngtiān zǎoshang néng jiào xǐng wǒ ma?", "Got it. Could you give me a wake-up call tomorrow morning?", "Понятно. Можете разбудить меня завтра утром?", "Фаҳмидам. Пагоҳ саҳар маро бедор карда метавонед?"),
                  ["我弟弟比我小三岁。", "这个菜太咸了。"], "密码"),
            ],
            "advanced": [
                X(("您好，非常抱歉，您预订的海景房空调出了故障，暂时不能入住。", "nín hǎo, fēicháng bàoqiàn, nín yùdìng de hǎijǐng fáng kōngtiáo chū le gùzhàng, zànshí bù néng rùzhù.", "Hello, we're very sorry: the air conditioning in your sea-view room has broken down, so it can't be used for now.", "Здравствуйте, приносим извинения: в забронированном номере с видом на море сломался кондиционер, заселиться пока нельзя.", "Салом, хеле бубахшед: кондитсионери ҳуҷраи манзараи баҳрии бронкардаатон вайрон шуд, ҳоло ҷойгир шудан мумкин нест."),
                  ("那你们打算怎么解决这个问题？", "nà nǐmen dǎsuan zěnme jiějué zhège wèntí?", "So how do you plan to solve this problem?", "И как вы собираетесь решить эту проблему?", "Пас шумо ин мушкилро чӣ тавр ҳал карданӣ ҳастед?"),
                  ["这个专业的就业前景很好。", "我从来没见过这么大的雪。", "请把文件发到我的邮箱。"], "解决"),
                X(("我们可以免费为您升级到套房，或者退还今晚的房费。", "wǒmen kěyǐ miǎnfèi wèi nín shēngjí dào tàofáng, huòzhě tuìhuán jīnwǎn de fángfèi.", "We can upgrade you to a suite for free, or refund tonight's room rate.", "Мы можем бесплатно перевести вас в люкс или вернуть оплату за эту ночь.", "Мо метавонем ройгон шуморо ба люкс гузаронем ё пули имшабро баргардонем."),
                  ("升级到套房吧，不过我希望明天能换回海景房。", "shēngjí dào tàofáng ba, búguò wǒ xīwàng míngtiān néng huàn huí hǎijǐng fáng.", "The suite, please — but I hope to move back to a sea-view room tomorrow.", "Давайте люкс, но я надеюсь завтра вернуться в номер с видом на море.", "Ба люкс гузаронед, аммо умедворам пагоҳ ба ҳуҷраи манзараи баҳрӣ баргардам."),
                  ["他的演讲引起了大家的共鸣。", "我们公司实行弹性工作制。", "这条河比那条河长得多。"], "希望"),
                X(("没问题，维修人员保证明天中午以前修好。", "méi wèntí, wéixiū rényuán bǎozhèng míngtiān zhōngwǔ yǐqián xiū hǎo.", "No problem — maintenance promise to fix it before noon tomorrow.", "Без проблем, ремонтники обещают починить до завтрашнего полудня.", "Мушкиле нест, устоҳо кафолат медиҳанд, ки то нисфирӯзии пагоҳ таъмир мекунанд."),
                  ("那退房时间能不能顺延一个小时？", "nà tuìfáng shíjiān néng bu néng shùnyán yí ge xiǎoshí?", "Then could checkout be pushed back an hour?", "Тогда можно сдвинуть время выезда на час?", "Пас вақти тарки ҳуҷраро як соат дароз кардан мумкин аст?"),
                  ["这种植物需要充足的阳光。", "我把这句话翻译成了英语。", "比赛因为下雨推迟了。"], "保证"),
                X(("当然可以，延迟到下午一点退房，不额外收费。", "dāngrán kěyǐ, yánchí dào xiàwǔ yī diǎn tuìfáng, bù éwài shōufèi.", "Of course — checkout extended to 1 p.m. at no extra charge.", "Конечно, выезд до часу дня без доплаты.", "Албатта, тарки ҳуҷра то соати якӣ рӯз, бе пардохти иловагӣ."),
                  ("你们处理得很专业，我很满意。", "nǐmen chǔlǐ de hěn zhuānyè, wǒ hěn mǎnyì.", "You handled it very professionally — I'm very satisfied.", "Вы решили вопрос очень профессионально, меня всё устраивает.", "Шумо хеле касбӣ ҳал кардед, ман хеле розӣ ҳастам."),
                  ["这个词的用法比较复杂。", "他终于决定辞职了。", "博物馆周一闭馆。"], "满意"),
                X(("这是您的房卡，行李员会帮您把行李送上去。", "zhè shì nín de fángkǎ, xínglǐyuán huì bāng nín bǎ xíngli sòng shàngqu.", "Here's your key card; the porter will take your luggage up.", "Вот ваша карта-ключ, носильщик поднимет ваш багаж.", "Ин корти калиди шумо, ҳаммол бағоҷатонро боло мебарад."),
                  ("辛苦了。附近有没有值得推荐的餐厅？", "xīnkǔ le. fùjìn yǒu méiyǒu zhíde tuījiàn de cāntīng?", "Thank you. Are there any restaurants nearby worth recommending?", "Спасибо. Есть поблизости ресторан, который стоит посоветовать?", "Ташаккур. Дар наздикӣ тарабхонае ҳаст, ки тавсия додан арзад?"),
                  ["我的签证下个月到期。", "这次考试的范围太大了。", "他们正在装修新房子。"], "推荐"),
            ],
        },
    },
    {
        "slug": "shopping",
        "icon": "🛍️",
        "title": T("Shopping", "Покупки", "Харид", "购物"),
        "description": T(
            "Choose, try on, bargain and pay.",
            "Выбирайте, примеряйте, торгуйтесь и платите.",
            "Интихоб кунед, пӯшида бинед, савдо кунед ва пардохт кунед.",
            "挑选、试穿、讲价、付款。",
        ),
        "npc": {"zh": "店员", "role": T("Shop assistant", "Продавец", "Фурӯшанда", "店员")},
        "tiers": {
            "beginner": [
                X(("你好！你想买什么？", "nǐ hǎo! nǐ xiǎng mǎi shénme?", "Hello! What would you like to buy?", "Здравствуйте! Что вы хотите купить?", "Салом! Шумо чӣ харидан мехоҳед?"),
                  ("我想买一件衣服。", "wǒ xiǎng mǎi yí jiàn yīfu.", "I'd like to buy some clothes.", "Я хочу купить одежду.", "Ман як либос харидан мехоҳам."),
                  [("我们坐出租车吧。", "wǒmen zuò chūzūchē ba."), ("我昨天很累。", "wǒ zuótiān hěn lèi.")], "衣服"),
                X(("这件红色的怎么样？", "zhè jiàn hóngsè de zěnmeyàng?", "How about this red one?", "Как вам вот эта, красная?", "Ин сурхаш чӣ хел аст?"),
                  ("很漂亮！多少钱？", "hěn piàoliang! duōshao qián?", "Very pretty! How much is it?", "Очень красивая! Сколько стоит?", "Хеле зебо! Нархаш чанд?"),
                  [("我不认识他。", "wǒ bú rènshi tā."), ("我在看电视。", "wǒ zài kàn diànshì.")], "漂亮"),
                X(("一百块。", "yìbǎi kuài.", "One hundred yuan.", "Сто юаней.", "Сад юан."),
                  ("太贵了！便宜一点儿吧。", "tài guì le! piányi yìdiǎnr ba.", "Too expensive! A bit cheaper, please.", "Слишком дорого! Подешевле, пожалуйста.", "Хеле қимат! Каме арзонтар кунед."),
                  [("我有一只猫。", "wǒ yǒu yì zhī māo."), ("今天是我的生日。", "jīntiān shì wǒ de shēngrì.")], "便宜"),
            ],
            "intermediate": [
                X(("这件外套是新款，您可以试一下。", "zhè jiàn wàitào shì xīn kuǎn, nín kěyǐ shì yíxià.", "This jacket is a new style — you can try it on.", "Это новая модель куртки, можете примерить.", "Ин куртаи моди нав аст, метавонед пӯшида бинед."),
                  ("有没有大一号的？这件有点儿紧。", "yǒu méiyǒu dà yí hào de? zhè jiàn yǒudiǎnr jǐn.", "Do you have one size up? This one's a bit tight.", "Есть на размер больше? Эта немного тесная.", "Як андоза калонтар ҳаст? Ин каме танг аст."),
                  ["我们下午去图书馆借书。", "他每天晚上给妈妈打电话。"], "试"),
                X(("有，这是L号的，颜色也比较多。", "yǒu, zhè shì L hào de, yánsè yě bǐjiào duō.", "Yes, here's size L, and there are more colours too.", "Есть, вот размер L, и цветов больше.", "Ҳаст, ин андозаи L, рангҳояш ҳам бисёртар."),
                  ("我比较喜欢黑色的，看起来更正式。", "wǒ bǐjiào xǐhuan hēisè de, kàn qǐlai gèng zhèngshì.", "I prefer the black one — it looks more formal.", "Мне больше нравится чёрная, она выглядит строже.", "Ба ман сиёҳаш бештар маъқул аст, расмитар менамояд."),
                  ["我们明天早上八点出发。", "这道题我还不会做。"], "颜色"),
                X(("这件现在打八折，原价五百，打完折四百。", "zhè jiàn xiànzài dǎ bā zhé, yuánjià wǔbǎi, dǎ wán zhé sìbǎi.", "It's 20% off now: originally 500, 400 after the discount.", "Сейчас на неё скидка 20%: было 500, со скидкой 400.", "Ҳоло 20% тахфиф дорад: нархи аслӣ 500, бо тахфиф 400."),
                  ("还能再便宜一点儿吗？我买两件。", "hái néng zài piányi yìdiǎnr ma? wǒ mǎi liǎng jiàn.", "Can it be a bit cheaper? I'll buy two.", "А ещё дешевле можно? Я возьму две.", "Боз арзонтар мешавад? Ман дуто мехарам."),
                  ["我觉得这个电影没意思。", "他的房间又干净又整齐。"], "便宜"),
                X(("买两件的话，可以送您一条围巾。", "mǎi liǎng jiàn de huà, kěyǐ sòng nín yì tiáo wéijīn.", "If you buy two, we'll give you a scarf for free.", "Если купите две, подарим вам шарф.", "Агар ду дона харед, ба шумо як гарданпеч тӯҳфа медиҳем."),
                  ("好，那就这样吧。可以刷卡吗？", "hǎo, nà jiù zhèyàng ba. kěyǐ shuā kǎ ma?", "OK, deal. Can I pay by card?", "Хорошо, договорились. Можно картой?", "Хуб, ҳамин тавр бошад. Бо корт мешавад?"),
                  ["我的老家在南方。", "外面正在下大雪。"], "送"),
            ],
            "advanced": [
                X(("这款手机是今年的新品，拍照功能特别强。", "zhè kuǎn shǒujī shì jīnnián de xīnpǐn, pāizhào gōngnéng tèbié qiáng.", "This phone is this year's new model; its camera is especially strong.", "Это новинка этого года, у неё особенно хорошая камера.", "Ин телефон маҳсулоти нави имсола аст, камераи он хеле қавӣ аст."),
                  ("它的电池能用多久？我经常出差。", "tā de diànchí néng yòng duō jiǔ? wǒ jīngcháng chūchāi.", "How long does the battery last? I travel for work a lot.", "На сколько хватает батареи? Я часто езжу в командировки.", "Батареяаш чанд вақт кор мекунад? Ман зуд-зуд ба сафари корӣ меравам."),
                  ["这次活动的报名已经截止了。", "我们应该保护野生动物。", "他在国外留学了五年。"], "功能"),
                X(("正常使用的话，充满电能用一整天。", "zhèngcháng shǐyòng de huà, chōng mǎn diàn néng yòng yì zhěng tiān.", "With normal use, a full charge lasts a whole day.", "При обычном использовании полного заряда хватает на целый день.", "Дар истифодаи муқаррарӣ як заряди пурра як рӯзи пурра кифоя мекунад."),
                  ("跟上一代相比，价格贵了多少？", "gēn shàng yí dài xiāngbǐ, jiàgé guì le duōshao?", "Compared with the previous generation, how much more does it cost?", "По сравнению с предыдущей моделью — насколько дороже?", "Дар муқоиса бо насли пешина, нархаш чӣ қадар қиматтар аст?"),
                  ["这部小说被翻译成了多种语言。", "请勿在车厢内吸烟。", "他的工作效率提高了不少。"], "价格"),
                X(("贵了五百，不过现在以旧换新可以抵八百块。", "guì le wǔbǎi, búguò xiànzài yǐ jiù huàn xīn kěyǐ dǐ bābǎi kuài.", "500 more, but right now trading in your old phone takes 800 off.", "На 500 дороже, но сейчас при сдаче старого телефона скидка 800.", "Панҷсад қиматтар, вале ҳоло бо супоридани телефони кӯҳна ҳаштсад кам мешавад."),
                  ("这么算的话还挺划算的，我的旧手机屏幕有点儿裂了，也能换吗？", "zhème suàn de huà hái tǐng huásuàn de, wǒ de jiù shǒujī píngmù yǒudiǎnr liè le, yě néng huàn ma?", "That's quite a good deal then — my old phone's screen is a little cracked; can I still trade it in?", "Тогда это выгодно. У моего старого телефона немного треснул экран — его тоже примут?", "Пас хеле фоиданок аст. Экрани телефони кӯҳнаам каме кафидааст, онро ҳам иваз мекунанд?"),
                  ["这个地区的气候四季分明。", "他对自己的要求非常严格。", "会议记录已经发给大家了。"], "划算"),
                X(("可以，不过需要检测一下，屏幕有问题会少抵一些。", "kěyǐ, búguò xūyào jiǎncè yíxià, píngmù yǒu wèntí huì shǎo dǐ yìxiē.", "Yes, but it needs checking; a damaged screen means a smaller discount.", "Можно, но его нужно проверить: с повреждённым экраном скидка будет меньше.", "Мешавад, вале санҷидан лозим аст; агар экран мушкил дошта бошад, тахфиф камтар мешавад."),
                  ("理解，那麻烦你帮我检测一下吧。", "lǐjiě, nà máfan nǐ bāng wǒ jiǎncè yíxià ba.", "Understood — please check it for me then.", "Понимаю, тогда проверьте его, пожалуйста.", "Фаҳмидам, пас лутфан онро барои ман санҷед."),
                  ["他从来不在背后说别人的坏话。", "春节期间车票很难买。", "这家公司去年的利润增长了一倍。"], "麻烦"),
                X(("检测好了，可以抵六百。另外这款手机保修两年。", "jiǎncè hǎo le, kěyǐ dǐ liùbǎi. lìngwài zhè kuǎn shǒujī bǎoxiū liǎng nián.", "Checked: it's worth 600 off. Also, this phone has a two-year warranty.", "Проверили: скидка 600. Кроме того, гарантия на этот телефон — два года.", "Санҷида шуд: шашсад кам мешавад. Инчунин ин телефон ду сол кафолат дорад."),
                  ("行，就买这款了，请帮我把数据转到新手机上。", "xíng, jiù mǎi zhè kuǎn le, qǐng bāng wǒ bǎ shùjù zhuǎn dào xīn shǒujī shang.", "OK, I'll take this one — please help me move my data to the new phone.", "Хорошо, беру эту модель. Помогите перенести данные на новый телефон.", "Хуб, ҳаминро мехарам, лутфан маълумотамро ба телефони нав гузаронед."),
                  ["他把这个秘密告诉了所有人。", "我们的教室在三楼。", "这条路晚上不太安全。"], "另外"),
            ],
        },
    },
    {
        "slug": "university",
        "icon": "🎓",
        "title": T("University", "Университет", "Донишгоҳ", "大学"),
        "description": T(
            "Talk with a classmate about courses, studying and research.",
            "Поговорите с однокурсником о курсах, учёбе и исследованиях.",
            "Бо ҳамкурс дар бораи дарсҳо, таҳсил ва таҳқиқот сӯҳбат кунед.",
            "和同学聊课程、学习和研究。",
        ),
        "npc": {"zh": "同学", "role": T("Classmate", "Однокурсник", "Ҳамкурс", "同学")},
        "tiers": {
            "beginner": [
                X(("你好！你是新同学吗？", "nǐ hǎo! nǐ shì xīn tóngxué ma?", "Hi! Are you a new student?", "Привет! Ты новый студент?", "Салом! Ту донишҷӯи нав ҳастӣ?"),
                  ("是，我是新同学。", "shì, wǒ shì xīn tóngxué.", "Yes, I'm a new student.", "Да, я новый студент.", "Бале, ман донишҷӯи нав ҳастам."),
                  [("我喜欢喝牛奶。", "wǒ xǐhuan hē niúnǎi."), ("他们都很好。", "tāmen dōu hěn hǎo.")], "同学"),
                X(("你学习什么？", "nǐ xuéxí shénme?", "What do you study?", "Что ты изучаешь?", "Ту чӣ мехонӣ?"),
                  ("我学习汉语。", "wǒ xuéxí Hànyǔ.", "I study Chinese.", "Я изучаю китайский.", "Ман забони чиниро меомӯзам."),
                  [("我坐飞机去。", "wǒ zuò fēijī qù."), ("这是我的杯子。", "zhè shì wǒ de bēizi.")], "学习"),
                X(("我们一起去吃饭吧！", "wǒmen yìqǐ qù chī fàn ba!", "Let's go and eat together!", "Пойдём поедим вместе!", "Биё якҷоя хӯрок хӯрем!"),
                  ("好啊，我们去哪儿吃？", "hǎo a, wǒmen qù nǎr chī?", "Sure — where shall we eat?", "Давай! Куда пойдём?", "Хуб, куҷо рафта мехӯрем?"),
                  [("我的老师很高。", "wǒ de lǎoshī hěn gāo."), ("他明天不来。", "tā míngtiān bù lái.")], "一起"),
            ],
            "intermediate": [
                X(("这学期的课你选好了吗？", "zhè xuéqī de kè nǐ xuǎn hǎo le ma?", "Have you chosen your courses for this semester?", "Курсы на этот семестр уже выбраны?", "Дарсҳои ин нимсоларо интихоб кардӣ?"),
                  ("还没有，我在考虑选历史课还是经济课。", "hái méiyǒu, wǒ zài kǎolǜ xuǎn lìshǐ kè háishi jīngjì kè.", "Not yet — I'm deciding between history and economics.", "Ещё нет, выбираю между историей и экономикой.", "Ҳанӯз не, фикр мекунам дарси таърихро интихоб кунам ё иқтисодро."),
                  ["我把雨伞忘在地铁上了。", "这个菜是我妈妈做的。"], "考虑"),
                X(("经济课的老师讲得很清楚，作业也不多。", "jīngjì kè de lǎoshī jiǎng de hěn qīngchu, zuòyè yě bù duō.", "The economics teacher explains clearly, and there isn't much homework.", "Преподаватель экономики объясняет понятно, и домашних заданий немного.", "Муаллими иқтисод равшан шарҳ медиҳад, вазифаи хонагӣ ҳам кам аст."),
                  ("真的吗？那我就选经济课吧。", "zhēn de ma? nà wǒ jiù xuǎn jīngjì kè ba.", "Really? Then I'll go with economics.", "Правда? Тогда выберу экономику.", "Ростӣ? Пас иқтисодро интихоб мекунам."),
                  ["我们家附近新开了一家超市。", "他的个子比我高。"], "作业"),
                X(("下周有个小考试，我们一起去图书馆复习吧。", "xià zhōu yǒu ge xiǎo kǎoshì, wǒmen yìqǐ qù túshūguǎn fùxí ba.", "There's a quiz next week — let's revise at the library together.", "На следующей неделе небольшая контрольная — давай вместе позанимаемся в библиотеке.", "Ҳафтаи оянда як имтиҳони хурд ҳаст, биё якҷоя дар китобхона такрор кунем."),
                  ("好主意！你周三下午有空吗？", "hǎo zhǔyi! nǐ zhōusān xiàwǔ yǒu kòng ma?", "Good idea! Are you free on Wednesday afternoon?", "Хорошая идея! У тебя есть время в среду днём?", "Фикри хуб! Рӯзи чоршанбе баъд аз зӯҳр вақт дорӣ?"),
                  ["这件衣服洗了以后变小了。", "我哥哥在银行工作。"], "复习"),
                X(("有空，我们两点在图书馆门口见。", "yǒu kòng, wǒmen liǎng diǎn zài túshūguǎn ménkǒu jiàn.", "Yes — let's meet at the library entrance at two.", "Есть, встретимся у входа в библиотеку в два.", "Вақт дорам, соати ду назди дари китобхона вомехӯрем."),
                  ("没问题，我会带上我的笔记。", "méi wèntí, wǒ huì dài shàng wǒ de bǐjì.", "No problem, I'll bring my notes.", "Договорились, я возьму свои конспекты.", "Мушкиле нест, ман дафтари қайдҳоямро меорам."),
                  ["我第一次来中国是在二〇一九年。", "他们正在打篮球。"], "笔记"),
            ],
            "advanced": [
                X(("导师说我们这学期的论文题目要和社会热点相关。", "dǎoshī shuō wǒmen zhè xuéqī de lùnwén tímù yào hé shèhuì rèdiǎn xiāngguān.", "Our supervisor says this semester's paper topic must relate to a current social issue.", "Научный руководитель сказал, что тема работы в этом семестре должна быть связана с актуальной общественной темой.", "Роҳбари илмӣ гуфт, ки мавзӯи рисолаи ин нимсола бояд ба масъалаҳои мубрами ҷамъиятӣ марбут бошад."),
                  ("我打算研究人工智能对就业的影响，你觉得怎么样？", "wǒ dǎsuan yánjiū réngōng zhìnéng duì jiùyè de yǐngxiǎng, nǐ juéde zěnmeyàng?", "I plan to study the impact of AI on employment — what do you think?", "Я собираюсь исследовать влияние ИИ на занятость. Как тебе?", "Ман нақша дорам таъсири зеҳни сунъиро ба шуғл таҳқиқ кунам, ту чӣ фикр дорӣ?"),
                  ["我的行李箱在海关被检查了。", "这家餐厅需要提前排队。", "他每天坚持跑五公里。"], "影响"),
                X(("题目不错，但范围有点儿大，最好缩小到某个行业。", "tímù búcuò, dàn fànwéi yǒudiǎnr dà, zuìhǎo suōxiǎo dào mǒu ge hángyè.", "Good topic, but the scope is a bit broad — better to narrow it to one industry.", "Тема хорошая, но широковата — лучше сузить её до одной отрасли.", "Мавзӯъ хуб аст, вале доирааш каме васеъ аст, беҳтар аст онро то як соҳа танг кунӣ."),
                  ("有道理，那我就聚焦在客服行业吧。", "yǒu dàolǐ, nà wǒ jiù jùjiāo zài kèfú hángyè ba.", "Makes sense — I'll focus on the customer-service industry.", "Разумно, тогда сосредоточусь на сфере обслуживания клиентов.", "Дуруст, пас ман ба соҳаи хизматрасонии муштариён тамаркуз мекунам."),
                  ["这座桥是一百年前建的。", "请大家把手机调成静音。", "我对海鲜过敏。"], "道理"),
                X(("你需要做问卷调查吗？我可以帮你发给认识的人。", "nǐ xūyào zuò wènjuàn diàochá ma? wǒ kěyǐ bāng nǐ fā gěi rènshi de rén.", "Do you need to run a survey? I can send it to people I know.", "Тебе нужен опрос? Могу разослать знакомым.", "Ба ту пурсиш лозим аст? Ман метавонам онро ба шиносҳоям фиристам."),
                  ("太感谢了，样本越多，结论就越可靠。", "tài gǎnxiè le, yàngběn yuè duō, jiélùn jiù yuè kěkào.", "Thanks so much — the bigger the sample, the more reliable the conclusion.", "Огромное спасибо: чем больше выборка, тем надёжнее вывод.", "Хеле ташаккур, ҳар қадар намуна зиёд бошад, хулоса ҳамон қадар боэътимодтар мешавад."),
                  ["这个公园周末人特别多。", "我昨晚做了一个奇怪的梦。", "他的护照快过期了。"], "调查"),
                X(("不过要注意保护受访者的隐私。", "búguò yào zhùyì bǎohù shòufǎngzhě de yǐnsī.", "But be careful to protect the respondents' privacy.", "Только не забудь о конфиденциальности опрошенных.", "Аммо ба ҳифзи махфияти пурсидашудагон диққат деҳ."),
                  ("放心，问卷是匿名的，不会收集个人信息。", "fàngxīn, wènjuàn shì nìmíng de, bú huì shōují gèrén xìnxī.", "Don't worry — the survey is anonymous and won't collect personal information.", "Не волнуйся, опрос анонимный, личные данные не собираются.", "Хотирҷамъ бош, пурсиш беном аст, маълумоти шахсӣ ҷамъ намешавад."),
                  ["这里的冬天比我想象的冷。", "他把车停在了门口。", "我们公司正在招聘工程师。"], "放心"),
                X(("那就好。写完初稿以后，我可以帮你看看逻辑。", "nà jiù hǎo. xiě wán chūgǎo yǐhòu, wǒ kěyǐ bāng nǐ kànkan luójí.", "Good. Once you finish the first draft, I can check the logic for you.", "Тогда хорошо. Когда допишешь черновик, могу проверить логику.", "Хуб. Пас аз навиштани нусхаи аввал, ман метавонам мантиқашро барои ту бинам."),
                  ("那就拜托你了，下次我请你喝咖啡。", "nà jiù bàituō nǐ le, xià cì wǒ qǐng nǐ hē kāfēi.", "I'm counting on you then — next time the coffee's on me.", "Тогда рассчитываю на тебя, в следующий раз угощаю кофе.", "Пас ба ту умед мебандам, дафъаи дигар туро ба қаҳва меҳмон мекунам."),
                  ["这个城市的房价越来越高。", "他上个月刚换了工作。", "运动会因为天气原因取消了。"], "咖啡"),
            ],
        },
    },
    {
        "slug": "hospital",
        "icon": "🏥",
        "title": T("Hospital", "Больница", "Беморхона", "医院"),
        "description": T(
            "Describe your symptoms and understand the doctor's advice.",
            "Опишите симптомы и поймите советы врача.",
            "Аломатҳоро тасвир кунед ва маслиҳати духтурро фаҳмед.",
            "描述症状，听懂医生的建议。",
        ),
        "npc": {"zh": "医生", "role": T("Doctor", "Врач", "Духтур", "医生")},
        "tiers": {
            "beginner": [
                X(("你好，你哪儿不舒服？", "nǐ hǎo, nǐ nǎr bù shūfu?", "Hello, what's bothering you?", "Здравствуйте, что вас беспокоит?", "Салом, шуморо чӣ ташвиш медиҳад?"),
                  ("我头疼。", "wǒ tóu téng.", "I have a headache.", "У меня болит голова.", "Сарам дард мекунад."),
                  [("我是中国人。", "wǒ shì Zhōngguó rén."), ("我想去看电影。", "wǒ xiǎng qù kàn diànyǐng.")], "舒服"),
                X(("你发烧吗？", "nǐ fāshāo ma?", "Do you have a fever?", "У вас температура?", "Шумо таб доред?"),
                  ("有一点儿，三十八度。", "yǒu yìdiǎnr, sānshíbā dù.", "A little — 38 degrees.", "Немного, тридцать восемь.", "Каме, сию ҳашт дараҷа."),
                  [("我家在北京。", "wǒ jiā zài Běijīng."), ("他喜欢唱歌。", "tā xǐhuan chàng gē.")], "一点儿"),
                X(("你要多喝水，多休息。", "nǐ yào duō hē shuǐ, duō xiūxi.", "Drink plenty of water and get lots of rest.", "Пейте больше воды и больше отдыхайте.", "Бисёр об нӯшед ва бисёр истироҳат кунед."),
                  ("好的，谢谢医生！", "hǎo de, xièxie yīshēng!", "OK, thank you, doctor!", "Хорошо, спасибо, доктор!", "Хуб, ташаккур, духтур!"),
                  [("我不会开车。", "wǒ bú huì kāi chē."), ("现在下雨了。", "xiànzài xià yǔ le.")], "休息"),
            ],
            "intermediate": [
                X(("你这样咳嗽多长时间了？", "nǐ zhèyàng késou duō cháng shíjiān le?", "How long have you been coughing like this?", "Как давно вы так кашляете?", "Чанд вақт боз ҳамин тавр сулфа мекунед?"),
                  ("差不多一个星期了，晚上更厉害。", "chàbuduō yí ge xīngqī le, wǎnshang gèng lìhai.", "About a week — it's worse at night.", "Почти неделю, ночью сильнее.", "Тақрибан як ҳафта, шабона сахттар мешавад."),
                  ["我们坐公共汽车去吧。", "这个字我不认识。"], "差不多"),
                X(("有没有发烧？吃过什么药吗？", "yǒu méiyǒu fāshāo? chī guo shénme yào ma?", "Any fever? Have you taken any medicine?", "Температура есть? Принимали какие-нибудь лекарства?", "Таб доред? Ягон дору хӯрдаед?"),
                  ("不发烧，我吃过一点儿感冒药，但是没用。", "bù fāshāo, wǒ chī guo yìdiǎnr gǎnmào yào, dànshì méi yòng.", "No fever; I took some cold medicine, but it didn't help.", "Температуры нет. Я принимаю средство от простуды, но оно не помогает.", "Таб надорам, каме доруи зуком хӯрдам, вале фоида накард."),
                  ["他的女朋友是老师。", "我想换一个大一点儿的房间。"], "感冒"),
                X(("我先给你检查一下，请把嘴张开。", "wǒ xiān gěi nǐ jiǎnchá yíxià, qǐng bǎ zuǐ zhāng kāi.", "Let me examine you first — please open your mouth.", "Сначала я вас осмотрю. Откройте рот.", "Аввал ман шуморо муоина мекунам, лутфан даҳонатонро кушоед."),
                  ("好的。医生，问题严重吗？", "hǎo de. yīshēng, wèntí yánzhòng ma?", "OK. Doctor, is it serious?", "Хорошо. Доктор, это серьёзно?", "Хуб. Духтур, мушкил ҷиддӣ аст?"),
                  ["我打算明年去旅游。", "这儿的咖啡很好喝。"], "检查"),
                X(("不严重，是嗓子发炎了。这个药一天吃三次，饭后吃。", "bù yánzhòng, shì sǎngzi fāyán le. zhège yào yì tiān chī sān cì, fàn hòu chī.", "Not serious — your throat is inflamed. Take this medicine three times a day, after meals.", "Не серьёзно, воспаление горла. Это лекарство — три раза в день после еды.", "Ҷиддӣ нест, гулӯ илтиҳоб кардааст. Ин доруро рӯзе се маротиба, баъди хӯрок истеъмол кунед."),
                  ("明白了，一天三次，饭后吃。", "míngbai le, yì tiān sān cì, fàn hòu chī.", "Got it: three times a day, after meals.", "Понятно: три раза в день после еды.", "Фаҳмидам: рӯзе се бор, баъди хӯрок."),
                  ["他昨天晚上没睡觉。", "我要去银行换钱。"], "严重"),
            ],
            "advanced": [
                X(("根据检查结果，你的血压偏高，平时工作压力大吗？", "gēnjù jiǎnchá jiéguǒ, nǐ de xuèyā piān gāo, píngshí gōngzuò yālì dà ma?", "Your results show slightly high blood pressure — is your work usually stressful?", "По результатам обследования давление у вас повышенное. На работе много стресса?", "Тибқи натиҷаи муоина фишори хунатон баланд аст, одатан фишори корӣ зиёд аст?"),
                  ("挺大的，经常加班，而且睡眠质量也不太好。", "tǐng dà de, jīngcháng jiābān, érqiě shuìmián zhìliàng yě bú tài hǎo.", "Quite a lot — I often work overtime, and I don't sleep very well either.", "Довольно много: часто задерживаюсь на работе, и сплю тоже не очень.", "Хеле зиёд, зуд-зуд изофакорӣ мекунам, илова бар ин хобам ҳам он қадар хуб нест."),
                  ["这次旅行的费用由公司承担。", "他把房子租给了一个留学生。", "这种花只在春天开。"], "压力"),
                X(("长期睡眠不足确实会影响血压。你平时运动吗？", "chángqī shuìmián bùzú quèshí huì yǐngxiǎng xuèyā. nǐ píngshí yùndòng ma?", "Long-term lack of sleep really does affect blood pressure. Do you exercise?", "Длительный недосып действительно влияет на давление. Вы занимаетесь спортом?", "Норасоии тӯлонии хоб дар ҳақиқат ба фишори хун таъсир мерасонад. Шумо варзиш мекунед?"),
                  ("很少，下班以后通常就没有精力了。", "hěn shǎo, xiàbān yǐhòu tōngcháng jiù méiyǒu jīnglì le.", "Rarely — after work I usually have no energy left.", "Редко, после работы обычно нет сил.", "Кам, баъди кор одатан қувват намемонад."),
                  ["这份合同需要双方签字。", "我们的航班在上海转机。", "他的口语比写作好。"], "精力"),
                X(("我建议你每天至少散步半小时，同时少吃咸的和油腻的。", "wǒ jiànyì nǐ měi tiān zhìshǎo sànbù bàn xiǎoshí, tóngshí shǎo chī xián de hé yóunì de.", "I suggest walking at least half an hour a day, and eating less salty and greasy food.", "Советую гулять хотя бы полчаса в день и поменьше есть солёного и жирного.", "Тавсия медиҳам ҳар рӯз ақаллан ним соат пиёда гардед ва хӯроки шӯру равғаниро камтар хӯред."),
                  ("好的，需要吃药控制吗？还是先观察一段时间？", "hǎo de, xūyào chī yào kòngzhì ma? háishi xiān guānchá yí duàn shíjiān?", "OK. Do I need medication to control it, or should we watch it for a while first?", "Хорошо. Нужно принимать лекарства или сначала понаблюдать?", "Хуб. Барои назорат дору лозим аст ё аввал муддате мушоҳида кунем?"),
                  ["这家商店的东西质量很好。", "请在黄线以外排队。", "他终于学会游泳了。"], "建议"),
                X(("先观察两周，每天早晚各量一次血压，记录下来。", "xiān guānchá liǎng zhōu, měi tiān zǎo wǎn gè liáng yí cì xuèyā, jìlù xiàlai.", "Watch it for two weeks first: measure your blood pressure morning and evening and write it down.", "Сначала понаблюдаем две недели: измеряйте давление утром и вечером и записывайте.", "Аввал ду ҳафта мушоҳида кунед: ҳар рӯз субҳу шом фишори хунро чен карда, қайд кунед."),
                  ("明白，两周后带着记录来复查，对吗？", "míngbai, liǎng zhōu hòu dài zhe jìlù lái fùchá, duì ma?", "Understood — come back for a follow-up in two weeks with the records, right?", "Понятно: через две недели прийти на повторный приём с записями, верно?", "Фаҳмидам, баъди ду ҳафта бо қайдҳо барои муоинаи такрорӣ биёям, дуруст?"),
                  ["这座城市的历史非常悠久。", "我把钥匙交给了邻居。", "他们正在讨论放假的安排。"], "记录"),
                X(("对。如果出现头晕或者胸闷，要马上来医院。", "duì. rúguǒ chūxiàn tóuyūn huòzhě xiōngmèn, yào mǎshàng lái yīyuàn.", "Right. If you feel dizzy or your chest feels tight, come to the hospital straight away.", "Да. Если появится головокружение или стеснение в груди, сразу приходите в больницу.", "Бале. Агар сарчархзанӣ ё фишори сина пайдо шавад, фавран ба беморхона биёед."),
                  ("我记住了，谢谢您这么耐心地解释。", "wǒ jì zhù le, xièxie nín zhème nàixīn de jiěshì.", "I'll remember that — thank you for explaining so patiently.", "Запомню. Спасибо, что так терпеливо объяснили.", "Дар хотир доштам, ташаккур, ки ин қадар бо сабр шарҳ додед."),
                  ["这个周末我们去郊区野餐吧。", "他的汉字写得越来越漂亮了。", "公司决定扩大生产规模。"], "耐心"),
            ],
        },
    },
    {
        "slug": "job-interview",
        "icon": "💼",
        "title": T("Job interview", "Собеседование", "Мусоҳибаи корӣ", "面试"),
        "description": T(
            "Introduce yourself and answer an interviewer's questions.",
            "Представьтесь и ответьте на вопросы интервьюера.",
            "Худро муаррифӣ кунед ва ба саволҳои мусоҳибгар ҷавоб диҳед.",
            "介绍自己，回答面试官的问题。",
        ),
        "npc": {"zh": "面试官", "role": T("Interviewer", "Интервьюер", "Мусоҳибгар", "面试官")},
        "tiers": {
            "beginner": [
                X(("你好！请介绍一下你自己。", "nǐ hǎo! qǐng jièshào yíxià nǐ zìjǐ.", "Hello! Please introduce yourself.", "Здравствуйте! Расскажите немного о себе.", "Салом! Лутфан худро муаррифӣ кунед."),
                  ("你好，我叫李明，今年二十五岁。", "nǐ hǎo, wǒ jiào Lǐ Míng, jīnnián èrshíwǔ suì.", "Hello, I'm Li Ming and I'm 25 years old.", "Здравствуйте, меня зовут Ли Мин, мне двадцать пять лет.", "Салом, номи ман Ли Мин, бисту панҷсолаам."),
                  [("我想喝一杯水。", "wǒ xiǎng hē yì bēi shuǐ."), ("明天是星期六。", "míngtiān shì xīngqīliù.")], "介绍"),
                X(("你会说什么语言？", "nǐ huì shuō shénme yǔyán?", "What languages can you speak?", "На каких языках вы говорите?", "Шумо бо кадом забонҳо гап мезанед?"),
                  ("我会说英语和一点儿汉语。", "wǒ huì shuō Yīngyǔ hé yìdiǎnr Hànyǔ.", "I speak English and a little Chinese.", "Я говорю по-английски и немного по-китайски.", "Ман англисӣ ва каме чинӣ гап мезанам."),
                  [("我住在三楼。", "wǒ zhù zài sān lóu."), ("这个苹果很大。", "zhège píngguǒ hěn dà.")], "会"),
                X(("你为什么想在这里工作？", "nǐ wèishénme xiǎng zài zhèlǐ gōngzuò?", "Why do you want to work here?", "Почему вы хотите работать здесь?", "Чаро шумо мехоҳед дар ин ҷо кор кунед?"),
                  ("因为我喜欢这个工作。", "yīnwèi wǒ xǐhuan zhège gōngzuò.", "Because I like this job.", "Потому что мне нравится эта работа.", "Чунки ба ман ин кор маъқул аст."),
                  [("我每天七点吃早饭。", "wǒ měi tiān qī diǎn chī zǎofàn."), ("他的车是白色的。", "tā de chē shì báisè de.")], "工作"),
            ],
            "intermediate": [
                X(("请简单介绍一下你以前的工作经验。", "qǐng jiǎndān jièshào yíxià nǐ yǐqián de gōngzuò jīngyàn.", "Please briefly describe your previous work experience.", "Кратко расскажите о своём опыте работы.", "Лутфан таҷрибаи кории пештараатонро мухтасар нақл кунед."),
                  ("我在一家贸易公司工作过两年，主要负责客户服务。", "wǒ zài yì jiā màoyì gōngsī gōngzuò guo liǎng nián, zhǔyào fùzé kèhù fúwù.", "I worked at a trading company for two years, mainly in customer service.", "У меня два года опыта в торговой компании, в основном — обслуживание клиентов.", "Ман ду сол дар як ширкати тиҷоратӣ кор кардаам, асосан барои хизматрасонии муштариён масъул будам."),
                  ["我的生日是十月三号。", "这条街晚上很热闹。"], "经验"),
                X(("你觉得自己最大的优点是什么？", "nǐ juéde zìjǐ zuì dà de yōudiǎn shì shénme?", "What do you think is your greatest strength?", "Какое ваше главное достоинство?", "Ба фикри шумо бузургтарин хислати хуби шумо чист?"),
                  ("我做事很认真，而且很快就能适应新环境。", "wǒ zuò shì hěn rènzhēn, érqiě hěn kuài jiù néng shìyìng xīn huánjìng.", "I'm conscientious, and I adapt quickly to new environments.", "Я ответственно отношусь к делу и быстро привыкаю к новой обстановке.", "Ман корро бо ҷиддият иҷро мекунам ва ба муҳити нав зуд мутобиқ мешавам."),
                  ["我们明天去动物园看熊猫。", "这个箱子太重了。"], "认真"),
                X(("这个工作有时候需要加班，你能接受吗？", "zhège gōngzuò yǒu shíhou xūyào jiābān, nǐ néng jiēshòu ma?", "This job sometimes needs overtime — is that OK for you?", "Иногда здесь нужно работать сверхурочно. Вас это устраивает?", "Ин кор баъзан изофакориро талаб мекунад, шумо қабул карда метавонед?"),
                  ("可以，只要提前通知，我都没问题。", "kěyǐ, zhǐyào tíqián tōngzhī, wǒ dōu méi wèntí.", "Yes — as long as I'm told in advance, it's no problem.", "Да, если предупредить заранее, без проблем.", "Бале, агар пешакӣ огоҳ кунед, ҳеҷ мушкиле нест."),
                  ["我的中文老师是北京人。", "这家医院离我家很近。"], "通知"),
                X(("好的，你还有什么问题想问我们吗？", "hǎo de, nǐ hái yǒu shénme wèntí xiǎng wèn wǒmen ma?", "OK. Do you have any questions for us?", "Хорошо. У вас есть к нам вопросы?", "Хуб. Шумо ба мо саволе доред?"),
                  ("请问什么时候能知道面试结果？", "qǐngwèn shénme shíhou néng zhīdào miànshì jiéguǒ?", "When will I know the result of the interview?", "Когда можно будет узнать результат собеседования?", "Натиҷаи мусоҳибаро кай фаҳмида метавонам?"),
                  ["我最喜欢的季节是秋天。", "他每天坐地铁上班。"], "结果"),
            ],
            "advanced": [
                X(("你在简历里提到曾经负责过一个跨部门项目，能具体说说吗？", "nǐ zài jiǎnlì li tídào céngjīng fùzé guo yí ge kuà bùmén xiàngmù, néng jùtǐ shuōshuo ma?", "Your résumé says you once led a cross-department project — can you go into detail?", "В резюме вы упомянули, что руководили межотдельским проектом. Расскажете подробнее?", "Дар тарҷумаи ҳолатон гуфтаед, ки боре лоиҳаи байнишӯъбавиро роҳбарӣ кардаед, метавонед муфассал нақл кунед?"),
                  ("当然，那个项目的目标是缩短交货周期，我主要负责协调各部门的进度。", "dāngrán, nàge xiàngmù de mùbiāo shì suōduǎn jiāohuò zhōuqī, wǒ zhǔyào fùzé xiétiáo gè bùmén de jìndù.", "Of course. The goal was to shorten delivery times; my main job was coordinating each department's progress.", "Конечно. Цель проекта — сократить сроки поставки, а моя задача — согласовывать сроки отделов.", "Албатта, ҳадафи лоиҳа кӯтоҳ кардани мӯҳлати таҳвил буд, ман асосан ҳамоҳангсозии пешрафти шӯъбаҳоро бар уҳда доштам."),
                  ["这个景点的门票包括导游服务。", "冬天的时候这里经常下雪。", "他的孩子刚上小学。"], "负责"),
                X(("在这个过程中，你遇到的最大困难是什么？", "zài zhège guòchéng zhōng, nǐ yù dào de zuì dà kùnnan shì shénme?", "What was the biggest difficulty you faced along the way?", "С какой главной трудностью вы столкнулись в процессе?", "Дар ин раванд бузургтарин мушкилие, ки ба он рӯ ба рӯ шудед, чӣ буд?"),
                  ("最大的困难是沟通，后来我们建立了每周例会制度，问题就解决了。", "zuì dà de kùnnan shì gōutōng, hòulái wǒmen jiànlì le měi zhōu lìhuì zhìdù, wèntí jiù jiějué le.", "Communication. Later we set up weekly meetings, and that solved it.", "Главная трудность — коммуникация. Потом мы ввели еженедельные планёрки, и проблема решилась.", "Мушкили асосӣ муошират буд, баъд мо ҷаласаҳои ҳарҳафтаина ташкил кардем ва мушкил ҳал шуд."),
                  ["这本词典对初学者很有帮助。", "我们的酒店离海边只有五分钟。", "他在比赛中受了轻伤。"], "困难"),
                X(("如果你的意见和上级不一致，你会怎么处理？", "rúguǒ nǐ de yìjiàn hé shàngjí bù yízhì, nǐ huì zěnme chǔlǐ?", "If your opinion differs from your manager's, how would you handle it?", "Если ваше мнение расходится с мнением руководителя, как вы поступите?", "Агар фикри шумо бо фикри роҳбаратон мувофиқ наояд, чӣ тавр рафтор мекунед?"),
                  ("我会先用数据说明我的理由，但最终会尊重团队的决定。", "wǒ huì xiān yòng shùjù shuōmíng wǒ de lǐyóu, dàn zuìzhōng huì zūnzhòng tuánduì de juédìng.", "I'd first explain my reasons with data, but in the end I'd respect the team's decision.", "Сначала объясню свои доводы с цифрами, но в итоге приму решение команды.", "Аввал далелҳоямро бо маълумот шарҳ медиҳам, вале дар ниҳоят қарори дастаро эҳтиром мекунам."),
                  ["这里的空气比城市里新鲜多了。", "我把那本书借给同学了。", "机场大巴每二十分钟一班。"], "尊重"),
                X(("我们这个职位的薪资是面议的，你的期望是多少？", "wǒmen zhège zhíwèi de xīnzī shì miànyì de, nǐ de qīwàng shì duōshao?", "The salary for this position is negotiable — what are you expecting?", "Зарплата на этой должности обсуждается. Каковы ваши ожидания?", "Маоши ин вазифа бо гуфтушунид муайян мешавад, интизории шумо чанд аст?"),
                  ("根据我的经验和市场水平，我希望月薪在一万五左右。", "gēnjù wǒ de jīngyàn hé shìchǎng shuǐpíng, wǒ xīwàng yuèxīn zài yíwàn wǔ zuǒyòu.", "Based on my experience and the market, I'd hope for around 15,000 a month.", "Исходя из опыта и рынка, рассчитываю примерно на 15 000 в месяц.", "Бо назардошти таҷриба ва сатҳи бозор, умедворам маоши моҳона тақрибан понздаҳ ҳазор бошад."),
                  ["这首歌让我想起了小时候。", "请不要在图书馆里大声说话。", "他已经习惯了这里的饮食。"], "左右"),
                X(("好的，我们会在一周内通知你复试的安排。", "hǎo de, wǒmen huì zài yì zhōu nèi tōngzhī nǐ fùshì de ānpái.", "OK, we'll let you know about the second interview within a week.", "Хорошо, в течение недели сообщим о втором этапе собеседования.", "Хуб, дар давоми як ҳафта дар бораи мусоҳибаи даври дуюм хабар медиҳем."),
                  ("谢谢您给我这次机会，期待您的消息。", "xièxie nín gěi wǒ zhè cì jīhuì, qīdài nín de xiāoxi.", "Thank you for this opportunity — I look forward to hearing from you.", "Спасибо за эту возможность, жду вашего ответа.", "Ташаккур барои ин имконият, мунтазири хабари шумо ҳастам."),
                  ["这条裤子需要改短一点儿。", "春天到了，树都绿了。", "他们决定下个月结婚。"], "机会"),
            ],
        },
    },
    {
        "slug": "convenience-store",
        "icon": "🏪",
        "title": T("Convenience store", "Магазин у дома", "Мағозаи наздик", "便利店"),
        "description": T(
            "Pay at the counter, top up your phone and sort out a payment problem.",
            "Расплатитесь на кассе, пополните телефон и решите проблему с оплатой.",
            "Дар касса пардохт кунед, ҳисоби телефонро пур кунед ва мушкили пардохтро ҳал кунед.",
            "结账、充话费、处理付款问题。",
        ),
        "npc": {"zh": "收银员", "role": T("Cashier", "Кассир", "Кассир", "收银员")},
        "tiers": {
            "beginner": [
                X(("你好！要袋子吗？", "nǐ hǎo! yào dàizi ma?", "Hello! Do you need a bag?", "Здравствуйте! Пакет нужен?", "Салом! Халта лозим аст?"),
                  ("不要，谢谢。", "bú yào, xièxie.", "No, thanks.", "Нет, спасибо.", "Не, ташаккур."),
                  [("我叫大卫。", "wǒ jiào Dàwèi."), ("他在睡觉。", "tā zài shuìjiào.")], "要"),
                X(("一共十五块。", "yígòng shíwǔ kuài.", "That's fifteen yuan altogether.", "Всего пятнадцать юаней.", "Ҳамагӣ понздаҳ юан."),
                  ("给你二十块。", "gěi nǐ èrshí kuài.", "Here's twenty.", "Вот двадцать.", "Инак бист юан."),
                  [("我是老师。", "wǒ shì lǎoshī."), ("我明天去学校。", "wǒ míngtiān qù xuéxiào.")], "块"),
                X(("找你五块。欢迎再来！", "zhǎo nǐ wǔ kuài. huānyíng zài lái!", "Five yuan change. Come again!", "Ваша сдача — пять юаней. Приходите ещё!", "Бақияатон панҷ юан. Боз биёед!"),
                  ("好的，再见！", "hǎo de, zàijiàn!", "OK, goodbye!", "Хорошо, до свидания!", "Хуб, хайр!"),
                  [("我很饿。", "wǒ hěn è."), ("这是什么？", "zhè shì shénme?")], "再见"),
            ],
            "intermediate": [
                X(("你好，需要帮你把饭团加热吗？", "nǐ hǎo, xūyào bāng nǐ bǎ fàntuán jiārè ma?", "Hi, would you like your rice ball heated up?", "Здравствуйте, разогреть вам рисовый шарик?", "Салом, биринҷгулачаатонро гарм кунам?"),
                  ("好的，麻烦你了。再拿一瓶矿泉水。", "hǎo de, máfan nǐ le. zài ná yì píng kuàngquánshuǐ.", "Yes, please. And a bottle of mineral water.", "Да, пожалуйста. И ещё бутылку минеральной воды.", "Бале, лутфан. Боз як шиша оби минералӣ."),
                  ["我的朋友住在上海。", "昨天的考试很难。"], "麻烦"),
                X(("矿泉水在后面的冰箱里，您自己拿一下。", "kuàngquánshuǐ zài hòumiàn de bīngxiāng li, nín zìjǐ ná yíxià.", "The mineral water is in the fridge at the back — please help yourself.", "Минеральная вода в холодильнике сзади, возьмите сами.", "Оби минералӣ дар яхдони қафо аст, худатон гиред."),
                  ("找到了。你们这儿可以交电话费吗？", "zhǎo dào le. nǐmen zhèr kěyǐ jiāo diànhuà fèi ma?", "Got it. Can I top up my phone here?", "Вот она. А здесь можно пополнить счёт телефона?", "Ёфтам. Дар ин ҷо пули телефонро пардохт кардан мумкин аст?"),
                  ["他的头发又黑又长。", "我们一起去打球吧。"], "冰箱"),
                X(("可以，告诉我手机号码和金额就行。", "kěyǐ, gàosu wǒ shǒujī hàomǎ hé jīn'é jiù xíng.", "Yes — just tell me the phone number and the amount.", "Можно, просто назовите номер и сумму.", "Мешавад, танҳо рақами телефон ва маблағро гӯед."),
                  ("号码是一三八一二三四五六七八，充一百块。", "hàomǎ shì yāo sān bā yāo èr sān sì wǔ liù qī bā, chōng yìbǎi kuài.", "The number is 138-1234-5678; top up 100 yuan.", "Номер 138-1234-5678, пополнить на 100 юаней.", "Рақам 138-1234-5678, сад юан пур кунед."),
                  ["我觉得这件衣服太长了。", "下雪的时候路很滑。"], "号码"),
                X(("好了，一共一百一十二块，您怎么付？", "hǎo le, yígòng yìbǎi yīshí'èr kuài, nín zěnme fù?", "Done — 112 yuan in total. How would you like to pay?", "Готово, всего 112 юаней. Как будете платить?", "Тайёр, ҳамагӣ саду дувоздаҳ юан. Чӣ тавр пардохт мекунед?"),
                  ("我用手机付吧，扫这个码对吗？", "wǒ yòng shǒujī fù ba, sǎo zhège mǎ duì ma?", "I'll pay by phone — I scan this code, right?", "Оплачу телефоном — сканировать этот код, да?", "Бо телефон пардохт мекунам, ҳамин кодро скан кунам, дуруст?"),
                  ["我妹妹喜欢画画儿。", "这个房间有两张床。"], "手机"),
            ],
            "advanced": [
                X(("不好意思，您刚才扫的码付款失败了，可能是网络的问题。", "bù hǎoyìsi, nín gāngcái sǎo de mǎ fùkuǎn shībài le, kěnéng shì wǎngluò de wèntí.", "Sorry, the payment for the code you just scanned failed — maybe a network problem.", "Извините, оплата по коду не прошла — возможно, проблема со связью.", "Бубахшед, пардохт бо коде, ки ҳозир скан кардед, нагузашт, шояд мушкили шабака бошад."),
                  ("可是我手机上显示已经扣款了，你能再查一下吗？", "kěshì wǒ shǒujī shang xiǎnshì yǐjīng kòukuǎn le, nǐ néng zài chá yíxià ma?", "But my phone shows the money was already taken — could you check again?", "Но у меня в телефоне видно, что деньги уже списаны. Проверьте ещё раз?", "Аммо дар телефонам нишон медиҳад, ки пул аллакай гирифта шуд, метавонед бори дигар санҷед?"),
                  ["这部电影改编自一本小说。", "他每年都去国外度假。", "我们应该尊重不同的文化。"], "显示"),
                X(("我这边确实没收到，系统有时候会延迟到账。", "wǒ zhèbiān quèshí méi shōudào, xìtǒng yǒu shíhou huì yánchí dàozhàng.", "It really hasn't arrived on my side — the system sometimes credits payments late.", "У меня действительно не пришло: система иногда зачисляет с задержкой.", "Дар тарафи ман воқеан нарасидааст, система баъзан бо таъхир ворид мекунад."),
                  ("那要是重复扣款了怎么办？我不想付两次。", "nà yàoshi chóngfù kòukuǎn le zěnme bàn? wǒ bù xiǎng fù liǎng cì.", "Then what if I'm charged twice? I don't want to pay double.", "А если спишут дважды? Я не хочу платить два раза.", "Агар ду бор гирифта шавад, чӣ мешавад? Ман намехоҳам ду бор пардохт кунам."),
                  ["这个问题的答案并不唯一。", "公园里的樱花开得正好。", "他在会议上提出了新方案。"], "系统"),
                X(("您放心，如果重复扣款，系统一般会在二十四小时内自动退回。", "nín fàngxīn, rúguǒ chóngfù kòukuǎn, xìtǒng yìbān huì zài èrshísì xiǎoshí nèi zìdòng tuìhuí.", "Don't worry — if you're charged twice, the system usually refunds it automatically within 24 hours.", "Не волнуйтесь: при двойном списании система обычно сама возвращает деньги в течение 24 часов.", "Хотирҷамъ бошед, агар ду бор гирифта шавад, система одатан дар давоми 24 соат худкор бармегардонад."),
                  ("那我先留一张小票作为凭证，可以吗？", "nà wǒ xiān liú yì zhāng xiǎopiào zuòwéi píngzhèng, kěyǐ ma?", "Then may I keep a receipt as proof for now?", "Тогда можно мне пока чек как подтверждение?", "Пас ман як чекро ҳамчун далел нигоҳ медорам, мешавад?"),
                  ["他的性格非常开朗。", "这个地区的交通十分便利。", "我们计划明年开一家分店。"], "自动"),
                X(("当然，我把交易记录打印出来给您，上面有流水号。", "dāngrán, wǒ bǎ jiāoyì jìlù dǎyìn chūlai gěi nín, shàngmiàn yǒu liúshuǐ hào.", "Of course — I'll print the transaction record for you; it has the reference number.", "Конечно, распечатаю вам запись операции, на ней есть её номер.", "Албатта, сабти амалиётро барои шумо чоп мекунам, дар он рақами амалиёт ҳаст."),
                  ("太好了，有问题我再拿着它来找你们。", "tài hǎo le, yǒu wèntí wǒ zài ná zhe tā lái zhǎo nǐmen.", "Great — if there's a problem, I'll bring it back to you.", "Отлично, если что — приду с ним к вам.", "Хеле хуб, агар мушкил бошад, бо он назди шумо меоям."),
                  ["那座山的风景美极了。", "他从小就想当医生。", "这次考试的成绩下周公布。"], "打印"),
                X(("好的。今天会员积分翻倍，要不要顺便办一张会员卡？", "hǎo de. jīntiān huìyuán jīfēn fānbèi, yào bu yào shùnbiàn bàn yì zhāng huìyuán kǎ?", "OK. Member points are doubled today — would you like a membership card while you're here?", "Хорошо. Сегодня бонусы для участников удваиваются — не хотите заодно оформить карту?", "Хуб. Имрӯз холҳои аъзо дучанд мешаванд, намехоҳед ҳамзамон корти аъзогӣ гиред?"),
                  ("下次吧，我今天赶时间，谢谢你的耐心。", "xià cì ba, wǒ jīntiān gǎn shíjiān, xièxie nǐ de nàixīn.", "Next time — I'm in a hurry today. Thanks for your patience.", "В другой раз, сегодня спешу. Спасибо за терпение.", "Дафъаи дигар, имрӯз шитоб дорам. Ташаккур барои сабратон."),
                  ["这条河流经好几个省。", "他把作业忘在家里了。", "研究表明睡眠很重要。"], "顺便"),
            ],
        },
    },
    {
        "slug": "travel",
        "icon": "🧳",
        "title": T("Travel", "Путешествие", "Сафар", "旅行"),
        "description": T(
            "Plan the day with a tour guide and learn the local customs.",
            "Обсудите маршрут с гидом и узнайте местные обычаи.",
            "Бо роҳбалад барномаи рӯзро муҳокима кунед ва урфу одати маҳаллиро омӯзед.",
            "跟导游安排行程，了解当地风俗。",
        ),
        "npc": {"zh": "导游", "role": T("Tour guide", "Гид", "Роҳбалад", "导游")},
        "tiers": {
            "beginner": [
                X(("欢迎来到北京！你是第一次来吗？", "huānyíng lái dào Běijīng! nǐ shì dì yī cì lái ma?", "Welcome to Beijing! Is this your first time here?", "Добро пожаловать в Пекин! Вы здесь впервые?", "Ба Пекин хуш омадед! Шумо бори аввал омадаед?"),
                  ("是，我很高兴！", "shì, wǒ hěn gāoxìng!", "Yes, and I'm very happy!", "Да, и мне очень радостно!", "Бале, ман хеле шодам!"),
                  [("我不吃肉。", "wǒ bù chī ròu."), ("他是我爸爸。", "tā shì wǒ bàba.")], "高兴"),
                X(("我们今天去长城。", "wǒmen jīntiān qù Chángchéng.", "Today we're going to the Great Wall.", "Сегодня мы едем на Великую стену.", "Имрӯз мо ба Девори Бузурги Чин меравем."),
                  ("太好了！长城远吗？", "tài hǎo le! Chángchéng yuǎn ma?", "Great! Is the Great Wall far?", "Отлично! Стена далеко?", "Аъло! Девори Бузург дур аст?"),
                  [("我的书在桌子上。", "wǒ de shū zài zhuōzi shang."), ("我会写汉字。", "wǒ huì xiě Hànzì.")], "远"),
                X(("不太远，坐车一个小时。", "bú tài yuǎn, zuò chē yí ge xiǎoshí.", "Not too far — an hour by bus.", "Не очень: час на автобусе.", "Он қадар дур не, бо мошин як соат."),
                  ("好的，我们几点走？", "hǎo de, wǒmen jǐ diǎn zǒu?", "OK, what time do we leave?", "Хорошо, во сколько выезжаем?", "Хуб, мо соати чанд меравем?"),
                  [("我有两个孩子。", "wǒ yǒu liǎng ge háizi."), ("这个菜不好吃。", "zhège cài bù hǎochī.")], "小时"),
            ],
            "intermediate": [
                X(("今天的行程是先参观故宫，下午去颐和园。", "jīntiān de xíngchéng shì xiān cānguān Gùgōng, xiàwǔ qù Yíhéyuán.", "Today's plan: the Forbidden City first, then the Summer Palace in the afternoon.", "Сегодня по плану сначала Запретный город, а днём — Летний дворец.", "Барномаи имрӯз: аввал Шаҳри Мамнӯъ, баъд аз зӯҳр Қасри Тобистона."),
                  ("故宫里可以拍照吗？", "Gùgōng li kěyǐ pāizhào ma?", "Can we take photos in the Forbidden City?", "В Запретном городе можно фотографировать?", "Дар Шаҳри Мамнӯъ акс гирифтан мумкин аст?"),
                  ["我昨天把作业交给老师了。", "这个超市的东西很便宜。"], "参观"),
                X(("大部分地方可以，但是有些宫殿里面不能用闪光灯。", "dà bùfen dìfang kěyǐ, dànshì yǒuxiē gōngdiàn lǐmiàn bù néng yòng shǎnguāngdēng.", "In most places, yes, but flash isn't allowed inside some of the halls.", "В большинстве мест можно, но в некоторых залах нельзя со вспышкой.", "Дар аксари ҷойҳо мешавад, вале дар баъзе қасрҳо аз дурахш истифода бурдан мумкин нест."),
                  ("明白了，我会注意的。中午在哪儿吃饭？", "míngbai le, wǒ huì zhùyì de. zhōngwǔ zài nǎr chī fàn?", "Got it, I'll keep that in mind. Where do we have lunch?", "Понятно, учту. А где будем обедать?", "Фаҳмидам, диққат мекунам. Нисфирӯзӣ дар куҷо хӯрок мехӯрем?"),
                  ["我每天晚上十一点睡觉。", "他的汉语说得越来越好了。"], "注意"),
                X(("我们会在附近一家老北京饭馆吃烤鸭。", "wǒmen huì zài fùjìn yì jiā lǎo Běijīng fànguǎn chī kǎoyā.", "We'll have roast duck at an old Beijing restaurant nearby.", "Пообедаем пекинской уткой в старом ресторанчике неподалёку.", "Дар як тарабхонаи кӯҳнаи пекинии наздик мурғобии бирён мехӯрем."),
                  ("听说北京烤鸭很有名，我早就想尝尝了。", "tīngshuō Běijīng kǎoyā hěn yǒumíng, wǒ zǎo jiù xiǎng chángchang le.", "I hear Beijing roast duck is famous — I've wanted to try it for ages.", "Говорят, пекинская утка знаменита — давно хочу её попробовать.", "Мешунавам мурғобии бирёни Пекин машҳур аст, кайҳо боз мехостам онро чашам."),
                  ["这个周末我得在家打扫房间。", "他坐错了公共汽车。"], "有名"),
                X(("请大家五点以前回到停车场，不要迟到。", "qǐng dàjiā wǔ diǎn yǐqián huí dào tíngchēchǎng, bú yào chídào.", "Everyone, please be back at the car park before five — don't be late.", "Пожалуйста, вернитесь на парковку до пяти, не опаздывайте.", "Лутфан ҳама то соати панҷ ба таваққуфгоҳ баргардед, дер накунед."),
                  ("好的，如果找不到路，我可以给你打电话吗？", "hǎo de, rúguǒ zhǎo bu dào lù, wǒ kěyǐ gěi nǐ dǎ diànhuà ma?", "OK — if I can't find the way, can I call you?", "Хорошо, а если не найду дорогу, можно вам позвонить?", "Хуб, агар роҳро наёбам, ба шумо занг зада метавонам?"),
                  ["我买了一本中文小说。", "今天的气温比昨天低。"], "迟到"),
            ],
            "advanced": [
                X(("接下来的三天，我们会深入体验云南少数民族的文化。", "jiē xiàlái de sān tiān, wǒmen huì shēnrù tǐyàn Yúnnán shǎoshù mínzú de wénhuà.", "Over the next three days we'll experience the culture of Yunnan's ethnic minorities in depth.", "Следующие три дня мы будем глубоко знакомиться с культурой народов Юньнани.", "Дар се рӯзи оянда мо фарҳанги ақаллиятҳои миллии Юннанро амиқ меомӯзем."),
                  ("行程里有没有机会跟当地人一起生活？", "xíngchéng li yǒu méiyǒu jīhuì gēn dāngdì rén yìqǐ shēnghuó?", "Is there a chance in the plan to live alongside local people?", "В программе есть возможность пожить вместе с местными жителями?", "Дар барнома имконияти якҷоя зиндагӣ кардан бо мардуми маҳаллӣ ҳаст?"),
                  ["这家银行的利率比较高。", "他把会议推迟到了下午。", "我的电脑需要更新系统。"], "体验"),
                X(("有，第二天晚上我们会住在傣族村民家里。", "yǒu, dì èr tiān wǎnshang wǒmen huì zhù zài Dǎizú cūnmín jiā li.", "Yes — on the second night we'll stay in the homes of Dai villagers.", "Да, на вторую ночь мы остановимся в домах жителей деревни народа дай.", "Ҳаст, шаби дуюм мо дар хонаи сокинони деҳаи қавми дай мемонем."),
                  ("我需要注意哪些当地的风俗习惯？", "wǒ xūyào zhùyì nǎxiē dāngdì de fēngsú xíguàn?", "Which local customs should I be aware of?", "На какие местные обычаи мне стоит обратить внимание?", "Ба кадом урфу одатҳои маҳаллӣ бояд диққат диҳам?"),
                  ["这种材料既轻又结实。", "他的病已经完全好了。", "银行周末不营业。"], "习惯"),
                X(("进门要脱鞋，另外不要随便摸小孩的头。", "jìn mén yào tuō xié, lìngwài bú yào suíbiàn mō xiǎohái de tóu.", "Take your shoes off when you go in, and don't casually touch children's heads.", "При входе нужно разуваться, и не стоит просто так трогать детей за голову.", "Ҳангоми даромадан пойафзолро кашед, инчунин сари кӯдаконро беҷо даст назанед."),
                  ("谢谢提醒，入乡随俗嘛，我一定会尊重他们的传统。", "xièxie tíxǐng, rù xiāng suí sú ma, wǒ yídìng huì zūnzhòng tāmen de chuántǒng.", "Thanks for the tip — when in Rome, do as the Romans do. I'll certainly respect their traditions.", "Спасибо, что предупредили: в чужой монастырь со своим уставом не ходят. Обязательно буду уважать их традиции.", "Ташаккур барои хотиррасонӣ: ба ҳар деҳе, ки равӣ, ба урфи он рафтор кун. Ман ҳатман анъанаҳои онҳоро эҳтиром мекунам."),
                  ["这个软件可以自动翻译文件。", "我们公司的总部在深圳。", "他最近在学弹钢琴。"], "传统"),
                X(("最后一天是自由活动，你可以去古城逛逛，也可以徒步去雪山脚下。", "zuìhòu yì tiān shì zìyóu huódòng, nǐ kěyǐ qù gǔchéng guàngguang, yě kěyǐ túbù qù xuěshān jiǎoxià.", "The last day is free time: wander the old town, or hike to the foot of the snow mountain.", "Последний день свободный: можно погулять по старому городу или пешком дойти до подножия снежной горы.", "Рӯзи охир вақти озод аст: метавонед дар шаҳри қадим гардиш кунед ё пиёда то доманаи кӯҳи барфӣ равед."),
                  ("徒步大概要多长时间？对体力的要求高吗？", "túbù dàgài yào duō cháng shíjiān? duì tǐlì de yāoqiú gāo ma?", "Roughly how long is the hike? Is it physically demanding?", "Сколько примерно длится поход? Нужна хорошая физическая форма?", "Пиёдагардӣ тақрибан чанд вақт мегирад? Қувваи ҷисмонии зиёд талаб мекунад?"),
                  ["这次讲座的内容非常实用。", "我把照片上传到网上了。", "我们小区新开了一家药店。"], "要求"),
                X(("来回大约五个小时，路不算难走，但是高原上容易累，要量力而行。", "láihuí dàyuē wǔ ge xiǎoshí, lù bú suàn nán zǒu, dànshì gāoyuán shang róngyì lèi, yào liàng lì ér xíng.", "About five hours there and back; the path isn't hard, but you tire easily at altitude, so know your limits.", "Туда и обратно около пяти часов. Дорога несложная, но на высоте быстро устаёшь — рассчитывайте силы.", "Рафтуомад тақрибан панҷ соат, роҳ душвор нест, вале дар баландкӯҳ зуд хаста мешавед, мувофиқи қувваатон рафтор кунед."),
                  ("那我准备好水和高原药品，慢慢走就是了。", "nà wǒ zhǔnbèi hǎo shuǐ hé gāoyuán yàopǐn, mànman zǒu jiù shì le.", "Then I'll get water and altitude medicine ready and just take it slowly.", "Тогда возьму воду и лекарства от горной болезни и пойду не спеша.", "Пас ман об ва доруҳои баландкӯҳиро тайёр карда, оҳиста-оҳиста меравам."),
                  ["这本杂志每个月出版一次。", "他向大家道了歉。", "我们的新同事是从广州来的。"], "准备"),
            ],
        },
    },
]

SCENE_BY_SLUG = {s["slug"]: s for s in SCENES}
