"""add next_review_at to learning_mistakes

Revision ID: 61482a6301b9
Revises: 757a5095116a
Create Date: 2026-09-22 21:42:06.105902

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '61482a6301b9'
down_revision: Union[str, Sequence[str], None] = '757a5095116a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('learning_mistakes', sa.Column('next_review_at', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('learning_mistakes', 'next_review_at')
    # ### end Alembic commands ###
