"""add pet teacher mode

Revision ID: 9ff480a197c2
Revises: c8b2486fff59
Create Date: 2026-09-22 14:29:57.141089

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9ff480a197c2'
down_revision: Union[str, Sequence[str], None] = 'c8b2486fff59'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('pet_teacher_cases',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('grammar_topic_id', sa.Integer(), nullable=True),
    sa.Column('hsk_level_id', sa.Integer(), nullable=False),
    sa.Column('wrong_sentence', sa.String(length=300), nullable=False),
    sa.Column('correct_sentence', sa.String(length=300), nullable=False),
    sa.Column('mistake_summary', sa.String(length=300), nullable=True),
    sa.Column('explanation_keywords', sa.JSON(), nullable=True),
    sa.Column('hint', sa.String(length=300), nullable=True),
    sa.Column('order_index', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['grammar_topic_id'], ['grammar_topics.id'], ),
    sa.ForeignKeyConstraint(['hsk_level_id'], ['hsk_levels.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_pet_teacher_cases_grammar_topic_id'), 'pet_teacher_cases', ['grammar_topic_id'], unique=False)
    op.create_index(op.f('ix_pet_teacher_cases_hsk_level_id'), 'pet_teacher_cases', ['hsk_level_id'], unique=False)
    op.create_index(op.f('ix_pet_teacher_cases_id'), 'pet_teacher_cases', ['id'], unique=False)
    op.create_table('user_taught_facts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('case_id', sa.Integer(), nullable=False),
    sa.Column('taught_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['case_id'], ['pet_teacher_cases.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'case_id', name='uq_user_case_taught')
    )
    op.create_index(op.f('ix_user_taught_facts_case_id'), 'user_taught_facts', ['case_id'], unique=False)
    op.create_index(op.f('ix_user_taught_facts_id'), 'user_taught_facts', ['id'], unique=False)
    op.create_index(op.f('ix_user_taught_facts_user_id'), 'user_taught_facts', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_user_taught_facts_user_id'), table_name='user_taught_facts')
    op.drop_index(op.f('ix_user_taught_facts_id'), table_name='user_taught_facts')
    op.drop_index(op.f('ix_user_taught_facts_case_id'), table_name='user_taught_facts')
    op.drop_table('user_taught_facts')
    op.drop_index(op.f('ix_pet_teacher_cases_id'), table_name='pet_teacher_cases')
    op.drop_index(op.f('ix_pet_teacher_cases_hsk_level_id'), table_name='pet_teacher_cases')
    op.drop_index(op.f('ix_pet_teacher_cases_grammar_topic_id'), table_name='pet_teacher_cases')
    op.drop_table('pet_teacher_cases')
    # ### end Alembic commands ###
