"""add user xp coins wallet and quest claimed flag

Revision ID: c6acf8197ca2
Revises: 2ed95eea4fb6
Create Date: 2026-09-22 15:18:51.480688

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c6acf8197ca2'
down_revision: Union[str, Sequence[str], None] = '2ed95eea4fb6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('daily_quests', sa.Column('claimed', sa.Boolean(), nullable=True))
    op.add_column('users', sa.Column('total_xp', sa.Integer(), nullable=True))
    op.add_column('users', sa.Column('coins', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'coins')
    op.drop_column('users', 'total_xp')
    op.drop_column('daily_quests', 'claimed')
    # ### end Alembic commands ###
