"""baseline schema

Revision ID: c8b2486fff59
Revises: 
Create Date: 2026-09-22 14:05:48.583066

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c8b2486fff59'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('achievements',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('code', sa.String(length=60), nullable=False),
    sa.Column('title', sa.String(length=150), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('icon', sa.String(length=20), nullable=True),
    sa.Column('category', sa.String(length=30), nullable=True),
    sa.Column('criteria', sa.JSON(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_achievements_code'), 'achievements', ['code'], unique=True)
    op.create_index(op.f('ix_achievements_id'), 'achievements', ['id'], unique=False)
    op.create_table('animals',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('slug', sa.String(length=50), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('species', sa.String(length=100), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('image_url', sa.String(length=500), nullable=True),
    sa.Column('accent_color', sa.String(length=20), nullable=True),
    sa.Column('personality', sa.String(length=300), nullable=True),
    sa.Column('tone_style', sa.Text(), nullable=True),
    sa.Column('preferred_mechanics', sa.Text(), nullable=True),
    sa.Column('special_ability', sa.String(length=300), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_animals_id'), 'animals', ['id'], unique=False)
    op.create_index(op.f('ix_animals_name'), 'animals', ['name'], unique=True)
    op.create_index(op.f('ix_animals_slug'), 'animals', ['slug'], unique=True)
    op.create_table('hsk_levels',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('level', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=100), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('total_vocab_target', sa.Integer(), nullable=True),
    sa.Column('mastery_to_unlock_next', sa.Float(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_hsk_levels_id'), 'hsk_levels', ['id'], unique=False)
    op.create_index(op.f('ix_hsk_levels_level'), 'hsk_levels', ['level'], unique=True)
    op.create_table('locations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('slug', sa.String(length=50), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('kind', sa.String(length=30), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('unlock_level', sa.Integer(), nullable=True),
    sa.Column('unlock_skill_mastery', sa.Float(), nullable=True),
    sa.Column('position_x', sa.Integer(), nullable=True),
    sa.Column('position_y', sa.Integer(), nullable=True),
    sa.Column('icon', sa.String(length=20), nullable=True),
    sa.Column('accent', sa.String(length=20), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_locations_id'), 'locations', ['id'], unique=False)
    op.create_index(op.f('ix_locations_slug'), 'locations', ['slug'], unique=True)
    op.create_table('skills',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('code', sa.String(length=50), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('category', sa.String(length=50), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_skills_code'), 'skills', ['code'], unique=True)
    op.create_index(op.f('ix_skills_id'), 'skills', ['id'], unique=False)
    op.create_table('animal_personalities',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('animal_id', sa.Integer(), nullable=False),
    sa.Column('traits', sa.String(length=300), nullable=True),
    sa.Column('energy', sa.Integer(), nullable=True),
    sa.Column('humor', sa.Integer(), nullable=True),
    sa.Column('patience', sa.Integer(), nullable=True),
    sa.Column('strictness', sa.Integer(), nullable=True),
    sa.Column('catchphrase', sa.String(length=200), nullable=True),
    sa.Column('chat_style', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['animal_id'], ['animals.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('animal_id')
    )
    op.create_index(op.f('ix_animal_personalities_id'), 'animal_personalities', ['id'], unique=False)
    op.create_table('grammar_topics',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('hsk_level_id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('pattern', sa.String(length=200), nullable=True),
    sa.Column('explanation', sa.Text(), nullable=True),
    sa.Column('examples', sa.Text(), nullable=True),
    sa.Column('order_index', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['hsk_level_id'], ['hsk_levels.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_grammar_topics_hsk_level_id'), 'grammar_topics', ['hsk_level_id'], unique=False)
    op.create_index(op.f('ix_grammar_topics_id'), 'grammar_topics', ['id'], unique=False)
    op.create_table('lessons',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('hsk_level_id', sa.Integer(), nullable=True),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('summary', sa.String(length=300), nullable=True),
    sa.Column('content', sa.Text(), nullable=True),
    sa.Column('lesson_type', sa.String(length=30), nullable=True),
    sa.Column('order_index', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['hsk_level_id'], ['hsk_levels.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_lessons_hsk_level_id'), 'lessons', ['hsk_level_id'], unique=False)
    op.create_index(op.f('ix_lessons_id'), 'lessons', ['id'], unique=False)
    op.create_table('npcs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('location_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('role', sa.String(length=100), nullable=True),
    sa.Column('title', sa.String(length=100), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('avatar_url', sa.String(length=500), nullable=True),
    sa.Column('personality', sa.String(length=300), nullable=True),
    sa.Column('speech_style', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['location_id'], ['locations.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_npcs_id'), 'npcs', ['id'], unique=False)
    op.create_index(op.f('ix_npcs_location_id'), 'npcs', ['location_id'], unique=False)
    op.create_table('scenarios',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('location_id', sa.Integer(), nullable=False),
    sa.Column('slug', sa.String(length=80), nullable=False),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('scenario_type', sa.String(length=20), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('min_hsk_level', sa.Integer(), nullable=True),
    sa.Column('difficulty', sa.Integer(), nullable=True),
    sa.Column('is_case', sa.Boolean(), nullable=True),
    sa.Column('case_data', sa.JSON(), nullable=True),
    sa.Column('requires_voice', sa.Boolean(), nullable=True),
    sa.Column('order_index', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['location_id'], ['locations.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_scenarios_id'), 'scenarios', ['id'], unique=False)
    op.create_index(op.f('ix_scenarios_location_id'), 'scenarios', ['location_id'], unique=False)
    op.create_index(op.f('ix_scenarios_slug'), 'scenarios', ['slug'], unique=True)
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=50), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('animal_id', sa.Integer(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['animal_id'], ['animals.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_index(op.f('ix_users_id'), 'users', ['id'], unique=False)
    op.create_index(op.f('ix_users_username'), 'users', ['username'], unique=True)
    op.create_table('vocabulary_words',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('hsk_level_id', sa.Integer(), nullable=False),
    sa.Column('simplified', sa.String(length=50), nullable=False),
    sa.Column('traditional', sa.String(length=50), nullable=True),
    sa.Column('pinyin', sa.String(length=100), nullable=False),
    sa.Column('meanings', sa.String(length=300), nullable=True),
    sa.Column('word_type', sa.String(length=30), nullable=True),
    sa.Column('example', sa.Text(), nullable=True),
    sa.Column('example_pinyin', sa.String(length=200), nullable=True),
    sa.ForeignKeyConstraint(['hsk_level_id'], ['hsk_levels.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('hsk_level_id', 'simplified', name='uq_word_level')
    )
    op.create_index(op.f('ix_vocabulary_words_hsk_level_id'), 'vocabulary_words', ['hsk_level_id'], unique=False)
    op.create_index(op.f('ix_vocabulary_words_id'), 'vocabulary_words', ['id'], unique=False)
    op.create_table('daily_quests',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('quest_date', sa.Date(), nullable=True),
    sa.Column('quest_type', sa.String(length=30), nullable=False),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('target', sa.Integer(), nullable=True),
    sa.Column('progress', sa.Integer(), nullable=True),
    sa.Column('completed', sa.Boolean(), nullable=True),
    sa.Column('reward_xp', sa.Integer(), nullable=True),
    sa.Column('reward_coins', sa.Integer(), nullable=True),
    sa.Column('flavor', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'quest_date', 'quest_type', name='uq_user_quest')
    )
    op.create_index(op.f('ix_daily_quests_id'), 'daily_quests', ['id'], unique=False)
    op.create_index(op.f('ix_daily_quests_user_id'), 'daily_quests', ['user_id'], unique=False)
    op.create_table('dialogues',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('scenario_id', sa.Integer(), nullable=True),
    sa.Column('npc_id', sa.Integer(), nullable=True),
    sa.Column('turn_index', sa.Integer(), nullable=True),
    sa.Column('speaker', sa.String(length=10), nullable=True),
    sa.Column('text', sa.Text(), nullable=False),
    sa.Column('pinyin', sa.String(length=300), nullable=True),
    sa.Column('english', sa.String(length=300), nullable=True),
    sa.Column('prompt', sa.Text(), nullable=True),
    sa.Column('expected_keywords', sa.JSON(), nullable=True),
    sa.Column('requires_voice', sa.Boolean(), nullable=True),
    sa.Column('reaction_correct', sa.String(length=200), nullable=True),
    sa.Column('reaction_incorrect', sa.String(length=200), nullable=True),
    sa.ForeignKeyConstraint(['npc_id'], ['npcs.id'], ),
    sa.ForeignKeyConstraint(['scenario_id'], ['scenarios.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_dialogues_id'), 'dialogues', ['id'], unique=False)
    op.create_index(op.f('ix_dialogues_npc_id'), 'dialogues', ['npc_id'], unique=False)
    op.create_index(op.f('ix_dialogues_scenario_id'), 'dialogues', ['scenario_id'], unique=False)
    op.create_table('duels',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=True),
    sa.Column('challenge_type', sa.String(length=30), nullable=True),
    sa.Column('question_data', sa.JSON(), nullable=True),
    sa.Column('winner_id', sa.Integer(), nullable=True),
    sa.Column('started_at', sa.DateTime(), nullable=True),
    sa.Column('finished_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['winner_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_duels_id'), 'duels', ['id'], unique=False)
    op.create_table('learning_mistakes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('mistake_type', sa.String(length=30), nullable=False),
    sa.Column('reference', sa.String(length=300), nullable=False),
    sa.Column('question_text', sa.Text(), nullable=True),
    sa.Column('answer_given', sa.String(length=300), nullable=True),
    sa.Column('correct_answer', sa.String(length=300), nullable=True),
    sa.Column('priority', sa.Integer(), nullable=True),
    sa.Column('occurrences', sa.Integer(), nullable=True),
    sa.Column('mastered', sa.Boolean(), nullable=True),
    sa.Column('mastered_at', sa.DateTime(), nullable=True),
    sa.Column('last_seen_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'mistake_type', 'reference', name='uq_user_mistake')
    )
    op.create_index(op.f('ix_learning_mistakes_id'), 'learning_mistakes', ['id'], unique=False)
    op.create_index(op.f('ix_learning_mistakes_user_id'), 'learning_mistakes', ['user_id'], unique=False)
    op.create_table('lesson_skills',
    sa.Column('lesson_id', sa.Integer(), nullable=False),
    sa.Column('skill_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['lesson_id'], ['lessons.id'], ),
    sa.ForeignKeyConstraint(['skill_id'], ['skills.id'], ),
    sa.PrimaryKeyConstraint('lesson_id', 'skill_id')
    )
    op.create_table('missions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('scenario_id', sa.Integer(), nullable=True),
    sa.Column('slug', sa.String(length=80), nullable=False),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('objective', sa.Text(), nullable=True),
    sa.Column('kind', sa.String(length=30), nullable=True),
    sa.Column('min_hsk_level', sa.Integer(), nullable=True),
    sa.Column('reward_xp', sa.Integer(), nullable=True),
    sa.Column('reward_coins', sa.Integer(), nullable=True),
    sa.Column('target_count', sa.Integer(), nullable=True),
    sa.Column('sort_order', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['scenario_id'], ['scenarios.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_missions_id'), 'missions', ['id'], unique=False)
    op.create_index(op.f('ix_missions_scenario_id'), 'missions', ['scenario_id'], unique=False)
    op.create_index(op.f('ix_missions_slug'), 'missions', ['slug'], unique=True)
    op.create_table('progress',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('lesson_id', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('score', sa.Integer(), nullable=True),
    sa.Column('completed_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['lesson_id'], ['lessons.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'lesson_id', name='uq_user_lesson')
    )
    op.create_index(op.f('ix_progress_id'), 'progress', ['id'], unique=False)
    op.create_index(op.f('ix_progress_lesson_id'), 'progress', ['lesson_id'], unique=False)
    op.create_index(op.f('ix_progress_user_id'), 'progress', ['user_id'], unique=False)
    op.create_table('user_achievements',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('achievement_id', sa.Integer(), nullable=False),
    sa.Column('unlocked_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['achievement_id'], ['achievements.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'achievement_id', name='uq_user_achievement')
    )
    op.create_index(op.f('ix_user_achievements_achievement_id'), 'user_achievements', ['achievement_id'], unique=False)
    op.create_index(op.f('ix_user_achievements_id'), 'user_achievements', ['id'], unique=False)
    op.create_index(op.f('ix_user_achievements_user_id'), 'user_achievements', ['user_id'], unique=False)
    op.create_table('user_animals',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('animal_id', sa.Integer(), nullable=False),
    sa.Column('bonded_at', sa.DateTime(), nullable=True),
    sa.Column('bond_level', sa.Integer(), nullable=True),
    sa.Column('bond_points', sa.Integer(), nullable=True),
    sa.Column('interactions', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['animal_id'], ['animals.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id')
    )
    op.create_index(op.f('ix_user_animals_id'), 'user_animals', ['id'], unique=False)
    op.create_table('user_profiles',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('native_language', sa.String(length=50), nullable=True),
    sa.Column('goal_text', sa.String(length=300), nullable=True),
    sa.Column('daily_goal_minutes', sa.Integer(), nullable=True),
    sa.Column('avatar_color', sa.String(length=20), nullable=True),
    sa.Column('bio', sa.Text(), nullable=True),
    sa.Column('level_test_score', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id')
    )
    op.create_index(op.f('ix_user_profiles_id'), 'user_profiles', ['id'], unique=False)
    op.create_table('user_skills',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('skill_id', sa.Integer(), nullable=False),
    sa.Column('level', sa.Integer(), nullable=True),
    sa.Column('xp', sa.Integer(), nullable=True),
    sa.Column('mastery', sa.Float(), nullable=True),
    sa.Column('last_updated', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['skill_id'], ['skills.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'skill_id', name='uq_user_skill')
    )
    op.create_index(op.f('ix_user_skills_id'), 'user_skills', ['id'], unique=False)
    op.create_index(op.f('ix_user_skills_skill_id'), 'user_skills', ['skill_id'], unique=False)
    op.create_index(op.f('ix_user_skills_user_id'), 'user_skills', ['user_id'], unique=False)
    op.create_table('user_streaks',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('current_streak', sa.Integer(), nullable=True),
    sa.Column('longest_streak', sa.Integer(), nullable=True),
    sa.Column('total_active_days', sa.Integer(), nullable=True),
    sa.Column('last_active_date', sa.Date(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id')
    )
    op.create_index(op.f('ix_user_streaks_id'), 'user_streaks', ['id'], unique=False)
    op.create_table('user_vocabulary',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('word_id', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=True),
    sa.Column('mastery', sa.Float(), nullable=True),
    sa.Column('times_seen', sa.Integer(), nullable=True),
    sa.Column('times_missed', sa.Integer(), nullable=True),
    sa.Column('last_reviewed_at', sa.DateTime(), nullable=True),
    sa.Column('next_review_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['word_id'], ['vocabulary_words.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'word_id', name='uq_user_word')
    )
    op.create_index(op.f('ix_user_vocabulary_id'), 'user_vocabulary', ['id'], unique=False)
    op.create_index(op.f('ix_user_vocabulary_user_id'), 'user_vocabulary', ['user_id'], unique=False)
    op.create_index(op.f('ix_user_vocabulary_word_id'), 'user_vocabulary', ['word_id'], unique=False)
    op.create_table('dialogue_choices',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('dialogue_id', sa.Integer(), nullable=False),
    sa.Column('label', sa.String(length=200), nullable=False),
    sa.Column('response_text', sa.Text(), nullable=True),
    sa.Column('is_best', sa.Boolean(), nullable=True),
    sa.Column('feedback', sa.Text(), nullable=True),
    sa.Column('next_turn', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['dialogue_id'], ['dialogues.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_dialogue_choices_dialogue_id'), 'dialogue_choices', ['dialogue_id'], unique=False)
    op.create_index(op.f('ix_dialogue_choices_id'), 'dialogue_choices', ['id'], unique=False)
    op.create_table('duel_participants',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('duel_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('role', sa.String(length=20), nullable=True),
    sa.Column('score', sa.Integer(), nullable=True),
    sa.Column('correct_count', sa.Integer(), nullable=True),
    sa.Column('answered', sa.Integer(), nullable=True),
    sa.Column('finished', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['duel_id'], ['duels.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('duel_id', 'user_id', name='uq_duel_user')
    )
    op.create_index(op.f('ix_duel_participants_duel_id'), 'duel_participants', ['duel_id'], unique=False)
    op.create_index(op.f('ix_duel_participants_id'), 'duel_participants', ['id'], unique=False)
    op.create_index(op.f('ix_duel_participants_user_id'), 'duel_participants', ['user_id'], unique=False)
    op.create_table('user_missions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('mission_id', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=True),
    sa.Column('progress', sa.Integer(), nullable=True),
    sa.Column('completed_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['mission_id'], ['missions.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'mission_id', name='uq_user_mission')
    )
    op.create_index(op.f('ix_user_missions_id'), 'user_missions', ['id'], unique=False)
    op.create_index(op.f('ix_user_missions_mission_id'), 'user_missions', ['mission_id'], unique=False)
    op.create_index(op.f('ix_user_missions_user_id'), 'user_missions', ['user_id'], unique=False)
    op.create_table('voice_attempts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('scenario_id', sa.Integer(), nullable=True),
    sa.Column('dialogue_id', sa.Integer(), nullable=True),
    sa.Column('prompt_text', sa.Text(), nullable=True),
    sa.Column('spoken_text', sa.Text(), nullable=True),
    sa.Column('transcript', sa.Text(), nullable=True),
    sa.Column('pronunciation', sa.Float(), nullable=True),
    sa.Column('tones', sa.Float(), nullable=True),
    sa.Column('fluency', sa.Float(), nullable=True),
    sa.Column('grammar', sa.Float(), nullable=True),
    sa.Column('relevance', sa.Float(), nullable=True),
    sa.Column('response_time_ms', sa.Integer(), nullable=True),
    sa.Column('overall', sa.Float(), nullable=True),
    sa.Column('feedback', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['dialogue_id'], ['dialogues.id'], ),
    sa.ForeignKeyConstraint(['scenario_id'], ['scenarios.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_voice_attempts_dialogue_id'), 'voice_attempts', ['dialogue_id'], unique=False)
    op.create_index(op.f('ix_voice_attempts_id'), 'voice_attempts', ['id'], unique=False)
    op.create_index(op.f('ix_voice_attempts_scenario_id'), 'voice_attempts', ['scenario_id'], unique=False)
    op.create_index(op.f('ix_voice_attempts_user_id'), 'voice_attempts', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_voice_attempts_user_id'), table_name='voice_attempts')
    op.drop_index(op.f('ix_voice_attempts_scenario_id'), table_name='voice_attempts')
    op.drop_index(op.f('ix_voice_attempts_id'), table_name='voice_attempts')
    op.drop_index(op.f('ix_voice_attempts_dialogue_id'), table_name='voice_attempts')
    op.drop_table('voice_attempts')
    op.drop_index(op.f('ix_user_missions_user_id'), table_name='user_missions')
    op.drop_index(op.f('ix_user_missions_mission_id'), table_name='user_missions')
    op.drop_index(op.f('ix_user_missions_id'), table_name='user_missions')
    op.drop_table('user_missions')
    op.drop_index(op.f('ix_duel_participants_user_id'), table_name='duel_participants')
    op.drop_index(op.f('ix_duel_participants_id'), table_name='duel_participants')
    op.drop_index(op.f('ix_duel_participants_duel_id'), table_name='duel_participants')
    op.drop_table('duel_participants')
    op.drop_index(op.f('ix_dialogue_choices_id'), table_name='dialogue_choices')
    op.drop_index(op.f('ix_dialogue_choices_dialogue_id'), table_name='dialogue_choices')
    op.drop_table('dialogue_choices')
    op.drop_index(op.f('ix_user_vocabulary_word_id'), table_name='user_vocabulary')
    op.drop_index(op.f('ix_user_vocabulary_user_id'), table_name='user_vocabulary')
    op.drop_index(op.f('ix_user_vocabulary_id'), table_name='user_vocabulary')
    op.drop_table('user_vocabulary')
    op.drop_index(op.f('ix_user_streaks_id'), table_name='user_streaks')
    op.drop_table('user_streaks')
    op.drop_index(op.f('ix_user_skills_user_id'), table_name='user_skills')
    op.drop_index(op.f('ix_user_skills_skill_id'), table_name='user_skills')
    op.drop_index(op.f('ix_user_skills_id'), table_name='user_skills')
    op.drop_table('user_skills')
    op.drop_index(op.f('ix_user_profiles_id'), table_name='user_profiles')
    op.drop_table('user_profiles')
    op.drop_index(op.f('ix_user_animals_id'), table_name='user_animals')
    op.drop_table('user_animals')
    op.drop_index(op.f('ix_user_achievements_user_id'), table_name='user_achievements')
    op.drop_index(op.f('ix_user_achievements_id'), table_name='user_achievements')
    op.drop_index(op.f('ix_user_achievements_achievement_id'), table_name='user_achievements')
    op.drop_table('user_achievements')
    op.drop_index(op.f('ix_progress_user_id'), table_name='progress')
    op.drop_index(op.f('ix_progress_lesson_id'), table_name='progress')
    op.drop_index(op.f('ix_progress_id'), table_name='progress')
    op.drop_table('progress')
    op.drop_index(op.f('ix_missions_slug'), table_name='missions')
    op.drop_index(op.f('ix_missions_scenario_id'), table_name='missions')
    op.drop_index(op.f('ix_missions_id'), table_name='missions')
    op.drop_table('missions')
    op.drop_table('lesson_skills')
    op.drop_index(op.f('ix_learning_mistakes_user_id'), table_name='learning_mistakes')
    op.drop_index(op.f('ix_learning_mistakes_id'), table_name='learning_mistakes')
    op.drop_table('learning_mistakes')
    op.drop_index(op.f('ix_duels_id'), table_name='duels')
    op.drop_table('duels')
    op.drop_index(op.f('ix_dialogues_scenario_id'), table_name='dialogues')
    op.drop_index(op.f('ix_dialogues_npc_id'), table_name='dialogues')
    op.drop_index(op.f('ix_dialogues_id'), table_name='dialogues')
    op.drop_table('dialogues')
    op.drop_index(op.f('ix_daily_quests_user_id'), table_name='daily_quests')
    op.drop_index(op.f('ix_daily_quests_id'), table_name='daily_quests')
    op.drop_table('daily_quests')
    op.drop_index(op.f('ix_vocabulary_words_id'), table_name='vocabulary_words')
    op.drop_index(op.f('ix_vocabulary_words_hsk_level_id'), table_name='vocabulary_words')
    op.drop_table('vocabulary_words')
    op.drop_index(op.f('ix_users_username'), table_name='users')
    op.drop_index(op.f('ix_users_id'), table_name='users')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_scenarios_slug'), table_name='scenarios')
    op.drop_index(op.f('ix_scenarios_location_id'), table_name='scenarios')
    op.drop_index(op.f('ix_scenarios_id'), table_name='scenarios')
    op.drop_table('scenarios')
    op.drop_index(op.f('ix_npcs_location_id'), table_name='npcs')
    op.drop_index(op.f('ix_npcs_id'), table_name='npcs')
    op.drop_table('npcs')
    op.drop_index(op.f('ix_lessons_id'), table_name='lessons')
    op.drop_index(op.f('ix_lessons_hsk_level_id'), table_name='lessons')
    op.drop_table('lessons')
    op.drop_index(op.f('ix_grammar_topics_id'), table_name='grammar_topics')
    op.drop_index(op.f('ix_grammar_topics_hsk_level_id'), table_name='grammar_topics')
    op.drop_table('grammar_topics')
    op.drop_index(op.f('ix_animal_personalities_id'), table_name='animal_personalities')
    op.drop_table('animal_personalities')
    op.drop_index(op.f('ix_skills_id'), table_name='skills')
    op.drop_index(op.f('ix_skills_code'), table_name='skills')
    op.drop_table('skills')
    op.drop_index(op.f('ix_locations_slug'), table_name='locations')
    op.drop_index(op.f('ix_locations_id'), table_name='locations')
    op.drop_table('locations')
    op.drop_index(op.f('ix_hsk_levels_level'), table_name='hsk_levels')
    op.drop_index(op.f('ix_hsk_levels_id'), table_name='hsk_levels')
    op.drop_table('hsk_levels')
    op.drop_index(op.f('ix_animals_slug'), table_name='animals')
    op.drop_index(op.f('ix_animals_name'), table_name='animals')
    op.drop_index(op.f('ix_animals_id'), table_name='animals')
    op.drop_table('animals')
    op.drop_index(op.f('ix_achievements_id'), table_name='achievements')
    op.drop_index(op.f('ix_achievements_code'), table_name='achievements')
    op.drop_table('achievements')
    # ### end Alembic commands ###
