"""add hanzi writing-progress fields to user_hanzi

Revision ID: d498a985f521
Revises: e962111277a7
Create Date: 2026-09-24 23:17:14.320867

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision: str = 'd498a985f521'
down_revision: Union[str, Sequence[str], None] = 'e962111277a7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user_hanzi', sa.Column('writing_status', sa.String(length=20), nullable=True))
    op.add_column('user_hanzi', sa.Column('writing_mastery', sa.Float(), nullable=True))
    op.add_column('user_hanzi', sa.Column('times_written', sa.Integer(), nullable=True))
    op.add_column('user_hanzi', sa.Column('last_written_at', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user_hanzi', 'last_written_at')
    op.drop_column('user_hanzi', 'times_written')
    op.drop_column('user_hanzi', 'writing_mastery')
    op.drop_column('user_hanzi', 'writing_status')
    # ### end Alembic commands ###
