"""add hanzi, user_hanzi, user_grammar tables and grammar/hsk_level columns

Revision ID: e962111277a7
Revises: f2a8c4d1b673
Create Date: 2026-09-24 22:51:03.629486

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision: str = 'e962111277a7'
down_revision: Union[str, Sequence[str], None] = 'f2a8c4d1b673'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('hanzi',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('hsk_level_id', sa.Integer(), nullable=False),
    sa.Column('character', sa.String(length=4), nullable=False),
    sa.Column('pinyin', sa.String(length=50), nullable=True),
    sa.Column('meaning', sa.String(length=300), nullable=True),
    sa.Column('radical', sa.String(length=10), nullable=True),
    sa.Column('decomposition', sa.String(length=50), nullable=True),
    sa.Column('stroke_count', sa.Integer(), nullable=True),
    sa.Column('handwriting_tier', sa.String(length=20), nullable=True),
    sa.Column('stroke_data', sa.JSON(), nullable=True),
    sa.Column('order_index', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['hsk_level_id'], ['hsk_levels.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('hsk_level_id', 'character', name='uq_hanzi_level')
    )
    op.create_index(op.f('ix_hanzi_character'), 'hanzi', ['character'], unique=False)
    op.create_index(op.f('ix_hanzi_hsk_level_id'), 'hanzi', ['hsk_level_id'], unique=False)
    op.create_index(op.f('ix_hanzi_id'), 'hanzi', ['id'], unique=False)
    op.create_table('user_grammar',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('topic_id', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=True),
    sa.Column('mastery', sa.Float(), nullable=True),
    sa.Column('times_practiced', sa.Integer(), nullable=True),
    sa.Column('times_missed', sa.Integer(), nullable=True),
    sa.Column('last_reviewed_at', sa.DateTime(), nullable=True),
    sa.Column('next_review_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['topic_id'], ['grammar_topics.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'topic_id', name='uq_user_grammar')
    )
    op.create_index(op.f('ix_user_grammar_id'), 'user_grammar', ['id'], unique=False)
    op.create_index(op.f('ix_user_grammar_topic_id'), 'user_grammar', ['topic_id'], unique=False)
    op.create_index(op.f('ix_user_grammar_user_id'), 'user_grammar', ['user_id'], unique=False)
    op.create_table('user_hanzi',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('hanzi_id', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=True),
    sa.Column('mastery', sa.Float(), nullable=True),
    sa.Column('times_seen', sa.Integer(), nullable=True),
    sa.Column('times_missed', sa.Integer(), nullable=True),
    sa.Column('last_reviewed_at', sa.DateTime(), nullable=True),
    sa.Column('next_review_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['hanzi_id'], ['hanzi.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'hanzi_id', name='uq_user_hanzi')
    )
    op.create_index(op.f('ix_user_hanzi_hanzi_id'), 'user_hanzi', ['hanzi_id'], unique=False)
    op.create_index(op.f('ix_user_hanzi_id'), 'user_hanzi', ['id'], unique=False)
    op.create_index(op.f('ix_user_hanzi_user_id'), 'user_hanzi', ['user_id'], unique=False)
    op.add_column('grammar_topics', sa.Column('category', sa.String(length=100), nullable=True))
    op.add_column('grammar_topics', sa.Column('difficulty', sa.String(length=20), nullable=True))
    op.add_column('hsk_levels', sa.Column('is_advanced_band', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('hsk_levels', 'is_advanced_band')
    op.drop_column('grammar_topics', 'difficulty')
    op.drop_column('grammar_topics', 'category')
    op.drop_index(op.f('ix_user_hanzi_user_id'), table_name='user_hanzi')
    op.drop_index(op.f('ix_user_hanzi_id'), table_name='user_hanzi')
    op.drop_index(op.f('ix_user_hanzi_hanzi_id'), table_name='user_hanzi')
    op.drop_table('user_hanzi')
    op.drop_index(op.f('ix_user_grammar_user_id'), table_name='user_grammar')
    op.drop_index(op.f('ix_user_grammar_topic_id'), table_name='user_grammar')
    op.drop_index(op.f('ix_user_grammar_id'), table_name='user_grammar')
    op.drop_table('user_grammar')
    op.drop_index(op.f('ix_hanzi_id'), table_name='hanzi')
    op.drop_index(op.f('ix_hanzi_hsk_level_id'), table_name='hanzi')
    op.drop_index(op.f('ix_hanzi_character'), table_name='hanzi')
    op.drop_table('hanzi')
    # ### end Alembic commands ###
