# Content data: vocabulary, grammar topics and starter lessons.
# Vocab format: (hsk_level, simplified, traditional, pinyin, meanings, word_type,
#                example, example_pinyin)
VOCAB = [
    (1, "我", None, "wǒ", "I, me", "pronoun", "我是学生。", "wǒ shì xuéshēng."),
    (1, "你", None, "nǐ", "you", "pronoun", "你好！", "nǐ hǎo!"),
    (1, "他", None, "tā", "he, him", "pronoun", "他是老师。", "tā shì lǎoshī."),
    (1, "她", None, "tā", "she, her", "pronoun", "她是医生。", "tā shì yīshēng."),
    (1, "好", None, "hǎo", "good, fine", "adjective", "很好。", "hěn hǎo."),
    (1, "不", None, "bù", "not, no", "adverb", "不去。", "bú qù."),
    (1, "是", None, "shì", "to be (am, is, are)", "verb", "我是中国人。", "wǒ shì Zhōngguórén."),
    (1, "吃", None, "chī", "to eat", "verb", "我吃米饭。", "wǒ chī mǐfàn."),
    (1, "喝", None, "hē", "to drink", "verb", "我喝水。", "wǒ hē shuǐ."),
    (1, "谢谢", None, "xièxie", "thank you", "verb", "谢谢！", "xièxie!"),
    (1, "叫", None, "jiào", "to be called", "verb", "我叫小明。", "wǒ jiào Xiǎomíng."),
    (1, "去", None, "qù", "to go", "verb", "去商店。", "qù shāngdiàn."),
    (1, "来", None, "lái", "to come", "verb", "来我家。", "lái wǒ jiā."),
    (1, "爱", None, "ài", "to love, to like", "verb", "我爱学习。", "wǒ ài xuéxí."),
    (1, "说", None, "shuō", "to speak, to say", "verb", "说中文。", "shuō Zhōngwén."),
    (1, "看", None, "kàn", "to look, to read, to watch", "verb", "看书。", "kàn shū."),
    (1, "听", None, "tīng", "to listen", "verb", "听音乐。", "tīng yīnyuè."),
    (1, "坐", None, "zuò", "to sit, to travel by", "verb", "坐火车。", "zuò huǒchē."),
    (1, "买", None, "mǎi", "to buy", "verb", "买苹果。", "mǎi píngguǒ."),
    (1, "钱", None, "qián", "money", "noun", "多少钱？", "duōshǎo qián?"),
    (1, "书", None, "shū", "book", "noun", "一本书。", "yì běn shū."),
    (1, "水", None, "shuǐ", "water", "noun", "一杯水。", "yì bēi shuǐ."),
    (1, "米饭", None, "mǐfàn", "cooked rice", "noun", "吃米饭。", "chī mǐfàn."),
    (1, "茶", None, "chá", "tea", "noun", "喝杯茶。", "hē bēi chá."),
    (1, "中国", None, "Zhōngguó", "China", "noun", "我去中国。", "wǒ qù Zhōngguó."),
    (1, "人", None, "rén", "person", "noun", "一个人。", "yí ge rén."),
    (1, "朋友", None, "péngyou", "friend", "noun", "我的朋友。", "wǒ de péngyou."),
    (1, "老师", None, "lǎoshī", "teacher", "noun", "李老师。", "Lǐ lǎoshī."),
    (1, "学生", None, "xuéshēng", "student", "noun", "我是学生。", "wǒ shì xuéshēng."),
    (1, "医生", None, "yīshēng", "doctor", "noun", "她是医生。", "tā shì yīshēng."),
    (1, "大", None, "dà", "big", "adjective", "很大的房间。", "hěn dà de fángjiān."),
    (1, "小", None, "xiǎo", "small", "adjective", "小狗。", "xiǎo gǒu."),
    (1, "多", None, "duō", "many, much, more", "adjective", "很多人。", "hěn duō rén."),
    (1, "少", None, "shǎo", "few, little", "adjective", "很少。", "hěn shǎo."),
    (1, "一", None, "yī", "one", "number", "一个。", "yí ge."),
    (1, "二", None, "èr", "two", "number", "两个人。", "liǎng ge rén."),
    (1, "三", None, "sān", "three", "number", "三个人。", "sān ge rén."),
    (1, "今天", None, "jīntiān", "today", "noun", "今天很好。", "jīntiān hěn hǎo."),
    (1, "明天", None, "míngtiān", "tomorrow", "noun", "明天见！", "míngtiān jiàn!"),
    (1, "现在", None, "xiànzài", "now", "noun", "现在几点了？", "xiànzài jǐ diǎn le?"),
    (1, "天气", None, "tiānqì", "weather", "noun", "今天天气好。", "jīntiān tiānqì hǎo."),
    (1, "东西", None, "dōngxi", "thing, stuff", "noun", "买点东西。", "mǎi diǎn dōngxi."),
    (1, "苹果", None, "píngguǒ", "apple", "noun", "吃苹果。", "chī píngguǒ."),
    (1, "西瓜", None, "xīguā", "watermelon", "noun", "一盘西瓜。", "yì pán xīguā."),
    (1, "牛肉面", None, "niúròumiàn", "beef noodles", "noun", "一碗牛肉面。", "yì wǎn niúròumiàn."),
    (1, "火车站", None, "huǒchēzhàn", "train station", "noun", "去火车站。", "qù huǒchēzhàn. "),
    (2, "商店", None, "shāngdiàn", "shop, store", "noun", "去商店买东西。", "qù shāngdiàn mǎi dōngxi."),
    (2, "医院", None, "yīyuàn", "hospital", "noun", "他在医院。", "tā zài yīyuàn."),
    (2, "大学", None, "dàxué", "university", "noun", "你上大学吗？", "nǐ shàng dàxué ma?"),
    (2, "觉得", None, "juéde", "to feel, to think", "verb", "我觉得很好。", "wǒ juéde hěn hǎo."),
    (2, "因为", None, "yīnwèi", "because", "conjunction", "因为下雨了。", "yīnwèi xià yǔ le."),
    (2, "所以", None, "suǒyǐ", "therefore", "conjunction", "所以我不去。", "suǒyǐ wǒ bú qù."),
]

# --- HSK accuracy pass: the sets above only covered 46/150 words at HSK1,
# 6/~150 at HSK2, and nothing at HSK3-6 despite the app modeling all six
# levels. These additions are real, well-established words from the old
# (2010-2021) HSK 1-6 word lists this app already targets (see HSK_LEVELS in
# seed_data.py -- its cumulative vocab targets of 150/300/600/1200/2500/5000
# are that standard's signature, not the newer 9-level HSK 3.0). No example
# sentences are attached (display-only field, unused by any scoring logic) --
# the priority here is getting the word/pinyin/meaning/level right, not prose.
VOCAB += [
    (1, "的", None, "de", "possessive/attributive particle", "particle", None, None),
    (1, "了", None, "le", "aspect particle (completed action)", "particle", None, None),
    (1, "吗", None, "ma", "question particle", "particle", None, None),
    (1, "呢", None, "ne", "question particle", "particle", None, None),
    (1, "这", None, "zhè", "this", "pronoun", None, None),
    (1, "那", None, "nà", "that", "pronoun", None, None),
    (1, "谁", None, "shéi", "who", "pronoun", None, None),
    (1, "什么", None, "shénme", "what", "pronoun", None, None),
    (1, "哪", None, "nǎ", "which", "pronoun", None, None),
    (1, "哪儿", None, "nǎr", "where", "pronoun", None, None),
    (1, "几", None, "jǐ", "how many (small numbers)", "pronoun", None, None),
    (1, "多少", None, "duōshao", "how many/much", "pronoun", None, None),
    (1, "怎么样", None, "zěnmeyàng", "how, how about", "pronoun", None, None),
    (1, "和", None, "hé", "and, with", "conjunction", None, None),
    (1, "在", None, "zài", "at, in, to be located at", "preposition", None, None),
    (1, "很", None, "hěn", "very", "adverb", None, None),
    (1, "太", None, "tài", "too, extremely", "adverb", None, None),
    (1, "都", None, "dōu", "all, both", "adverb", None, None),
    (1, "能", None, "néng", "can, to be able to", "verb", None, None),
    (1, "会", None, "huì", "can (learned skill), will", "verb", None, None),
    (1, "想", None, "xiǎng", "to want, to think", "verb", None, None),
    (1, "喜欢", None, "xǐhuan", "to like", "verb", None, None),
    (1, "学习", None, "xuéxí", "to study", "verb", None, None),
    (1, "学校", None, "xuéxiào", "school", "noun", None, None),
    (1, "工作", None, "gōngzuò", "to work, job", "verb", None, None),
    (1, "名字", None, "míngzi", "name", "noun", None, None),
    (1, "岁", None, "suì", "year of age", "measure word", None, None),
    (1, "年", None, "nián", "year", "noun", None, None),
    (1, "月", None, "yuè", "month", "noun", None, None),
    (1, "号", None, "hào", "day of month, number", "noun", None, None),
    (1, "点", None, "diǎn", "o'clock, point", "noun", None, None),
    (1, "分钟", None, "fēnzhōng", "minute", "noun", None, None),
    (1, "时候", None, "shíhou", "time, moment", "noun", None, None),
    (1, "上午", None, "shàngwǔ", "morning", "noun", None, None),
    (1, "下午", None, "xiàwǔ", "afternoon", "noun", None, None),
    (1, "中午", None, "zhōngwǔ", "noon", "noun", None, None),
    (1, "昨天", None, "zuótiān", "yesterday", "noun", None, None),
    (1, "星期", None, "xīngqī", "week", "noun", None, None),
    (1, "爸爸", None, "bàba", "dad", "noun", None, None),
    (1, "妈妈", None, "māma", "mom", "noun", None, None),
    (1, "儿子", None, "érzi", "son", "noun", None, None),
    (1, "女儿", None, "nǚ'ér", "daughter", "noun", None, None),
    (1, "家", None, "jiā", "home, family", "noun", None, None),
    (1, "同学", None, "tóngxué", "classmate", "noun", None, None),
    (1, "先生", None, "xiānsheng", "Mr., sir", "noun", None, None),
    (1, "小姐", None, "xiǎojiě", "Miss", "noun", None, None),
    (1, "猫", None, "māo", "cat", "noun", None, None),
    (1, "狗", None, "gǒu", "dog", "noun", None, None),
    (1, "杯子", None, "bēizi", "cup", "noun", None, None),
    (1, "桌子", None, "zhuōzi", "table", "noun", None, None),
    (1, "椅子", None, "yǐzi", "chair", "noun", None, None),
    (1, "电脑", None, "diànnǎo", "computer", "noun", None, None),
    (1, "电视", None, "diànshì", "television", "noun", None, None),
    (1, "电影", None, "diànyǐng", "movie", "noun", None, None),
    (1, "飞机", None, "fēijī", "airplane", "noun", None, None),
    (1, "出租车", None, "chūzūchē", "taxi", "noun", None, None),
    (1, "饭店", None, "fàndiàn", "restaurant, hotel", "noun", None, None),
    (1, "房间", None, "fángjiān", "room", "noun", None, None),
    (1, "衣服", None, "yīfu", "clothes", "noun", None, None),
    (1, "水果", None, "shuǐguǒ", "fruit", "noun", None, None),
    (1, "汉语", None, "Hànyǔ", "Chinese language", "noun", None, None),
    (1, "字", None, "zì", "character, word", "noun", None, None),
    (1, "本", None, "běn", "measure word for books", "measure word", None, None),
    (1, "块", None, "kuài", "yuan (colloquial), lump/piece", "measure word", None, None),
    (1, "元", None, "yuán", "yuan (currency)", "measure word", None, None),
    (1, "下雨", None, "xiàyǔ", "to rain", "verb", None, None),
    (1, "冷", None, "lěng", "cold", "adjective", None, None),
    (1, "热", None, "rè", "hot", "adjective", None, None),
    (1, "高兴", None, "gāoxìng", "happy", "adjective", None, None),
    (1, "漂亮", None, "piàoliang", "pretty", "adjective", None, None),
    (1, "忙", None, "máng", "busy", "adjective", None, None),
    (1, "新", None, "xīn", "new", "adjective", None, None),
    (1, "快", None, "kuài", "fast", "adjective", None, None),
    (1, "慢", None, "màn", "slow", "adjective", None, None),
    (1, "早", None, "zǎo", "early", "adjective", None, None),
    (1, "上", None, "shàng", "on, above, to go to", "noun", None, None),
    (1, "下", None, "xià", "under, below, next", "noun", None, None),
    (1, "里", None, "lǐ", "inside", "noun", None, None),
    (1, "前面", None, "qiánmiàn", "in front", "noun", None, None),
    (1, "后面", None, "hòumiàn", "behind", "noun", None, None),
    (1, "这儿", None, "zhèr", "here", "pronoun", None, None),
    (1, "那儿", None, "nàr", "there", "pronoun", None, None),
    (1, "一起", None, "yìqǐ", "together", "adverb", None, None),
    (1, "再见", None, "zàijiàn", "goodbye", "phrase", None, None),
    (1, "没关系", None, "méi guānxi", "it's okay, never mind", "phrase", None, None),
    (1, "不客气", None, "bú kèqi", "you're welcome", "phrase", None, None),
    (1, "对不起", None, "duìbuqǐ", "sorry", "phrase", None, None),
    (1, "请", None, "qǐng", "please", "verb", None, None),
    (1, "打电话", None, "dǎ diànhuà", "to make a phone call", "verb", None, None),
    (1, "回", None, "huí", "to return", "verb", None, None),
    (1, "开", None, "kāi", "to open, to drive", "verb", None, None),
    (1, "睡觉", None, "shuìjiào", "to sleep", "verb", None, None),
    (1, "写", None, "xiě", "to write", "verb", None, None),
    (1, "读", None, "dú", "to read aloud", "verb", None, None),
    (1, "认识", None, "rènshi", "to know, to recognize", "verb", None, None),
    (1, "看见", None, "kànjiàn", "to see", "verb", None, None),
    (1, "住", None, "zhù", "to live, to reside", "verb", None, None),
    (1, "做", None, "zuò", "to do, to make", "verb", None, None),
]
VOCAB += [
    (2, "再", None, "zài", "again", "adverb", None, None),
    (2, "已经", None, "yǐjīng", "already", "adverb", None, None),
    (2, "但是", None, "dànshì", "but", "conjunction", None, None),
    (2, "可是", None, "kěshì", "but", "conjunction", None, None),
    (2, "还", None, "hái", "still, also", "adverb", None, None),
    (2, "还是", None, "háishi", "or, still", "conjunction", None, None),
    (2, "就", None, "jiù", "then, just", "adverb", None, None),
    (2, "只", None, "zhǐ", "only", "adverb", None, None),
    (2, "一点儿", None, "yìdiǎnr", "a little", "measure word", None, None),
    (2, "一些", None, "yìxiē", "some", "measure word", None, None),
    (2, "每", None, "měi", "every", "pronoun", None, None),
    (2, "每天", None, "měitiān", "every day", "noun", None, None),
    (2, "次", None, "cì", "time, occurrence", "measure word", None, None),
    (2, "一直", None, "yìzhí", "always, straight", "adverb", None, None),
    (2, "一定", None, "yídìng", "certainly", "adverb", None, None),
    (2, "一样", None, "yíyàng", "the same", "adjective", None, None),
    (2, "别", None, "bié", "don't", "adverb", None, None),
    (2, "完", None, "wán", "to finish", "verb", None, None),
    (2, "懂", None, "dǒng", "to understand", "verb", None, None),
    (2, "告诉", None, "gàosu", "to tell", "verb", None, None),
    (2, "帮助", None, "bāngzhù", "to help", "verb", None, None),
    (2, "让", None, "ràng", "to let, to make", "verb", None, None),
    (2, "给", None, "gěi", "to give, for", "verb", None, None),
    (2, "送", None, "sòng", "to give (a gift), to send off", "verb", None, None),
    (2, "拿", None, "ná", "to take, to hold", "verb", None, None),
    (2, "放", None, "fàng", "to put, to place", "verb", None, None),
    (2, "关", None, "guān", "to close", "verb", None, None),
    (2, "开始", None, "kāishǐ", "to start", "verb", None, None),
    (2, "准备", None, "zhǔnbèi", "to prepare", "verb", None, None),
    (2, "需要", None, "xūyào", "to need", "verb", None, None),
    (2, "应该", None, "yīnggāi", "should", "verb", None, None),
    (2, "可以", None, "kěyǐ", "can, may", "verb", None, None),
    (2, "比", None, "bǐ", "compared to", "preposition", None, None),
    (2, "更", None, "gèng", "even more", "adverb", None, None),
    (2, "最", None, "zuì", "most", "adverb", None, None),
    (2, "非常", None, "fēicháng", "extremely", "adverb", None, None),
    (2, "希望", None, "xīwàng", "to hope", "verb", None, None),
    (2, "累", None, "lèi", "tired", "adjective", None, None),
    (2, "病", None, "bìng", "sick, illness", "noun", None, None),
    (2, "眼睛", None, "yǎnjing", "eyes", "noun", None, None),
    (2, "耳朵", None, "ěrduo", "ears", "noun", None, None),
    (2, "嘴", None, "zuǐ", "mouth", "noun", None, None),
    (2, "鼻子", None, "bízi", "nose", "noun", None, None),
    (2, "手", None, "shǒu", "hand", "noun", None, None),
    (2, "脚", None, "jiǎo", "foot", "noun", None, None),
    (2, "身体", None, "shēntǐ", "body, health", "noun", None, None),
    (2, "唱歌", None, "chànggē", "to sing", "verb", None, None),
    (2, "跳舞", None, "tiàowǔ", "to dance", "verb", None, None),
    (2, "运动", None, "yùndòng", "exercise, sport", "noun", None, None),
    (2, "游泳", None, "yóuyǒng", "to swim", "verb", None, None),
    (2, "篮球", None, "lánqiú", "basketball", "noun", None, None),
    (2, "足球", None, "zúqiú", "soccer", "noun", None, None),
    (2, "音乐", None, "yīnyuè", "music", "noun", None, None),
    (2, "画", None, "huà", "to draw, painting", "verb", None, None),
    (2, "旅游", None, "lǚyóu", "to travel", "verb", None, None),
    (2, "火车", None, "huǒchē", "train", "noun", None, None),
    (2, "机场", None, "jīchǎng", "airport", "noun", None, None),
    (2, "自行车", None, "zìxíngchē", "bicycle", "noun", None, None),
    (2, "公共汽车", None, "gōnggòng qìchē", "bus", "noun", None, None),
    (2, "地铁", None, "dìtiě", "subway", "noun", None, None),
    (2, "街", None, "jiē", "street", "noun", None, None),
    (2, "城市", None, "chéngshì", "city", "noun", None, None),
    (2, "公园", None, "gōngyuán", "park", "noun", None, None),
    (2, "图书馆", None, "túshūguǎn", "library", "noun", None, None),
    (2, "教室", None, "jiàoshì", "classroom", "noun", None, None),
    (2, "办公室", None, "bàngōngshì", "office", "noun", None, None),
    (2, "洗手间", None, "xǐshǒujiān", "restroom", "noun", None, None),
    (2, "超市", None, "chāoshì", "supermarket", "noun", None, None),
    (2, "宾馆", None, "bīnguǎn", "hotel", "noun", None, None),
    (2, "饭馆", None, "fànguǎn", "restaurant", "noun", None, None),
    (2, "鸡蛋", None, "jīdàn", "egg", "noun", None, None),
    (2, "面条", None, "miàntiáo", "noodles", "noun", None, None),
    (2, "面包", None, "miànbāo", "bread", "noun", None, None),
    (2, "牛奶", None, "niúnǎi", "milk", "noun", None, None),
    (2, "咖啡", None, "kāfēi", "coffee", "noun", None, None),
    (2, "鱼", None, "yú", "fish", "noun", None, None),
    (2, "肉", None, "ròu", "meat", "noun", None, None),
    (2, "颜色", None, "yánsè", "color", "noun", None, None),
    (2, "红", None, "hóng", "red", "adjective", None, None),
    (2, "黄", None, "huáng", "yellow", "adjective", None, None),
    (2, "黑", None, "hēi", "black", "adjective", None, None),
    (2, "白", None, "bái", "white", "adjective", None, None),
    (2, "穿", None, "chuān", "to wear", "verb", None, None),
    (2, "鞋", None, "xié", "shoes", "noun", None, None),
    (2, "高", None, "gāo", "tall, high", "adjective", None, None),
    (2, "生日", None, "shēngrì", "birthday", "noun", None, None),
    (2, "礼物", None, "lǐwù", "gift", "noun", None, None),
    (2, "过", None, "guò", "to pass, to celebrate", "verb", None, None),
    (2, "唱", None, "chàng", "to sing", "verb", None, None),
    (2, "笑", None, "xiào", "to laugh, to smile", "verb", None, None),
    (2, "难过", None, "nánguò", "sad", "adjective", None, None),
    (2, "有意思", None, "yǒu yìsi", "interesting", "phrase", None, None),
    (2, "有名", None, "yǒumíng", "famous", "adjective", None, None),
    (2, "难", None, "nán", "difficult", "adjective", None, None),
    (2, "问题", None, "wèntí", "problem, question", "noun", None, None),
    (2, "意思", None, "yìsi", "meaning", "noun", None, None),
    (2, "楼", None, "lóu", "building, floor", "noun", None, None),
    (2, "中间", None, "zhōngjiān", "middle", "noun", None, None),
    (2, "旁边", None, "pángbiān", "beside", "noun", None, None),
    (2, "左边", None, "zuǒbian", "left side", "noun", None, None),
    (2, "右边", None, "yòubian", "right side", "noun", None, None),
    (2, "一边", None, "yìbiān", "one side", "noun", None, None),
    (2, "从", None, "cóng", "from", "preposition", None, None),
    (2, "向", None, "xiàng", "towards", "preposition", None, None),
    (2, "远", None, "yuǎn", "far", "adjective", None, None),
    (2, "近", None, "jìn", "near", "adjective", None, None),
    (2, "回来", None, "huílai", "to come back", "verb", None, None),
    (2, "出去", None, "chūqu", "to go out", "verb", None, None),
    (2, "进", None, "jìn", "to enter", "verb", None, None),
    (2, "出", None, "chū", "to exit, out", "verb", None, None),
    (2, "上班", None, "shàngbān", "to go to work", "verb", None, None),
    (2, "下班", None, "xiàbān", "to get off work", "verb", None, None),
    (2, "上课", None, "shàngkè", "to attend class", "verb", None, None),
    (2, "下课", None, "xiàkè", "class ends", "verb", None, None),
    (2, "考试", None, "kǎoshì", "exam", "noun", None, None),
    (2, "作业", None, "zuòyè", "homework", "noun", None, None),
    (2, "汉字", None, "Hànzì", "Chinese character", "noun", None, None),
    (2, "练习", None, "liànxí", "to practice", "verb", None, None),
    (2, "复习", None, "fùxí", "to review", "verb", None, None),
    (2, "教", None, "jiāo", "to teach", "verb", None, None),
    (2, "服务员", None, "fúwùyuán", "waiter/waitress", "noun", None, None),
    (2, "护士", None, "hùshi", "nurse", "noun", None, None),
    (2, "阿姨", None, "āyí", "auntie", "noun", None, None),
    (2, "叔叔", None, "shūshu", "uncle", "noun", None, None),
    (2, "哥哥", None, "gēge", "older brother", "noun", None, None),
    (2, "姐姐", None, "jiějie", "older sister", "noun", None, None),
    (2, "弟弟", None, "dìdi", "younger brother", "noun", None, None),
    (2, "妹妹", None, "mèimei", "younger sister", "noun", None, None),
    (2, "爷爷", None, "yéye", "grandfather (paternal)", "noun", None, None),
    (2, "奶奶", None, "nǎinai", "grandmother (paternal)", "noun", None, None),
    (2, "孩子", None, "háizi", "child", "noun", None, None),
    (2, "男", None, "nán", "male", "adjective", None, None),
    (2, "女", None, "nǚ", "female", "adjective", None, None),
    (2, "男人", None, "nánrén", "man", "noun", None, None),
    (2, "女人", None, "nǚrén", "woman", "noun", None, None),
    (2, "国家", None, "guójiā", "country", "noun", None, None),
    (2, "地方", None, "dìfang", "place", "noun", None, None),
]
VOCAB += [
    (3, "爱好", None, "àihào", "hobby", "noun", None, None),
    (3, "安静", None, "ānjìng", "quiet", "adjective", None, None),
    (3, "班", None, "bān", "class", "noun", None, None),
    (3, "办法", None, "bànfǎ", "method", "noun", None, None),
    (3, "半", None, "bàn", "half", "number", None, None),
    (3, "帮忙", None, "bāngmáng", "to help", "verb", None, None),
    (3, "包", None, "bāo", "bag, to wrap", "noun", None, None),
    (3, "保护", None, "bǎohù", "to protect", "verb", None, None),
    (3, "报纸", None, "bàozhǐ", "newspaper", "noun", None, None),
    (3, "北方", None, "běifāng", "north", "noun", None, None),
    (3, "本子", None, "běnzi", "notebook", "noun", None, None),
    (3, "比较", None, "bǐjiào", "relatively, to compare", "adverb", None, None),
    (3, "比赛", None, "bǐsài", "competition", "noun", None, None),
    (3, "必须", None, "bìxū", "must", "adverb", None, None),
    (3, "变化", None, "biànhuà", "change", "noun", None, None),
    (3, "别人", None, "biéren", "other people", "pronoun", None, None),
    (3, "冰箱", None, "bīngxiāng", "refrigerator", "noun", None, None),
    (3, "不但", None, "búdàn", "not only", "conjunction", None, None),
    (3, "才", None, "cái", "only then, just", "adverb", None, None),
    (3, "菜单", None, "càidān", "menu", "noun", None, None),
    (3, "参加", None, "cānjiā", "to participate", "verb", None, None),
    (3, "差", None, "chà", "short of, poor", "adjective", None, None),
    (3, "场", None, "chǎng", "measure word (events)", "measure word", None, None),
    (3, "成功", None, "chénggōng", "success", "verb", None, None),
    (3, "成绩", None, "chéngjì", "grade, score", "noun", None, None),
    (3, "迟到", None, "chídào", "to be late", "verb", None, None),
    (3, "出现", None, "chūxiàn", "to appear", "verb", None, None),
    (3, "除了", None, "chúle", "except, besides", "preposition", None, None),
    (3, "春", None, "chūn", "spring", "noun", None, None),
    (3, "春节", None, "Chūnjié", "Spring Festival", "noun", None, None),
    (3, "词典", None, "cídiǎn", "dictionary", "noun", None, None),
    (3, "打扫", None, "dǎsǎo", "to clean", "verb", None, None),
    (3, "打算", None, "dǎsuàn", "to plan", "verb", None, None),
    (3, "带", None, "dài", "to bring, to carry", "verb", None, None),
    (3, "担心", None, "dānxīn", "to worry", "verb", None, None),
    (3, "蛋糕", None, "dàngāo", "cake", "noun", None, None),
    (3, "当然", None, "dāngrán", "of course", "adverb", None, None),
    (3, "地图", None, "dìtú", "map", "noun", None, None),
    (3, "灯", None, "dēng", "lamp, light", "noun", None, None),
    (3, "等", None, "děng", "to wait", "verb", None, None),
    (3, "低", None, "dī", "low", "adjective", None, None),
    (3, "第一", None, "dìyī", "first", "number", None, None),
    (3, "电梯", None, "diàntī", "elevator", "noun", None, None),
    (3, "电子邮件", None, "diànzǐ yóujiàn", "email", "noun", None, None),
    (3, "掉", None, "diào", "to drop, to fall", "verb", None, None),
    (3, "冬", None, "dōng", "winter", "noun", None, None),
    (3, "动物", None, "dòngwù", "animal", "noun", None, None),
    (3, "短信", None, "duǎnxìn", "text message", "noun", None, None),
    (3, "段", None, "duàn", "section, paragraph", "measure word", None, None),
    (3, "锻炼", None, "duànliàn", "to exercise", "verb", None, None),
    (3, "对话", None, "duìhuà", "dialogue", "noun", None, None),
    (3, "多么", None, "duōme", "how (exclamatory)", "adverb", None, None),
    (3, "而且", None, "érqiě", "moreover", "conjunction", None, None),
    (3, "发", None, "fā", "to send, to emit", "verb", None, None),
    (3, "发烧", None, "fāshāo", "to have a fever", "verb", None, None),
    (3, "发生", None, "fāshēng", "to happen", "verb", None, None),
    (3, "发现", None, "fāxiàn", "to discover", "verb", None, None),
    (3, "翻译", None, "fānyì", "to translate", "verb", None, None),
    (3, "方便", None, "fāngbiàn", "convenient", "adjective", None, None),
    (3, "方法", None, "fāngfǎ", "method", "noun", None, None),
    (3, "方向", None, "fāngxiàng", "direction", "noun", None, None),
    (3, "放心", None, "fàngxīn", "to feel at ease", "verb", None, None),
    (3, "放假", None, "fàngjià", "to have a holiday", "verb", None, None),
    (3, "干净", None, "gānjìng", "clean", "adjective", None, None),
    (3, "感冒", None, "gǎnmào", "to catch a cold", "verb", None, None),
    (3, "感觉", None, "gǎnjué", "to feel, feeling", "noun", None, None),
    (3, "刚", None, "gāng", "just now", "adverb", None, None),
    (3, "刚才", None, "gāngcái", "just now", "noun", None, None),
    (3, "各", None, "gè", "each", "pronoun", None, None),
    (3, "够", None, "gòu", "enough", "adjective", None, None),
    (3, "故事", None, "gùshi", "story", "noun", None, None),
    (3, "挂", None, "guà", "to hang", "verb", None, None),
    (3, "关系", None, "guānxì", "relationship", "noun", None, None),
    (3, "关心", None, "guānxīn", "to care about", "verb", None, None),
    (3, "关于", None, "guānyú", "about, regarding", "preposition", None, None),
    (3, "光", None, "guāng", "light", "noun", None, None),
    (3, "逛", None, "guàng", "to stroll", "verb", None, None),
    (3, "果汁", None, "guǒzhī", "juice", "noun", None, None),
    (3, "过去", None, "guòqù", "the past", "noun", None, None),
    (3, "害怕", None, "hàipà", "to be afraid", "verb", None, None),
    (3, "寒假", None, "hánjià", "winter vacation", "noun", None, None),
    (3, "护照", None, "hùzhào", "passport", "noun", None, None),
    (3, "花", None, "huā", "flower, to spend", "noun", None, None),
    (3, "回答", None, "huídá", "to answer", "verb", None, None),
    (3, "会议", None, "huìyì", "meeting", "noun", None, None),
    (3, "或者", None, "huòzhě", "or", "conjunction", None, None),
    (3, "机会", None, "jīhuì", "opportunity", "noun", None, None),
    (3, "记得", None, "jìde", "to remember", "verb", None, None),
    (3, "继续", None, "jìxù", "to continue", "verb", None, None),
    (3, "寄", None, "jì", "to mail", "verb", None, None),
    (3, "假", None, "jià", "vacation, holiday", "noun", None, None),
    (3, "价格", None, "jiàgé", "price", "noun", None, None),
    (3, "检查", None, "jiǎnchá", "to check, to inspect", "verb", None, None),
    (3, "简单", None, "jiǎndān", "simple", "adjective", None, None),
    (3, "建议", None, "jiànyì", "suggestion", "noun", None, None),
    (3, "健康", None, "jiànkāng", "health, healthy", "adjective", None, None),
    (3, "讲", None, "jiǎng", "to speak, to explain", "verb", None, None),
    (3, "节", None, "jié", "festival, section", "measure word", None, None),
    (3, "节目", None, "jiémù", "program, show", "noun", None, None),
    (3, "节日", None, "jiérì", "festival, holiday", "noun", None, None),
    (3, "结果", None, "jiéguǒ", "result", "noun", None, None),
    (3, "结婚", None, "jiéhūn", "to marry", "verb", None, None),
    (3, "结束", None, "jiéshù", "to end", "verb", None, None),
    (3, "解决", None, "jiějué", "to solve", "verb", None, None),
    (3, "经常", None, "jīngcháng", "often", "adverb", None, None),
    (3, "经过", None, "jīngguò", "to pass by", "verb", None, None),
    (3, "经理", None, "jīnglǐ", "manager", "noun", None, None),
    (3, "警察", None, "jǐngchá", "police", "noun", None, None),
    (3, "举行", None, "jǔxíng", "to hold (an event)", "verb", None, None),
    (3, "决定", None, "juédìng", "to decide", "verb", None, None),
    (3, "咳嗽", None, "késou", "to cough", "verb", None, None),
    (3, "可爱", None, "kě'ài", "cute", "adjective", None, None),
    (3, "客人", None, "kèrén", "guest", "noun", None, None),
    (3, "空气", None, "kōngqì", "air", "noun", None, None),
    (3, "空调", None, "kōngtiáo", "air conditioner", "noun", None, None),
    (3, "口", None, "kǒu", "mouth, measure word", "noun", None, None),
    (3, "苦", None, "kǔ", "bitter", "adjective", None, None),
    (3, "裤子", None, "kùzi", "pants", "noun", None, None),
    (3, "筷子", None, "kuàizi", "chopsticks", "noun", None, None),
    (3, "困", None, "kùn", "sleepy", "adjective", None, None),
    (3, "困难", None, "kùnnan", "difficulty", "noun", None, None),
    (3, "拉", None, "lā", "to pull", "verb", None, None),
    (3, "辣", None, "là", "spicy", "adjective", None, None),
    (3, "离开", None, "líkāi", "to leave", "verb", None, None),
    (3, "脸", None, "liǎn", "face", "noun", None, None),
    (3, "凉快", None, "liángkuai", "pleasantly cool", "adjective", None, None),
    (3, "了解", None, "liǎojiě", "to understand, to find out", "verb", None, None),
    (3, "邻居", None, "línjū", "neighbor", "noun", None, None),
    (3, "零", None, "líng", "zero", "number", None, None),
    (3, "另外", None, "lìngwài", "additionally, other", "adverb", None, None),
    (3, "留", None, "liú", "to stay, to leave behind", "verb", None, None),
    (3, "流行", None, "liúxíng", "popular, to be in fashion", "adjective", None, None),
    (3, "旅行", None, "lǚxíng", "to travel", "verb", None, None),
    (3, "麻烦", None, "máfan", "troublesome, to bother", "adjective", None, None),
    (3, "马", None, "mǎ", "horse", "noun", None, None),
    (3, "马路", None, "mǎlù", "road", "noun", None, None),
    (3, "满意", None, "mǎnyì", "satisfied", "adjective", None, None),
    (3, "美丽", None, "měilì", "beautiful", "adjective", None, None),
    (3, "民族", None, "mínzú", "ethnic group", "noun", None, None),
    (3, "目前", None, "mùqián", "currently", "noun", None, None),
]
VOCAB += [
    (4, "不管", None, "bùguǎn", "regardless of", "conjunction", None, None),
    (4, "部分", None, "bùfen", "part, portion", "noun", None, None),
    (4, "超过", None, "chāoguò", "to exceed", "verb", None, None),
    (4, "从来", None, "cónglái", "always, never (with negation)", "adverb", None, None),
    (4, "到处", None, "dàochù", "everywhere", "adverb", None, None),
    (4, "调查", None, "diàochá", "to investigate", "verb", None, None),
    (4, "丢", None, "diū", "to lose, to throw", "verb", None, None),
    (4, "发展", None, "fāzhǎn", "to develop", "verb", None, None),
    (4, "法律", None, "fǎlǜ", "law", "noun", None, None),
    (4, "丰富", None, "fēngfù", "abundant", "adjective", None, None),
    (4, "否则", None, "fǒuzé", "otherwise", "conjunction", None, None),
    (4, "符合", None, "fúhé", "to conform to", "verb", None, None),
    (4, "复杂", None, "fùzá", "complicated", "adjective", None, None),
    (4, "敢", None, "gǎn", "to dare", "verb", None, None),
    (4, "各种", None, "gèzhǒng", "various kinds", "pronoun", None, None),
    (4, "工资", None, "gōngzī", "salary", "noun", None, None),
    (4, "关键", None, "guānjiàn", "key, crucial point", "noun", None, None),
    (4, "管理", None, "guǎnlǐ", "to manage", "verb", None, None),
    (4, "广播", None, "guǎngbō", "broadcast", "noun", None, None),
    (4, "广告", None, "guǎnggào", "advertisement", "noun", None, None),
    (4, "规定", None, "guīdìng", "regulation, to stipulate", "noun", None, None),
    (4, "国际", None, "guójì", "international", "adjective", None, None),
    (4, "过程", None, "guòchéng", "process", "noun", None, None),
    (4, "好处", None, "hǎochù", "benefit", "noun", None, None),
    (4, "好像", None, "hǎoxiàng", "to seem like", "adverb", None, None),
    (4, "互联网", None, "hùliánwǎng", "internet", "noun", None, None),
    (4, "几乎", None, "jīhū", "almost", "adverb", None, None),
    (4, "既然", None, "jìrán", "since (given that)", "conjunction", None, None),
    (4, "记者", None, "jìzhě", "journalist", "noun", None, None),
    (4, "技术", None, "jìshù", "technology, skill", "noun", None, None),
    (4, "假如", None, "jiǎrú", "if, supposing", "conjunction", None, None),
    (4, "坚持", None, "jiānchí", "to persist", "verb", None, None),
    (4, "降低", None, "jiàngdī", "to lower", "verb", None, None),
    (4, "接受", None, "jiēshòu", "to accept", "verb", None, None),
    (4, "接着", None, "jiēzhe", "then, next", "adverb", None, None),
    (4, "解释", None, "jiěshì", "to explain", "verb", None, None),
    (4, "尽管", None, "jǐnguǎn", "although", "conjunction", None, None),
    (4, "精彩", None, "jīngcǎi", "brilliant, wonderful", "adjective", None, None),
    (4, "经历", None, "jīnglì", "experience", "noun", None, None),
    (4, "经验", None, "jīngyàn", "experience (accumulated)", "noun", None, None),
    (4, "竟然", None, "jìngrán", "unexpectedly", "adverb", None, None),
    (4, "竞争", None, "jìngzhēng", "competition", "verb", None, None),
    (4, "究竟", None, "jiūjìng", "after all, exactly", "adverb", None, None),
    (4, "拒绝", None, "jùjué", "to refuse", "verb", None, None),
    (4, "距离", None, "jùlí", "distance", "noun", None, None),
    (4, "考虑", None, "kǎolǜ", "to consider", "verb", None, None),
    (4, "看法", None, "kànfǎ", "viewpoint", "noun", None, None),
    (4, "恐怕", None, "kǒngpà", "I'm afraid that", "adverb", None, None),
    (4, "来自", None, "láizì", "to come from", "verb", None, None),
    (4, "理解", None, "lǐjiě", "to understand", "verb", None, None),
    (4, "厉害", None, "lìhai", "formidable, terrible", "adjective", None, None),
    (4, "例如", None, "lìrú", "for example", "conjunction", None, None),
    (4, "连", None, "lián", "even (emphasis)", "preposition", None, None),
    (4, "目的", None, "mùdì", "purpose", "noun", None, None),
]
VOCAB += [
    (5, "把握", None, "bǎwò", "to grasp, certainty", "verb", None, None),
    (5, "摆", None, "bǎi", "to place, to put", "verb", None, None),
    (5, "包括", None, "bāokuò", "to include", "verb", None, None),
    (5, "悲观", None, "bēiguān", "pessimistic", "adjective", None, None),
    (5, "背景", None, "bèijǐng", "background", "noun", None, None),
    (5, "比例", None, "bǐlì", "proportion", "noun", None, None),
    (5, "彼此", None, "bǐcǐ", "each other", "pronoun", None, None),
    (5, "弊病", None, "bìbìng", "malady, drawback", "noun", None, None),
    (5, "边疆", None, "biānjiāng", "border area", "noun", None, None),
    (5, "补充", None, "bǔchōng", "to supplement", "verb", None, None),
    (5, "不安", None, "bù'ān", "uneasy", "adjective", None, None),
    (5, "不得了", None, "bùdéliǎo", "extremely, terrible", "adjective", None, None),
    (5, "采访", None, "cǎifǎng", "to interview", "verb", None, None),
    (5, "采取", None, "cǎiqǔ", "to adopt (a measure)", "verb", None, None),
    (5, "参考", None, "cānkǎo", "to consult, reference", "verb", None, None),
    (5, "差距", None, "chājù", "gap, disparity", "noun", None, None),
    (5, "产品", None, "chǎnpǐn", "product", "noun", None, None),
    (5, "成分", None, "chéngfèn", "component", "noun", None, None),
    (5, "成就", None, "chéngjiù", "achievement", "noun", None, None),
    (5, "成立", None, "chénglì", "to establish", "verb", None, None),
    (5, "充分", None, "chōngfèn", "sufficient", "adjective", None, None),
    (5, "重大", None, "zhòngdà", "major, significant", "adjective", None, None),
    (5, "除非", None, "chúfēi", "unless", "conjunction", None, None),
    (5, "传统", None, "chuántǒng", "tradition", "noun", None, None),
    (5, "创造", None, "chuàngzào", "to create", "verb", None, None),
    (5, "刺激", None, "cìjī", "stimulus, to stimulate", "verb", None, None),
    (5, "从事", None, "cóngshì", "to be engaged in", "verb", None, None),
    (5, "措施", None, "cuòshī", "measure, step", "noun", None, None),
    (5, "答应", None, "dāying", "to agree, to promise", "verb", None, None),
    (5, "大概", None, "dàgài", "probably", "adverb", None, None),
]
VOCAB += [
    (6, "哀求", None, "āiqiú", "to plead", "verb", None, None),
    (6, "癌症", None, "áizhèng", "cancer", "noun", None, None),
    (6, "昂贵", None, "ángguì", "costly", "adjective", None, None),
    (6, "案例", None, "ànlì", "case (example)", "noun", None, None),
    (6, "暗示", None, "ànshì", "to hint", "verb", None, None),
    (6, "熬夜", None, "áoyè", "to stay up late", "verb", None, None),
    (6, "把关", None, "bǎguān", "to guard a pass, to check", "verb", None, None),
    (6, "摆脱", None, "bǎituō", "to break free from", "verb", None, None),
    (6, "颁布", None, "bānbù", "to promulgate", "verb", None, None),
    (6, "半途而废", None, "bàntú'érfèi", "to give up halfway", "phrase", None, None),
    (6, "包庇", None, "bāobì", "to shield, to cover for", "verb", None, None),
    (6, "薄弱", None, "bóruò", "weak, frail", "adjective", None, None),
    (6, "本能", None, "běnnéng", "instinct", "noun", None, None),
    (6, "鄙视", None, "bǐshì", "to despise", "verb", None, None),
    (6, "弊端", None, "bìduān", "malpractice, abuse", "noun", None, None),
    (6, "必然", None, "bìrán", "inevitable", "adjective", None, None),
    (6, "变故", None, "biàngù", "unforeseen event", "noun", None, None),
    (6, "辨别", None, "biànbié", "to distinguish", "verb", None, None),
    (6, "辩护", None, "biànhù", "to defend (legally)", "verb", None, None),
    (6, "标准", None, "biāozhǔn", "standard", "noun", None, None),
    (6, "鄙夷", None, "bǐyí", "to despise", "verb", None, None),
    (6, "濒临", None, "bīnlín", "to be on the verge of", "verb", None, None),
    (6, "并存", None, "bìngcún", "to coexist", "verb", None, None),
    (6, "波折", None, "bōzhé", "twists and turns", "noun", None, None),
    (6, "博大精深", None, "bódàjīngshēn", "broad and profound", "phrase", None, None),
]

# Grammar format: (hsk_level, title, pattern, explanation, examples, order)
GRAMMAR = [
    (1, "是 — to be", "A 是 B",
     "Links a subject to a noun phrase. Like 'to be' in English.",
     "我是学生。 / 他是老师。", 1),
    (1, "吗 — yes/no question", "……吗？",
     "Adding 吗 to the end of a statement turns it into a yes/no question.",
     "你好吗？ / 你是学生吗？", 2),
    (1, "不 — negation", "不 + verb/adjective",
     "不 negates a verb or adjective.",
     "我不去。 / 不好。", 3),
    (1, "的 — possession", "A 的 B",
     "的 links a possessor to what they own (my, your, ...).",
     "我的朋友 / 我的书", 4),
    (1, "个 — measure word", "数 + 个 + 名词",
     "个 is a general measure word used before nouns with numbers.",
     "一个人 / 一个苹果", 5),
    (1, "有 — to have / there is", "有 / 没有",
     "有 expresses having or existence; 没有 negates it.",
     "我有一个朋友。 / 没有时间。", 6),
    (2, "因为……所以…… — because/therefore", "因为 A，所以 B",
     "Gives a reason and its result.",
     "因为下雨，所以我不去。", 1),
    (2, "了 — completed action", "V + 了",
     "了 after a verb marks a completed action.",
     "我吃了饭。 / 他来了。", 2),
    (2, "都 — all", "都 + V",
     "都 means 'all' or 'both'.",
     "我们都去。/ 他们都是学生。", 3),
]

# --- HSK accuracy pass: HSK1/2 had a solid but thin core; HSK3/4 had zero
# grammar points despite lessons/pet-teacher content spanning those levels.
# These are real, standard patterns from the old-standard syllabus.
GRAMMAR += [
    (1, "在 — location / progressive", "在 + 地点 / 在 + V", "在 marks where something is, or (before a verb) that an action is in progress.", "我在家。 / 我在吃饭。", 7),
    (1, "这/那 — this/that", "这 + 名词 / 那 + 名词", "这 points to something near the speaker, 那 to something farther away.", "这是我的书。 / 那是他的车。", 8),
    (1, "呢 — follow-up question", "……呢？", "呢 after a noun asks 'what about ...?' as a follow-up.", "我很好，你呢？", 9),
    (1, "会/能 — ability, possibility", "会/能 + verb", "会 is for learned skills, 能 for general ability or permission.", "我会说中文。 / 我能来。", 10),
    (1, "一点儿 — a little", "V/Adj + 一点儿", "一点儿 softens an adjective or adds a small amount to a verb.", "便宜一点儿。 / 喝一点儿水。", 11),
    (1, "几/多少 — asking quantity", "几 + measure word (small numbers) / 多少 (any size)", "几 expects an answer under ~10 and needs a measure word; 多少 works for any number.", "你家有几口人？ / 多少钱？", 12),
]
GRAMMAR += [
    (2, "比 — comparison", "A 比 B + adjective", "比 compares two things directly along one quality.", "今天比昨天冷。", 4),
    (2, "正在/在 — progressive aspect", "正在/在 + V (+呢)", "Marks an action happening right now.", "他正在吃饭。 / 我在看书呢。", 5),
    (2, "得 (děi) — must", "得 + verb", "得 expresses obligation, similar to 应该 but more colloquial.", "我得走了。", 6),
    (2, "太……了 — excessively", "太 + adjective + 了", "Expresses that something is too much of a quality.", "太贵了！", 7),
    (2, "一下 — brief action", "V + 一下", "Softens a verb, suggesting a quick, casual action.", "你看一下。 / 等一下。", 8),
]
GRAMMAR += [
    (3, "把字句 — the 把 construction", "主语 + 把 + 宾语 + V + 其他成分", "把 moves the object before the verb to emphasize what happens to it.", "我把书放在桌子上。", 1),
    (3, "被字句 — the passive with 被", "受事 + 被 (+ 施事) + V", "被 marks the passive voice — the subject receives the action.", "杯子被他打破了。", 2),
    (3, "虽然……但是…… — although/but", "虽然 A，但是 B", "Concedes A, then contrasts it with B.", "虽然很累，但是很高兴。", 3),
    (3, "一边……一边…… — simultaneous actions", "一边 A，一边 B", "Describes two actions happening at the same time.", "他一边吃饭一边看电视。", 4),
    (3, "越来越 — increasingly", "越来越 + adjective/verb", "Describes a quality that keeps increasing over time.", "天气越来越冷了。", 5),
    (3, "除了……以外 — besides/except", "除了 A 以外，(还/都) B", "Excludes or adds to A when talking about B.", "除了咖啡以外，我什么都喝。", 6),
]
GRAMMAR += [
    (4, "不但……而且…… — not only/but also", "不但 A，而且 B", "Adds a stronger second point on top of the first.", "他不但聪明，而且努力。", 1),
    (4, "尽管……还是…… — despite/still", "尽管 A，还是 B", "Concedes a strong obstacle A, then B still happens.", "尽管很难，他还是坚持学习。", 2),
    (4, "只要……就…… — as long as", "只要 A，就 B", "States a sufficient condition for B.", "只要努力，就能成功。", 3),
    (4, "无论……都…… — no matter what", "无论 A，都 B", "B holds true regardless of A.", "无论多忙，他都锻炼身体。", 4),
]

# Lesson format: (hsk_level, title, summary, content, lesson_type, order, skills)
LESSONS = [
    (1, "Greetings", "Start every conversation with 你好.",
     "你好 (nǐ hǎo) = hello.\n早上好 (zǎoshang hǎo) = good morning.\n"
     "晚上好 (wǎnshang hǎo) = good evening.\n"
     "你好吗？(nǐ hǎo ma?) = How are you? — Answer: 我很好，谢谢。",
     "lesson", 1, ["speaking", "listening"]),
    (1, "Introduce yourself", "Say your name and where you are from.",
     "我叫…… (wǒ jiào ...) = My name is ...\n我是……人。 = I am from ...\n"
     "很高兴认识你。 (hěn gāoxìng rènshi nǐ) = Nice to meet you.",
     "lesson", 2, ["speaking", "grammar"]),
    (1, "Numbers 1–10", "Count and understand prices.",
     "一 yī, 二 èr, 三 sān, 四 sì, 五 wǔ, 六 liù, 七 qī, 八 bā, 九 jiǔ, 十 shí.\n"
     "十 is 10. Eleven is 十一 (shí yī), twenty is 二十 (èr shí).",
     "lesson", 3, ["vocabulary", "reading"]),
    (1, "Asking questions", "Form basic questions with 吗 and 什么.",
     "Add 吗 to turn a sentence into a question.\n"
     "什么 (shénme) = what. 谁 (shéi) = who. 哪儿 (nǎr) = where.\n"
     "你去哪儿？ (nǐ qù nǎr?) = Where are you going?",
     "lesson", 4, ["grammar", "speaking"]),
    (1, "Food words", "Order food and drinks.",
     "米饭 mǐfàn = rice, 茶 chá = tea, 水 shuǐ = water,\n"
     "牛肉面 niúròumiàn = beef noodles, 苹果 píngguǒ = apple.\n"
     "一碗牛肉面，谢谢。 = One bowl of beef noodles, please.",
     "lesson", 5, ["vocabulary", "reading"]),
    (2, "Because & therefore", "Explain reasons with 因为……所以……",
     "因为 (yīnwèi) = because. 所以 (suǒyǐ) = therefore.\n"
     "因为下雨，所以我不去。 = Because it's raining, I'm not going.",
     "lesson", 1, ["grammar", "writing"]),
    (2, "Completed actions", "Mark the past with 了",
     "Put 了 after a verb to show the action is done.\n"
     "我吃了饭。 = I ate (the food). 他来了。 = He came.",
     "lesson", 2, ["grammar", "reading"]),
]