# Content data: vocabulary, grammar topics and starter lessons.
# Vocab format: (hsk_level, simplified, traditional, pinyin, meanings, word_type,
#                example, example_pinyin)
VOCAB = [
    (1, "我", None, "wǒ", "I, me", "pronoun", "我是学生。", "wǒ shì xuéshēng."),
    (1, "你", None, "nǐ", "you", "pronoun", "你好！", "nǐ hǎo!"),
    (1, "他", None, "tā", "he, him", "pronoun", "他是老师。", "tā shì lǎoshī."),
    (1, "她", None, "tā", "she, her", "pronoun", "她是医生。", "tā shì yīshēng."),
    (1, "好", None, "hǎo", "good, fine", "adjective", "很好。", "hěn hǎo."),
    (1, "不", None, "bù", "not, no", "adverb", "不去。", "bú qù."),
    (1, "是", None, "shì", "to be (am, is, are)", "verb", "我是中国人。", "wǒ shì Zhōngguórén."),
    (1, "吃", None, "chī", "to eat", "verb", "我吃米饭。", "wǒ chī mǐfàn."),
    (1, "喝", None, "hē", "to drink", "verb", "我喝水。", "wǒ hē shuǐ."),
    (1, "谢", None, "xiè", "thanks", "verb", "谢谢！", "xièxie!"),
    (1, "叫", None, "jiào", "to be called", "verb", "我叫小明。", "wǒ jiào Xiǎomíng."),
    (1, "去", None, "qù", "to go", "verb", "去商店。", "qù shāngdiàn."),
    (1, "来", None, "lái", "to come", "verb", "来我家。", "lái wǒ jiā."),
    (1, "爱", None, "ài", "to love, to like", "verb", "我爱学习。", "wǒ ài xuéxí."),
    (1, "说", None, "shuō", "to speak, to say", "verb", "说中文。", "shuō Zhōngwén."),
    (1, "看", None, "kàn", "to look, to read, to watch", "verb", "看书。", "kàn shū."),
    (1, "听", None, "tīng", "to listen", "verb", "听音乐。", "tīng yīnyuè."),
    (1, "坐", None, "zuò", "to sit, to travel by", "verb", "坐火车。", "zuò huǒchē."),
    (1, "买", None, "mǎi", "to buy", "verb", "买苹果。", "mǎi píngguǒ."),
    (1, "钱", None, "qián", "money", "noun", "多少钱？", "duōshǎo qián?"),
    (1, "书", None, "shū", "book", "noun", "一本书。", "yì běn shū."),
    (1, "水", None, "shuǐ", "water", "noun", "一杯水。", "yì bēi shuǐ."),
    (1, "米饭", None, "mǐfàn", "cooked rice", "noun", "吃米饭。", "chī mǐfàn."),
    (1, "茶", None, "chá", "tea", "noun", "喝杯茶。", "hē bēi chá."),
    (1, "中国", None, "Zhōngguó", "China", "noun", "我去中国。", "wǒ qù Zhōngguó."),
    (1, "人", None, "rén", "person", "noun", "一个人。", "yí ge rén."),
    (1, "朋友", None, "péngyou", "friend", "noun", "我的朋友。", "wǒ de péngyou."),
    (1, "老师", None, "lǎoshī", "teacher", "noun", "李老师。", "Lǐ lǎoshī."),
    (1, "学生", None, "xuéshēng", "student", "noun", "我是学生。", "wǒ shì xuéshēng."),
    (1, "医生", None, "yīshēng", "doctor", "noun", "她是医生。", "tā shì yīshēng."),
    (1, "大", None, "dà", "big", "adjective", "很大的房间。", "hěn dà de fángjiān."),
    (1, "小", None, "xiǎo", "small", "adjective", "小狗。", "xiǎo gǒu."),
    (1, "多", None, "duō", "many, much, more", "adjective", "很多人。", "hěn duō rén."),
    (1, "少", None, "shǎo", "few, little", "adjective", "很少。", "hěn shǎo."),
    (1, "一", None, "yī", "one", "number", "一个。", "yí ge."),
    (1, "二", None, "èr", "two", "number", "两个人。", "liǎng ge rén."),
    (1, "三", None, "sān", "three", "number", "三个人。", "sān ge rén."),
    (1, "今天", None, "jīntiān", "today", "noun", "今天很好。", "jīntiān hěn hǎo."),
    (1, "明天", None, "míngtiān", "tomorrow", "noun", "明天见！", "míngtiān jiàn!"),
    (1, "现在", None, "xiànzài", "now", "noun", "现在几点了？", "xiànzài jǐ diǎn le?"),
    (1, "天气", None, "tiānqì", "weather", "noun", "今天天气好。", "jīntiān tiānqì hǎo."),
    (1, "东西", None, "dōngxi", "thing, stuff", "noun", "买点东西。", "mǎi diǎn dōngxi."),
    (1, "苹果", None, "píngguǒ", "apple", "noun", "吃苹果。", "chī píngguǒ."),
    (1, "西瓜", None, "xīguā", "watermelon", "noun", "一盘西瓜。", "yì pán xīguā."),
    (1, "牛肉面", None, "niúròumiàn", "beef noodles", "noun", "一碗牛肉面。", "yì wǎn niúròumiàn."),
    (1, "火车站", None, "huǒchēzhàn", "train station", "noun", "去火车站。", "qù huǒchēzhàn. "),
    (2, "商店", None, "shāngdiàn", "shop, store", "noun", "去商店买东西。", "qù shāngdiàn mǎi dōngxi."),
    (2, "医院", None, "yīyuàn", "hospital", "noun", "他在医院。", "tā zài yīyuàn."),
    (2, "大学", None, "dàxué", "university", "noun", "你上大学吗？", "nǐ shàng dàxué ma?"),
    (2, "觉得", None, "juéde", "to feel, to think", "verb", "我觉得很好。", "wǒ juéde hěn hǎo."),
    (2, "因为", None, "yīnwèi", "because", "conjunction", "因为下雨了。", "yīnwèi xià yǔ le."),
    (2, "所以", None, "suǒyǐ", "therefore", "conjunction", "所以我不去。", "suǒyǐ wǒ bú qù."),
]

# Grammar format: (hsk_level, title, pattern, explanation, examples, order)
GRAMMAR = [
    (1, "是 — to be", "A 是 B",
     "Links a subject to a noun phrase. Like 'to be' in English.",
     "我是学生。 / 他是老师。", 1),
    (1, "吗 — yes/no question", "……吗？",
     "Adding 吗 to the end of a statement turns it into a yes/no question.",
     "你好吗？ / 你是学生吗？", 2),
    (1, "不 — negation", "不 + verb/adjective",
     "不 negates a verb or adjective.",
     "我不去。 / 不好。", 3),
    (1, "的 — possession", "A 的 B",
     "的 links a possessor to what they own (my, your, ...).",
     "我的朋友 / 我的书", 4),
    (1, "个 — measure word", "数 + 个 + 名词",
     "个 is a general measure word used before nouns with numbers.",
     "一个人 / 一个苹果", 5),
    (1, "有 — to have / there is", "有 / 没有",
     "有 expresses having or existence; 没有 negates it.",
     "我有一个朋友。 / 没有时间。", 6),
    (2, "因为……所以…… — because/therefore", "因为 A，所以 B",
     "Gives a reason and its result.",
     "因为下雨，所以我不去。", 1),
    (2, "了 — completed action", "V + 了",
     "了 after a verb marks a completed action.",
     "我吃了饭。 / 他来了。", 2),
    (2, "都 — all", "都 + V",
     "都 means 'all' or 'both'.",
     "我们都去。/ 他们都是学生。", 3),
]

# Lesson format: (hsk_level, title, summary, content, lesson_type, order, skills)
LESSONS = [
    (1, "Greetings", "Start every conversation with 你好.",
     "你好 (nǐ hǎo) = hello.\n早上好 (zǎoshang hǎo) = good morning.\n"
     "晚上好 (wǎnshang hǎo) = good evening.\n"
     "你好吗？(nǐ hǎo ma?) = How are you? — Answer: 我很好，谢谢。",
     "lesson", 1, ["speaking", "listening"]),
    (1, "Introduce yourself", "Say your name and where you are from.",
     "我叫…… (wǒ jiào ...) = My name is ...\n我是……人。 = I am from ...\n"
     "很高兴认识你。 (hěn gāoxìng rènshi nǐ) = Nice to meet you.",
     "lesson", 2, ["speaking", "grammar"]),
    (1, "Numbers 1–10", "Count and understand prices.",
     "一 yī, 二 èr, 三 sān, 四 sì, 五 wǔ, 六 liù, 七 qī, 八 bā, 九 jiǔ, 十 shí.\n"
     "十 is 10. Eleven is 十一 (shí yī), twenty is 二十 (èr shí).",
     "lesson", 3, ["vocabulary", "reading"]),
    (1, "Asking questions", "Form basic questions with 吗 and 什么.",
     "Add 吗 to turn a sentence into a question.\n"
     "什么 (shénme) = what. 谁 (shéi) = who. 哪儿 (nǎr) = where.\n"
     "你去哪儿？ (nǐ qù nǎr?) = Where are you going?",
     "lesson", 4, ["grammar", "speaking"]),
    (1, "Food words", "Order food and drinks.",
     "米饭 mǐfàn = rice, 茶 chá = tea, 水 shuǐ = water,\n"
     "牛肉面 niúròumiàn = beef noodles, 苹果 píngguǒ = apple.\n"
     "一碗牛肉面，谢谢。 = One bowl of beef noodles, please.",
     "lesson", 5, ["vocabulary", "reading"]),
    (2, "Because & therefore", "Explain reasons with 因为……所以……",
     "因为 (yīnwèi) = because. 所以 (suǒyǐ) = therefore.\n"
     "因为下雨，所以我不去。 = Because it's raining, I'm not going.",
     "lesson", 1, ["grammar", "writing"]),
    (2, "Completed actions", "Mark the past with 了",
     "Put 了 after a verb to show the action is done.\n"
     "我吃了饭。 = I ate (the food). 他来了。 = He came.",
     "lesson", 2, ["grammar", "reading"]),
]