# Content data: the Chinese World (locations, NPCs, scenarios, dialogues, cases)
# and missions.

LOCATIONS = [
    ("home", "Home", "home", "🏠", "#fbbf24",
     "Your home base, where your animal companion waits.",
     1, 0, 12, 78),
    ("city-street", "City Street", "street", "🛣️", "#94a3b8",
     "The heartbeat of the city. Ask locals for directions.",
     1, 30, 30, 60),
    ("restaurant", "Restaurant", "food", "🍜", "#f97316",
     "Order food, pay the bill and survive the busy lunch rush.",
     1, 40, 48, 72),
    ("shop", "Shop", "shop", "🏪", "#38bdf8",
     "Buy and sell. Haggling is optional, speaking is not.",
     2, 50, 62, 82),
    ("university", "University", "education", "🎓", "#a78bfa",
     "Meet classmates and professors for deeper discussions.",
     3, 60, 45, 30),
    ("hospital", "Hospital", "health", "🏥", "#f43f5e",
     "Describe symptoms and understand a doctor's advice.",
     4, 65, 22, 42),
    ("train-station", "Train Station", "travel", "🚉", "#22c55e",
     "Buy tickets, find platforms, and catch your train.",
     4, 75, 72, 22),
    ("hotel", "Hotel", "travel", "🏨", "#f472b6",
     "Check in, ask for amenities, and handle any trouble.",
     5, 80, 34, 12),
    ("airport", "Airport", "travel", "✈️", "#a3e635",
     "Check in for your flight and follow spoken announcements.",
     6, 85, 88, 40),
]

NPCS = [
    ("home", "奶奶", "Grandma", "Family elder", "",
     "A warm grandmother who speaks slowly and clearly.",
     "kind, loves to feed you", "slow, warm, simple words"),
    ("city-street", "老李", "Cyclist", "Friendly local", "",
     "A chatty local who knows every street.",
     "talkative, helpful", "fast, cheerful, uses directions"),
    ("restaurant", "服务员", "Waitress", "Dandan", "",
     "A busy waitress who repeats orders aloud.",
     "efficient, polite, slightly rushed", "polite, quick, echoes your order"),
    ("restaurant", "老板", "Owner", "Uncle Chen", "",
     "Oversees the noodles. Very sharp about the money.",
     "sharp, honest, observant", "direct, numbers-heavy"),
    ("shop", "店主", "Shopkeeper", "Ms. Wang", "",
     "Runs a small fruit shop full of local gossip.",
     "cheerful, shrewd", "friendly, price-focused"),
    ("university", "同学", "Classmate", "Xiao Ming", "",
     "A fellow student happy to practice.",
     "enthusiastic, fast-talking", "casual, fast"),
    ("hospital", "医生", "Doctor", "Dr. Liu", "",
     "Calm and precise. Needs to understand your symptoms.",
     "calm, precise, caring", "clear, careful, medical"),
    ("train-station", "检票员", "Ticket inspector", "Mr. Zhao", "",
     "Checks tickets and directs passengers.",
     "serious but fair", "loud, official, numbers-heavy"),
    ("hotel", "前台", "Receptionist", "Miss Li", "",
     "Handles check-ins and special requests.",
     "professional, helpful", "polite, standard phrases"),
    ("airport", "地勤", "Ground agent", "Ms. Chen", "",
     "Announces departures and guides passengers.",
     "efficient, clear announcements", "loud announcements, very clear"),
]

# Scenario dict format:
#   slug, location, scenario_type, title, description, min_hsk_level, difficulty,
#   requires_voice, is_case, order_index, case_data or None, dialogues, choices
SCENARIOS = [
    {
        "slug": "greet-grandma",
        "location": "home",
        "scenario_type": "conversation",
        "title": "Saying Hello to Grandma",
        "description": "Walk into the house and greet Grandma properly.",
        "min_hsk_level": 1, "difficulty": 1, "requires_voice": True,
        "is_case": False, "order_index": 1, "case_data": None,
        "npc": "奶奶",
        "dialogues": [
            {"turn": 0, "speaker": "npc", "text": "你回来啦！饿了吗？",
             "pinyin": "nǐ huílái la! è le ma?", "english": "You're back! Hungry?"},
            {"turn": 1, "speaker": "learner", "text": "",
             "prompt": "Say: I'm not hungry, thank you.",
             "expected_keywords": ["不饿", "谢谢"], "requires_voice": True,
             "reaction_correct": "奶奶：好，那先喝口水吧。",
             "reaction_incorrect": "奶奶：啊？听不清楚，再说一遍？"},
            {"turn": 2, "speaker": "npc", "text": "你叫什么名字？",
             "pinyin": "nǐ jiào shénme míngzi?", "english": "What's your name?"},
            {"turn": 3, "speaker": "learner", "text": "",
             "prompt": "Say: My name is ... and I am glad to see you.",
             "expected_keywords": ["我", "叫", "高兴", "见"], "requires_voice": True,
             "reaction_correct": "奶奶：好孩子！",
             "reaction_incorrect": "奶奶：再说一遍，慢一点。"},
        ],
    },
    {
        "slug": "ordering-noodles",
        "location": "restaurant",
        "scenario_type": "conversation",
        "title": "Ordering Beef Noodles",
        "description": "Order a bowl of beef noodles and pay the bill.",
        "min_hsk_level": 1, "difficulty": 1, "requires_voice": True,
        "is_case": False, "order_index": 1, "case_data": None,
        "npc": "服务员",
        "dialogues": [
            {"turn": 0, "speaker": "npc", "text": "欢迎光临！请问吃什么？",
             "pinyin": "huānyíng guānglín! qǐngwèn chī shénme?",
             "english": "Welcome! What would you like?"},
            {"turn": 1, "speaker": "learner", "text": "",
             "prompt": "Say: I would like a bowl of beef noodles.",
             "expected_keywords": ["牛肉面", "一碗", "要"], "requires_voice": True,
             "reaction_correct": "服务员：一碗牛肉面，马上就来！",
             "reaction_incorrect": "服务员：不好意思，请再说一遍？"},
            {"turn": 2, "speaker": "npc", "text": "好的！一共二十五元。",
             "pinyin": "hǎo de! yígòng èrshíwǔ yuán.", "english": "OK! Altogether 25 yuan."},
            {"turn": 3, "speaker": "learner", "text": "",
             "prompt": "Say: Here you are. Thank you.",
             "expected_keywords": ["给", "钱", "谢谢"], "requires_voice": True,
             "reaction_correct": "服务员：谢谢，慢走！",
             "reaction_incorrect": "服务员：嗯？我没听清。"},
        ],
        "choices": [
            {"turn": 2, "label": "太贵了，便宜一点吗？", "response_text": "老板：行吧，给你二十块！",
             "is_best": False, "feedback": "Politely asking to lower the price. Try it next time.", "next_turn": 3},
            {"turn": 2, "label": "好的，给你钱。", "response_text": "服务员：谢谢！",
             "is_best": True, "feedback": "Simple and correct. Well done.", "next_turn": 3},
        ],
    },
    {
        "slug": "asking-directions",
        "location": "city-street",
        "scenario_type": "mission",
        "title": "Asking for Directions",
        "description": "Find the train station by asking a local.",
        "min_hsk_level": 1, "difficulty": 1, "requires_voice": True,
        "is_case": False, "order_index": 1, "case_data": None,
        "npc": "老李",
        "dialogues": [
            {"turn": 0, "speaker": "npc", "text": "你好！去哪儿啊？",
             "pinyin": "nǐ hǎo! qù nǎr a?", "english": "Hello! Where are you going?"},
            {"turn": 1, "speaker": "learner", "text": "",
             "prompt": "Say: Excuse me, where is the train station?",
             "expected_keywords": ["火车站", "在", "哪儿"], "requires_voice": True,
             "reaction_correct": "老李：往前走，然后往右拐。",
             "reaction_incorrect": "老李：再说一遍？"},
            {"turn": 2, "speaker": "npc", "text": "往前走，然后往右拐。",
             "pinyin": "wǎng qián zǒu, ránhòu wǎng yòu guǎi.",
             "english": "Walk forward, then turn right."},
            {"turn": 3, "speaker": "learner", "text": "",
             "prompt": "Say: Thank you so much!",
             "expected_keywords": ["谢谢", "你"], "requires_voice": True,
             "reaction_correct": "老李：不客气！",
             "reaction_incorrect": "老李：你说什么？"},
        ],
    },
    {
        "slug": "buying-fruit",
        "location": "shop",
        "scenario_type": "conversation",
        "title": "Buying Fruit at the Shop",
        "description": "Buy some apples and watermelons without overpaying.",
        "min_hsk_level": 2, "difficulty": 1, "requires_voice": False,
        "is_case": False, "order_index": 1, "case_data": None,
        "npc": "店主",
        "dialogues": [
            {"turn": 0, "speaker": "npc", "text": "要什么水果？今天的苹果特别甜。",
             "pinyin": "yào shénme shuǐguǒ? jīntiān de píngguǒ tèbié tián.",
             "english": "What fruit? Today's apples are especially sweet."},
            {"turn": 1, "speaker": "learner", "text": "",
             "prompt": "Say: I want two apples and one watermelon, how much?",
             "expected_keywords": ["苹果", "西瓜", "两", "多少钱"], "requires_voice": False,
             "reaction_correct": "店主：两个苹果一个西瓜，一共二十块。",
             "reaction_incorrect": "店主：能再说一次吗？"},
            {"turn": 2, "speaker": "npc", "text": "两个苹果一个西瓜，一共二十块。",
             "pinyin": "liǎng ge píngguǒ yí ge xīguā, yígòng èrshí kuài.",
             "english": "Two apples and a watermelon, 20 yuan total."},
            {"turn": 3, "speaker": "learner", "text": "",
             "prompt": "Say: Okay, please give me two apples and one watermelon.",
             "expected_keywords": ["好", "苹果", "西瓜"], "requires_voice": False,
             "reaction_correct": "店主：" + "给你，欢迎再来！",
             "reaction_incorrect": "店主：" + "什么？再说一遍？"},
        ],
    },
    {
        "slug": "the-missing-bill",
        "location": "restaurant",
        "scenario_type": "case",
        "title": "Case: The Missing Bill",
        "description": "Uncle Chen insists the customer paid only 10 yuan. The customer says they paid 25. Who is right?",
        "min_hsk_level": 2, "difficulty": 2, "requires_voice": True,
        "is_case": True, "order_index": 2,
        "case_data": {
            "clues": [
                "老板说：他给了我十块钱。",
                "顾客说：我给了他二十五块钱。",
                "服务员说：我听到顾客说“多少钱？”，老板说“二十五元”。",
                "收银机里有十块、一块和五块的零钱。",
            ],
            "solution_kws": ["二十五", "25", "customer", "顾客", "老板错"],
            "hint": "Compare what the waitress heard with what the owner claims.",
        },
        "npc": "老板",
        "dialogues": [
            {"turn": 0, "speaker": "npc", "text": "他吃完了面，说一共二十五元，他给了我十块！",
             "pinyin": "tā chīwán le miàn, shuō yígòng èrshíwǔ yuán, tā gěi le wǒ shí kuài!",
             "english": "He finished his noodles, the total was 25 yuan, he gave me 10!"},
            {"turn": 1, "speaker": "learner", "text": "",
             "prompt": "Say: How much did the waitress say the noodles cost?",
             "expected_keywords": ["服务员", "说", "二十五"], "requires_voice": True,
             "reaction_correct": "顾客：她说一共二十五元！",
             "reaction_incorrect": "老板：应该是二十五元，他少给了！"},
            {"turn": 2, "speaker": "learner", "text": "",
             "prompt": "Say: I think the customer is right, he paid 25.",
             "expected_keywords": ["顾客", "对", "二十五"], "requires_voice": True,
             "reaction_correct": "老板：啊……也许是我记错了！",
             "reaction_incorrect": "老板：你说什么？"},
        ],
    },
]

MISSIONS = [
    ("greet-day", "speak", "A Spoken Hello", "Complete the 'Saying Hello to Grandma' scenario.",
     1, 50, 10, 1, "greet-grandma"),
    ("first-order", "speak", "Order Like a Local", "Complete 'Ordering Beef Noodles' using your voice.",
     1, 60, 15, 1, "ordering-noodles"),
    ("find-way", "speak", "City Navigator", "Ask a local for directions to the train station.",
     1, 60, 10, 1, "asking-directions"),
    ("fruit-shop", "conversation", "Fruit Bargain", "Complete the fruit shop conversation for the first time.",
     2, 70, 15, 1, "buying-fruit"),
    ("solve-case", "case", "Detective Work", "Solve the case of the missing bill.",
     2, 100, 25, 1, "the-missing-bill"),
    ("listen-drill", "listening", "Listen Quick", "Complete 3 voice listening turns today.",
     1, 40, 5, 3, None),
    ("first-duel", "duel", "Prove Yourself", "Win your first DNA Duel.",
     1, 45, 10, 1, None),
    ("word-collector", "vocab", "Word Collector", "Review 10 vocabulary cards.",
     1, 55, 10, 10, None),
    ("teach-your-friend", "teach", "Turn the Tables", "Catch and correct your companion's mistake in Pet Teacher Mode.",
     1, 50, 10, 1, None),
    ("directions-master", "conversation", "Getting Around", "Complete 'Asking Directions' as a full conversation.",
     1, 60, 10, 1, "asking-directions"),
    ("case-streak", "case", "Repeat Detective", "Solve 2 Chinese Cases.",
     2, 120, 30, 2, None),
]

ACHIEVEMENTS = [
    ("first_voice", "First Spoken Conversation", "Complete your first voice turn.", "🎙️", "voice", {"type": "voice_count", "target": 1}),
    ("tone_master", "Tone Master", "Reach 80 tone accuracy across voice attempts.", "🎵", "voice", {"type": "avg_tones", "target": 80}),
    ("restaurant_survivor", "Restaurant Survivor", "Complete the ordering-noodles scenario.", "🍜", "world", {"type": "scenario", "target": "ordering-noodles"}),
    ("case_solver", "Case Solver", "Solve your first Chinese case.", "🕵️", "world", {"type": "case_count", "target": 1}),
    ("streak_7", "7-Day Streak", "Keep a 7-day learning streak.", "🔥", "habit", {"type": "streak", "target": 7}),
    ("hsk2_mastery", "HSK 2 Mastery", "Reach 80% mastery on HSK 2 skills.", "🏮", "hsk", {"type": "hsk", "target": 2, "mastery": 80}),
    ("duel_win", "First Duel Victory", "Win your first DNA Duel.", "⚔️", "social", {"type": "duel_wins", "target": 1}),
    ("words_100", "100 Words Mastered", "Master 100 vocabulary words.", "💯", "vocabulary", {"type": "vocab_mastered", "target": 100}),
    ("bond_3", "Bonded Companion", "Reach bond level 3 with your animal.", "🪻", "animal", {"type": "bond_level", "target": 3}),
    ("mistakes_10", "Mistake Hunter", "Master 10 recorded mistakes.", "🎯", "habit", {"type": "mistakes_mastered", "target": 10}),
    ("world_4", "City Explorer", "Unlock 4 locations.", "🗺️", "world", {"type": "locations_unlocked", "target": 4}),
    ("first_mission", "First Mission", "Complete your first mission.", "📜", "general", {"type": "mission_count", "target": 1}),
    ("pet_teacher_5", "Patient Teacher", "Teach your companion 5 grammar rules.", "🧑‍🏫", "animal", {"type": "taught_count", "target": 5}),
    ("xp_500", "Rising Star", "Earn 500 total XP from quests and missions.", "⭐", "general", {"type": "total_xp", "target": 500}),
]