# Content data: animal roster, HSK levels, learning skills.
# Animal tuple format:
#   (slug, name, species, accent, description, personality, tone_style,
#    preferred_mechanics, special_ability, traits,
#    energy, humor, patience, strictness, catchphrase, chat_style)
ANIMALS = [
    (
        "fox", "Fox", "Vulpes vulpes", "#f97316",
        "Quick-witted and playful. Loves speed, riddles and word puzzles.",
        "Clever, quick, a little mischievous.",
        "Short, snappy sentences. Loves rhymes and brain teasers.",
        "Speed quizzes, word puzzles, timed reviews.",
        "Quick Paws: reaction-speed challenges score +10%.",
        "clever, quick, mischievous", 90, 80, 40, 30,
        "Wanna play a word game?", "fast, playful, puzzle-driven",
    ),
    (
        "wolf", "Wolf", "Canis lupus", "#94a3b8",
        "Brave and driven. Hunts difficult missions and long quests.",
        "Loyal, intense, mission-focused.",
        "Direct, motivating, rarely jokes around.",
        "Missions, hard challenges, streaks.",
        "Pack Leader: mission rewards +20%.",
        "loyal, intense, driven", 80, 20, 60, 90,
        "The pack expects nothing less.", "motivational, direct",
    ),
    (
        "snake", "Snake", "Python bivittatus", "#22c55e",
        "Patient and precise. A master of memory and character recognition.",
        "Calm, patient, always observing.",
        "Measured, wise, speaks in short calm lines.",
        "Character drills, spaced repetition memory.",
        "Memory Coil: spaced-repetition intervals improve 2x.",
        "calm, precise, observant", 30, 10, 100, 60,
        "Slow and steady memorizes the character.", "calm, wise, minimal",
    ),
    (
        "cat", "Cat", "Felis catus", "#a78bfa",
        "Gentle and sensitive. Best for listening and calm practice.",
        "Cozy, independent, soothing.",
        "Warm, quiet, reassuring.",
        "Listening, pronunciation, relaxing sessions.",
        "Clear Ear: listening scores +10%.",
        "gentle, calm, independent", 40, 40, 80, 20,
        "Purr. Take your time.", "warm, soothing",
    ),
    (
        "dog", "Dog", "Canis familiaris", "#fbbf24",
        "Loyal and encouraging. Your everyday training buddy.",
        "Friendly, loyal, always cheering you on.",
        "Enthusiastic, repetitive praise.",
        "Daily practice, streaks, vocabulary.",
        "Cheerleader: daily quests reward +10%.",
        "friendly, loyal, cheerful", 85, 70, 70, 30,
        "Good job! Again! Good job!", "enthusiastic, repetitive",
    ),
    (
        "tiger", "Tiger", "Panthera tigris", "#f97316",
        "Fierce and focused. Thrives on challenging grammar and duels.",
        "Strong, ambitious, fearless.",
        "Bold, challenging, inspiring.",
        "Duels, hard grammar, cases.",
        "Fierce Roar: duel scoring +10%.",
        "strong, ambitious, fierce", 90, 30, 50, 85,
        "Show me your strength.", "bold, challenging",
    ),
    (
        "rabbit", "Rabbit", "Oryctolagus cuniculus", "#f472b6",
        "Bouncy and optimistic. Lifts you up after mistakes.",
        "Hopeful, cute, resilient.",
        "Soft, cheerful, forgiving.",
        "Mistake recovery, gentle reviews.",
        "Bounce Back: mistakes recover 2x faster.",
        "bouncy, optimistic, forgiving", 70, 75, 85, 15,
        "You tripped! Hop up again!", "cheerful, forgiving",
    ),
    (
        "bird", "Bird", "Passer domesticus", "#38bdf8",
        "Light and musical. Perfect for tones and speaking practice.",
        "Melodic, curious, chatty.",
        "Sings phrases, loves tones.",
        "Tones, speaking, voice.",
        "Perfect Pitch: tone scores +10%.",
        "musical, curious, chatty", 60, 60, 50, 40,
        "Tone check, tone check!", "musical, chatty",
    ),
    (
        "capybara", "Capybara", "Hydrochoerus hydrochaeris", "#a16207",
        "Ultra relaxed. No stress, just steady progress.",
        "Zen, calm, unshakeable.",
        "Slow, peaceful, minimal words.",
        "Casual practice, low-pressure sessions.",
        "Zen Flow: no streak pressure, calm mode.",
        "zen, calm, steady", 15, 35, 100, 5,
        "No rush. Chomp. Continue.", "zen, minimal",
    ),
    (
        "panther", "Panther", "Panthera pardus", "#64748b",
        "Mysterious and sharp. Excels at detective cases.",
        "Mysterious, analytical, silent.",
        "Quiet, probing questions.",
        "Cases, contradictions, logic.",
        "Night Vision: case insight +20%.",
        "mysterious, analytical, silent", 50, 15, 75, 55,
        "Something doesn't add up...", "probing, mysterious",
    ),
    (
        "sheep", "Sheep", "Ovis aries", "#e2e8f0",
        "Soft and steady. Reinforces everything until it sticks.",
        "Gentle, dedicated, repetitive-but-kind.",
        "Warm repetition, gentle reminders.",
        "Review, repetition, vocabulary mastery.",
        "Rumination: review sessions +25% retention.",
        "gentle, steady, dedicated", 25, 30, 95, 25,
        "Again is okay. Let's chew it once more.", "gentle, repetitive",
    ),
    # Original companions, preserved and upgraded.
    (
        "panda", "Panda", "Ailuropoda melanoleuca", "#10b981",
        "A calm and friendly companion that loves bamboo and slow steady progress.",
        "Relaxed, friendly, reassuring.", "Calm and warm.",
        "Balanced practice.", "Bamboo Snack: bonus coins for completed reviews.",
        "relaxed, friendly, calm", 40, 45, 90, 20,
        "One step at a time.", "calm, warm",
    ),
    (
        "red-panda", "Red Panda", "Ailurus fulgens", "#ef4444",
        "A curious little companion great at spotting new words.",
        "Curious, shy, delighted by new vocabulary.",
        "Eager whispers of new words.",
        "Vocabulary discovery.", "Word Sniff: finds forgotten words for review.",
        "curious, shy, delighted", 55, 55, 65, 15,
        "What's this word?!", "curious, eager",
    ),
    (
        "phoenix", "Phoenix", "Phoenix mythicus", "#f87171",
        "A wise companion that rises after every mistake.",
        "Wise, resilient, poetic.", "Poetic, philosophical, warm.",
        "Mistake recovery, mastery.", "Rebirth: failed sessions turn into double XP.",
        "wise, resilient, poetic", 70, 25, 70, 50,
        "From every mistake, we rise.", "poetic, wise",
    ),
    (
        "monkey", "Monkey", "Macaca mulatta", "#b45309",
        "Playful and full of energy. Turns every lesson into a game.",
        "Playful, curious, a joker.",
        "Silly jokes, quick games, lots of cheering.",
        "Mini-games, conversation, fun challenges.",
        "Banana Bonus: 5 correct answers in a row give bonus coins.",
        "playful, curious, funny", 95, 95, 35, 20,
        "Ooh ooh! Let's make this fun!", "playful, energetic, joking",
    ),
    (
        "koala", "Koala", "Phascolarctos cinereus", "#9ca3af",
        "Sleepy and gentle. Perfect for short, cozy study sessions.",
        "Relaxed, gentle, huggable.",
        "Soft, slow, very kind words.",
        "Short sessions, listening, gentle reviews.",
        "Eucalyptus Nap: even a 5-minute session keeps your streak alive.",
        "relaxed, gentle, cozy", 20, 40, 95, 10,
        "Mmm... small steps, big hugs.", "sleepy, soft, kind",
    ),
    (
        "elephant", "Elephant", "Loxodonta africana", "#60a5fa",
        "Calm and wise with a legendary memory. Never lets a word be forgotten.",
        "Wise, calm, dependable.",
        "Slow, thoughtful, remembers everything you learned.",
        "Vocabulary memory, spaced repetition, reading.",
        "Never Forget: forgotten words come back for review at the perfect time.",
        "wise, calm, dependable", 45, 35, 90, 50,
        "An elephant never forgets, and neither will you.", "thoughtful, calm",
    ),
    (
        "cow", "Cow", "Bos taurus", "#f9a8d4",
        "Kind and patient. Explains grammar slowly, one step at a time.",
        "Kind, patient, steady.",
        "Warm, simple explanations, never in a hurry.",
        "Step-by-step grammar, lessons, review.",
        "Slow Grazing: finished lessons give +15% XP.",
        "kind, patient, steady", 35, 50, 95, 30,
        "Moo~ one sentence at a time.", "kind, simple, patient",
    ),
    (
        "penguin", "Penguin", "Aptenodytes forsteri", "#2dd4bf",
        "Friendly and social. Loves conversations and practicing with friends.",
        "Friendly, social, cheerful.",
        "Chatty, warm, always asks you a question back.",
        "Conversations, speaking, community.",
        "Huddle Up: conversation missions reward +15%.",
        "friendly, social, cheerful", 75, 70, 70, 30,
        "Let's waddle into a conversation!", "chatty, friendly",
    ),
    (
        "owl", "Owl", "Bubo bubo", "#8b5cf6",
        "Wise and thoughtful. Great at grammar puzzles and careful reading.",
        "Wise, analytical, curious.",
        "Asks smart questions and explains the rule behind every answer.",
        "Grammar, reading, detective cases.",
        "Night Scholar: grammar and reading scores +10%.",
        "wise, analytical, curious", 40, 25, 80, 70,
        "Hoo! Let's think this through.", "wise, explanatory",
    ),
]

HSK_LEVELS = [
    (1, "HSK 1", "Foundation. Greetings, numbers, basic daily phrases.", 150, 60),
    (2, "HSK 2", "Daily life, shopping, simple conversations.", 300, 60),
    (3, "HSK 3", "Travel and work scenarios, richer grammar.", 600, 65),
    (4, "HSK 4", "Opinions, news, longer exchanges.", 1200, 70),
    (5, "HSK 5", "Academic and professional Chinese.", 2500, 75),
    (6, "HSK 6", "Near-native fluency and cultural depth.", 5000, 100),
]

SKILLS = [
    ("speaking", "Speaking", "core", "Producing fluent, relevant spoken Chinese."),
    ("listening", "Listening", "core", "Understanding spoken Chinese in context."),
    ("reading", "Reading", "core", "Reading and comprehending characters and texts."),
    ("writing", "Writing", "core", "Writing characters and constructing sentences."),
    ("vocabulary", "Vocabulary", "foundation", "Word knowledge and recall."),
    ("grammar", "Grammar", "foundation", "Sentence structure and patterns."),
    ("tones", "Tones", "voice", "Producing and distinguishing the four tones."),
    ("memory", "Memory", "cognitive", "Retention and recall over time."),
    ("reaction_speed", "Reaction Speed", "cognitive", "Responding quickly and accurately."),
]